

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Linq.Dynamic;
using System.Linq.Expressions;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Telerik.OpenAccess;
using AppFramework.ApplicationLayer.Services;
using KMUH.iKASAWebApi.ApplicationLayer.Assemblers;
using KMUH.iKASAWebApi.ApplicationLayer.DTO;
using KMUH.iKASAWebApi.Infrastructure.Data.Repositories;
using KMUH.iKASAWebApi.DomainModel.Entities;

namespace KMUH.iKASAWebApi.ApplicationLayer.Services
{
	public partial interface I移課程暫存Service : IEntityService<移課程暫存Dto, 移課程暫存>
	{
	}


	public partial class 移課程暫存Service : EntityService<移課程暫存Dto, 移課程暫存>, I移課程暫存Service
	{
		public 移課程暫存Service(I移課程暫存Assembler assembler, I移課程暫存Repository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface I抓MAIL暫存Service : IEntityService<抓MAIL暫存Dto, 抓MAIL暫存>
	{
	}


	public partial class 抓MAIL暫存Service : EntityService<抓MAIL暫存Dto, 抓MAIL暫存>, I抓MAIL暫存Service
	{
		public 抓MAIL暫存Service(I抓MAIL暫存Assembler assembler, I抓MAIL暫存Repository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface I住院醫師暫存Service : IEntityService<住院醫師暫存Dto, 住院醫師暫存>
	{
	}


	public partial class 住院醫師暫存Service : EntityService<住院醫師暫存Dto, 住院醫師暫存>, I住院醫師暫存Service
	{
		public 住院醫師暫存Service(I住院醫師暫存Assembler assembler, I住院醫師暫存Repository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface I西醫受訓人員名單Service : IEntityService<西醫受訓人員名單Dto, 西醫受訓人員名單>
	{
	}


	public partial class 西醫受訓人員名單Service : EntityService<西醫受訓人員名單Dto, 西醫受訓人員名單>, I西醫受訓人員名單Service
	{
		public 西醫受訓人員名單Service(I西醫受訓人員名單Assembler assembler, I西醫受訓人員名單Repository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IVOTEUSERDEFINELISTService : IEntityService<VOTEUSERDEFINELISTDto, VOTEUSERDEFINELIST>
	{
	}


	public partial class VOTEUSERDEFINELISTService : EntityService<VOTEUSERDEFINELISTDto, VOTEUSERDEFINELIST>, IVOTEUSERDEFINELISTService
	{
		public VOTEUSERDEFINELISTService(IVOTEUSERDEFINELISTAssembler assembler, IVOTEUSERDEFINELISTRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IVOTETEMPDATUMService : IEntityService<VOTETEMPDATUMDto, VOTETEMPDATUM>
	{
	}


	public partial class VOTETEMPDATUMService : EntityService<VOTETEMPDATUMDto, VOTETEMPDATUM>, IVOTETEMPDATUMService
	{
		public VOTETEMPDATUMService(IVOTETEMPDATUMAssembler assembler, IVOTETEMPDATUMRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IVOTETARGETService : IEntityService<VOTETARGETDto, VOTETARGET>
	{
	}


	public partial class VOTETARGETService : EntityService<VOTETARGETDto, VOTETARGET>, IVOTETARGETService
	{
		public VOTETARGETService(IVOTETARGETAssembler assembler, IVOTETARGETRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IVOTEMAINService : IEntityService<VOTEMAINDto, VOTEMAIN>
	{
	}


	public partial class VOTEMAINService : EntityService<VOTEMAINDto, VOTEMAIN>, IVOTEMAINService
	{
		public VOTEMAINService(IVOTEMAINAssembler assembler, IVOTEMAINRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IVOTEJOBService : IEntityService<VOTEJOBDto, VOTEJOB>
	{
	}


	public partial class VOTEJOBService : EntityService<VOTEJOBDto, VOTEJOB>, IVOTEJOBService
	{
		public VOTEJOBService(IVOTEJOBAssembler assembler, IVOTEJOBRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IVOTEINSTANCEService : IEntityService<VOTEINSTANCEDto, VOTEINSTANCE>
	{
	}


	public partial class VOTEINSTANCEService : EntityService<VOTEINSTANCEDto, VOTEINSTANCE>, IVOTEINSTANCEService
	{
		public VOTEINSTANCEService(IVOTEINSTANCEAssembler assembler, IVOTEINSTANCERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IVOTEINSDETService : IEntityService<VOTEINSDETDto, VOTEINSDET>
	{
	}


	public partial class VOTEINSDETService : EntityService<VOTEINSDETDto, VOTEINSDET>, IVOTEINSDETService
	{
		public VOTEINSDETService(IVOTEINSDETAssembler assembler, IVOTEINSDETRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IVOTEGROUPService : IEntityService<VOTEGROUPDto, VOTEGROUP>
	{
	}


	public partial class VOTEGROUPService : EntityService<VOTEGROUPDto, VOTEGROUP>, IVOTEGROUPService
	{
		public VOTEGROUPService(IVOTEGROUPAssembler assembler, IVOTEGROUPRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IVOTEGCONDService : IEntityService<VOTEGCONDDto, VOTEGCOND>
	{
	}


	public partial class VOTEGCONDService : EntityService<VOTEGCONDDto, VOTEGCOND>, IVOTEGCONDService
	{
		public VOTEGCONDService(IVOTEGCONDAssembler assembler, IVOTEGCONDRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface ITRAININGTIMEService : IEntityService<TRAININGTIMEDto, TRAININGTIME>
	{
	}


	public partial class TRAININGTIMEService : EntityService<TRAININGTIMEDto, TRAININGTIME>, ITRAININGTIMEService
	{
		public TRAININGTIMEService(ITRAININGTIMEAssembler assembler, ITRAININGTIMERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface ITESTService : IEntityService<TESTDto, TEST>
	{
	}


	public partial class TESTService : EntityService<TESTDto, TEST>, ITESTService
	{
		public TESTService(ITESTAssembler assembler, ITESTRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface ITEACHTIMETYPEService : IEntityService<TEACHTIMETYPEDto, TEACHTIMETYPE>
	{
	}


	public partial class TEACHTIMETYPEService : EntityService<TEACHTIMETYPEDto, TEACHTIMETYPE>, ITEACHTIMETYPEService
	{
		public TEACHTIMETYPEService(ITEACHTIMETYPEAssembler assembler, ITEACHTIMETYPERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface ITEACHTIMERATEService : IEntityService<TEACHTIMERATEDto, TEACHTIMERATE>
	{
	}


	public partial class TEACHTIMERATEService : EntityService<TEACHTIMERATEDto, TEACHTIMERATE>, ITEACHTIMERATEService
	{
		public TEACHTIMERATEService(ITEACHTIMERATEAssembler assembler, ITEACHTIMERATERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface ITEACHTIMEKPIREFTEMPService : IEntityService<TEACHTIMEKPIREFTEMPDto, TEACHTIMEKPIREFTEMP>
	{
	}


	public partial class TEACHTIMEKPIREFTEMPService : EntityService<TEACHTIMEKPIREFTEMPDto, TEACHTIMEKPIREFTEMP>, ITEACHTIMEKPIREFTEMPService
	{
		public TEACHTIMEKPIREFTEMPService(ITEACHTIMEKPIREFTEMPAssembler assembler, ITEACHTIMEKPIREFTEMPRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface ITEACHTIMEKPIREFService : IEntityService<TEACHTIMEKPIREFDto, TEACHTIMEKPIREF>
	{
	}


	public partial class TEACHTIMEKPIREFService : EntityService<TEACHTIMEKPIREFDto, TEACHTIMEKPIREF>, ITEACHTIMEKPIREFService
	{
		public TEACHTIMEKPIREFService(ITEACHTIMEKPIREFAssembler assembler, ITEACHTIMEKPIREFRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface ITEACHPOINTREFService : IEntityService<TEACHPOINTREFDto, TEACHPOINTREF>
	{
	}


	public partial class TEACHPOINTREFService : EntityService<TEACHPOINTREFDto, TEACHPOINTREF>, ITEACHPOINTREFService
	{
		public TEACHPOINTREFService(ITEACHPOINTREFAssembler assembler, ITEACHPOINTREFRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface ITEACHPOINTJOBITEMService : IEntityService<TEACHPOINTJOBITEMDto, TEACHPOINTJOBITEM>
	{
	}


	public partial class TEACHPOINTJOBITEMService : EntityService<TEACHPOINTJOBITEMDto, TEACHPOINTJOBITEM>, ITEACHPOINTJOBITEMService
	{
		public TEACHPOINTJOBITEMService(ITEACHPOINTJOBITEMAssembler assembler, ITEACHPOINTJOBITEMRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface ITEACHPOINTITEMREQUIREService : IEntityService<TEACHPOINTITEMREQUIREDto, TEACHPOINTITEMREQUIRE>
	{
	}


	public partial class TEACHPOINTITEMREQUIREService : EntityService<TEACHPOINTITEMREQUIREDto, TEACHPOINTITEMREQUIRE>, ITEACHPOINTITEMREQUIREService
	{
		public TEACHPOINTITEMREQUIREService(ITEACHPOINTITEMREQUIREAssembler assembler, ITEACHPOINTITEMREQUIRERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface ITEACHPOINTITEMService : IEntityService<TEACHPOINTITEMDto, TEACHPOINTITEM>
	{
	}


	public partial class TEACHPOINTITEMService : EntityService<TEACHPOINTITEMDto, TEACHPOINTITEM>, ITEACHPOINTITEMService
	{
		public TEACHPOINTITEMService(ITEACHPOINTITEMAssembler assembler, ITEACHPOINTITEMRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface ITEACHPOINTEMPITEMDATUMService : IEntityService<TEACHPOINTEMPITEMDATUMDto, TEACHPOINTEMPITEMDATUM>
	{
	}


	public partial class TEACHPOINTEMPITEMDATUMService : EntityService<TEACHPOINTEMPITEMDATUMDto, TEACHPOINTEMPITEMDATUM>, ITEACHPOINTEMPITEMDATUMService
	{
		public TEACHPOINTEMPITEMDATUMService(ITEACHPOINTEMPITEMDATUMAssembler assembler, ITEACHPOINTEMPITEMDATUMRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface ITEACHPOINTCALCTYPEREFService : IEntityService<TEACHPOINTCALCTYPEREFDto, TEACHPOINTCALCTYPEREF>
	{
	}


	public partial class TEACHPOINTCALCTYPEREFService : EntityService<TEACHPOINTCALCTYPEREFDto, TEACHPOINTCALCTYPEREF>, ITEACHPOINTCALCTYPEREFService
	{
		public TEACHPOINTCALCTYPEREFService(ITEACHPOINTCALCTYPEREFAssembler assembler, ITEACHPOINTCALCTYPEREFRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface ITEACHPOINTCALCTYPEService : IEntityService<TEACHPOINTCALCTYPEDto, TEACHPOINTCALCTYPE>
	{
	}


	public partial class TEACHPOINTCALCTYPEService : EntityService<TEACHPOINTCALCTYPEDto, TEACHPOINTCALCTYPE>, ITEACHPOINTCALCTYPEService
	{
		public TEACHPOINTCALCTYPEService(ITEACHPOINTCALCTYPEAssembler assembler, ITEACHPOINTCALCTYPERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface ISCORESETTINGSCORETYPEService : IEntityService<SCORESETTINGSCORETYPEDto, SCORESETTINGSCORETYPE>
	{
	}


	public partial class SCORESETTINGSCORETYPEService : EntityService<SCORESETTINGSCORETYPEDto, SCORESETTINGSCORETYPE>, ISCORESETTINGSCORETYPEService
	{
		public SCORESETTINGSCORETYPEService(ISCORESETTINGSCORETYPEAssembler assembler, ISCORESETTINGSCORETYPERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface ISCORESETTINGJOBService : IEntityService<SCORESETTINGJOBDto, SCORESETTINGJOB>
	{
	}


	public partial class SCORESETTINGJOBService : EntityService<SCORESETTINGJOBDto, SCORESETTINGJOB>, ISCORESETTINGJOBService
	{
		public SCORESETTINGJOBService(ISCORESETTINGJOBAssembler assembler, ISCORESETTINGJOBRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface ISCORESETTINGDETAILService : IEntityService<SCORESETTINGDETAILDto, SCORESETTINGDETAIL>
	{
	}


	public partial class SCORESETTINGDETAILService : EntityService<SCORESETTINGDETAILDto, SCORESETTINGDETAIL>, ISCORESETTINGDETAILService
	{
		public SCORESETTINGDETAILService(ISCORESETTINGDETAILAssembler assembler, ISCORESETTINGDETAILRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface ISCORESETTINGService : IEntityService<SCORESETTINGDto, SCORESETTING>
	{
	}


	public partial class SCORESETTINGService : EntityService<SCORESETTINGDto, SCORESETTING>, ISCORESETTINGService
	{
		public SCORESETTINGService(ISCORESETTINGAssembler assembler, ISCORESETTINGRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface ISCOREINSTANCEDETAILService : IEntityService<SCOREINSTANCEDETAILDto, SCOREINSTANCEDETAIL>
	{
	}


	public partial class SCOREINSTANCEDETAILService : EntityService<SCOREINSTANCEDETAILDto, SCOREINSTANCEDETAIL>, ISCOREINSTANCEDETAILService
	{
		public SCOREINSTANCEDETAILService(ISCOREINSTANCEDETAILAssembler assembler, ISCOREINSTANCEDETAILRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface ISCOREINSTANCEService : IEntityService<SCOREINSTANCEDto, SCOREINSTANCE>
	{
	}


	public partial class SCOREINSTANCEService : EntityService<SCOREINSTANCEDto, SCOREINSTANCE>, ISCOREINSTANCEService
	{
		public SCOREINSTANCEService(ISCOREINSTANCEAssembler assembler, ISCOREINSTANCERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface ISCHEDULERLOGService : IEntityService<SCHEDULERLOGDto, SCHEDULERLOG>
	{
	}


	public partial class SCHEDULERLOGService : EntityService<SCHEDULERLOGDto, SCHEDULERLOG>, ISCHEDULERLOGService
	{
		public SCHEDULERLOGService(ISCHEDULERLOGAssembler assembler, ISCHEDULERLOGRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IR分級資料Service : IEntityService<R分級資料Dto, R分級資料>
	{
	}


	public partial class R分級資料Service : EntityService<R分級資料Dto, R分級資料>, IR分級資料Service
	{
		public R分級資料Service(IR分級資料Assembler assembler, IR分級資料Repository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IREPORTDATATEMPService : IEntityService<REPORTDATATEMPDto, REPORTDATATEMP>
	{
	}


	public partial class REPORTDATATEMPService : EntityService<REPORTDATATEMPDto, REPORTDATATEMP>, IREPORTDATATEMPService
	{
		public REPORTDATATEMPService(IREPORTDATATEMPAssembler assembler, IREPORTDATATEMPRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IRECORDTEMPLATEService : IEntityService<RECORDTEMPLATEDto, RECORDTEMPLATE>
	{
	}


	public partial class RECORDTEMPLATEService : EntityService<RECORDTEMPLATEDto, RECORDTEMPLATE>, IRECORDTEMPLATEService
	{
		public RECORDTEMPLATEService(IRECORDTEMPLATEAssembler assembler, IRECORDTEMPLATERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IRECORDINSVIEWERService : IEntityService<RECORDINSVIEWERDto, RECORDINSVIEWER>
	{
	}


	public partial class RECORDINSVIEWERService : EntityService<RECORDINSVIEWERDto, RECORDINSVIEWER>, IRECORDINSVIEWERService
	{
		public RECORDINSVIEWERService(IRECORDINSVIEWERAssembler assembler, IRECORDINSVIEWERRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IRECORDINSTANCEREJECTLOGService : IEntityService<RECORDINSTANCEREJECTLOGDto, RECORDINSTANCEREJECTLOG>
	{
	}


	public partial class RECORDINSTANCEREJECTLOGService : EntityService<RECORDINSTANCEREJECTLOGDto, RECORDINSTANCEREJECTLOG>, IRECORDINSTANCEREJECTLOGService
	{
		public RECORDINSTANCEREJECTLOGService(IRECORDINSTANCEREJECTLOGAssembler assembler, IRECORDINSTANCEREJECTLOGRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IRECORDINSTANCEService : IEntityService<RECORDINSTANCEDto, RECORDINSTANCE>
	{
	}


	public partial class RECORDINSTANCEService : EntityService<RECORDINSTANCEDto, RECORDINSTANCE>, IRECORDINSTANCEService
	{
		public RECORDINSTANCEService(IRECORDINSTANCEAssembler assembler, IRECORDINSTANCERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IRECORDINSSIGNINService : IEntityService<RECORDINSSIGNINDto, RECORDINSSIGNIN>
	{
	}


	public partial class RECORDINSSIGNINService : EntityService<RECORDINSSIGNINDto, RECORDINSSIGNIN>, IRECORDINSSIGNINService
	{
		public RECORDINSSIGNINService(IRECORDINSSIGNINAssembler assembler, IRECORDINSSIGNINRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IRECORDINSREADERService : IEntityService<RECORDINSREADERDto, RECORDINSREADER>
	{
	}


	public partial class RECORDINSREADERService : EntityService<RECORDINSREADERDto, RECORDINSREADER>, IRECORDINSREADERService
	{
		public RECORDINSREADERService(IRECORDINSREADERAssembler assembler, IRECORDINSREADERRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IRECORDINSDETService : IEntityService<RECORDINSDETDto, RECORDINSDET>
	{
	}


	public partial class RECORDINSDETService : EntityService<RECORDINSDETDto, RECORDINSDET>, IRECORDINSDETService
	{
		public RECORDINSDETService(IRECORDINSDETAssembler assembler, IRECORDINSDETRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IRECORDEDUACTREFService : IEntityService<RECORDEDUACTREFDto, RECORDEDUACTREF>
	{
	}


	public partial class RECORDEDUACTREFService : EntityService<RECORDEDUACTREFDto, RECORDEDUACTREF>, IRECORDEDUACTREFService
	{
		public RECORDEDUACTREFService(IRECORDEDUACTREFAssembler assembler, IRECORDEDUACTREFRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IPSNOPDService : IEntityService<PSNOPDDto, PSNOPD>
	{
	}


	public partial class PSNOPDService : EntityService<PSNOPDDto, PSNOPD>, IPSNOPDService
	{
		public PSNOPDService(IPSNOPDAssembler assembler, IPSNOPDRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IPASSPORTSTUDENTAPPLICATIONITEMFAILLOGService : IEntityService<PASSPORTSTUDENTAPPLICATIONITEMFAILLOGDto, PASSPORTSTUDENTAPPLICATIONITEMFAILLOG>
	{
	}


	public partial class PASSPORTSTUDENTAPPLICATIONITEMFAILLOGService : EntityService<PASSPORTSTUDENTAPPLICATIONITEMFAILLOGDto, PASSPORTSTUDENTAPPLICATIONITEMFAILLOG>, IPASSPORTSTUDENTAPPLICATIONITEMFAILLOGService
	{
		public PASSPORTSTUDENTAPPLICATIONITEMFAILLOGService(IPASSPORTSTUDENTAPPLICATIONITEMFAILLOGAssembler assembler, IPASSPORTSTUDENTAPPLICATIONITEMFAILLOGRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IPASSPORTSTUDENTAPPLICATIONITEM_BK2Service : IEntityService<PASSPORTSTUDENTAPPLICATIONITEM_BK2Dto, PASSPORTSTUDENTAPPLICATIONITEM_BK2>
	{
	}


	public partial class PASSPORTSTUDENTAPPLICATIONITEM_BK2Service : EntityService<PASSPORTSTUDENTAPPLICATIONITEM_BK2Dto, PASSPORTSTUDENTAPPLICATIONITEM_BK2>, IPASSPORTSTUDENTAPPLICATIONITEM_BK2Service
	{
		public PASSPORTSTUDENTAPPLICATIONITEM_BK2Service(IPASSPORTSTUDENTAPPLICATIONITEM_BK2Assembler assembler, IPASSPORTSTUDENTAPPLICATIONITEM_BK2Repository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IPASSPORTSTUDENTAPPLICATIONITEM_BKService : IEntityService<PASSPORTSTUDENTAPPLICATIONITEM_BKDto, PASSPORTSTUDENTAPPLICATIONITEM_BK>
	{
	}


	public partial class PASSPORTSTUDENTAPPLICATIONITEM_BKService : EntityService<PASSPORTSTUDENTAPPLICATIONITEM_BKDto, PASSPORTSTUDENTAPPLICATIONITEM_BK>, IPASSPORTSTUDENTAPPLICATIONITEM_BKService
	{
		public PASSPORTSTUDENTAPPLICATIONITEM_BKService(IPASSPORTSTUDENTAPPLICATIONITEM_BKAssembler assembler, IPASSPORTSTUDENTAPPLICATIONITEM_BKRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IPASSPORTSTUDENTAPPLICATIONITEMService : IEntityService<PASSPORTSTUDENTAPPLICATIONITEMDto, PASSPORTSTUDENTAPPLICATIONITEM>
	{
	}


	public partial class PASSPORTSTUDENTAPPLICATIONITEMService : EntityService<PASSPORTSTUDENTAPPLICATIONITEMDto, PASSPORTSTUDENTAPPLICATIONITEM>, IPASSPORTSTUDENTAPPLICATIONITEMService
	{
		public PASSPORTSTUDENTAPPLICATIONITEMService(IPASSPORTSTUDENTAPPLICATIONITEMAssembler assembler, IPASSPORTSTUDENTAPPLICATIONITEMRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IPASSPORTSPECIALLISTService : IEntityService<PASSPORTSPECIALLISTDto, PASSPORTSPECIALLIST>
	{
	}


	public partial class PASSPORTSPECIALLISTService : EntityService<PASSPORTSPECIALLISTDto, PASSPORTSPECIALLIST>, IPASSPORTSPECIALLISTService
	{
		public PASSPORTSPECIALLISTService(IPASSPORTSPECIALLISTAssembler assembler, IPASSPORTSPECIALLISTRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IPASSPORTJOBTITLEITEM_BKService : IEntityService<PASSPORTJOBTITLEITEM_BKDto, PASSPORTJOBTITLEITEM_BK>
	{
	}


	public partial class PASSPORTJOBTITLEITEM_BKService : EntityService<PASSPORTJOBTITLEITEM_BKDto, PASSPORTJOBTITLEITEM_BK>, IPASSPORTJOBTITLEITEM_BKService
	{
		public PASSPORTJOBTITLEITEM_BKService(IPASSPORTJOBTITLEITEM_BKAssembler assembler, IPASSPORTJOBTITLEITEM_BKRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IPASSPORTJOBTITLEITEMService : IEntityService<PASSPORTJOBTITLEITEMDto, PASSPORTJOBTITLEITEM>
	{
	}


	public partial class PASSPORTJOBTITLEITEMService : EntityService<PASSPORTJOBTITLEITEMDto, PASSPORTJOBTITLEITEM>, IPASSPORTJOBTITLEITEMService
	{
		public PASSPORTJOBTITLEITEMService(IPASSPORTJOBTITLEITEMAssembler assembler, IPASSPORTJOBTITLEITEMRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IPASSPORTJOBFINALMANService : IEntityService<PASSPORTJOBFINALMANDto, PASSPORTJOBFINALMAN>
	{
	}


	public partial class PASSPORTJOBFINALMANService : EntityService<PASSPORTJOBFINALMANDto, PASSPORTJOBFINALMAN>, IPASSPORTJOBFINALMANService
	{
		public PASSPORTJOBFINALMANService(IPASSPORTJOBFINALMANAssembler assembler, IPASSPORTJOBFINALMANRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IPASSPORTDOCGRADEService : IEntityService<PASSPORTDOCGRADEDto, PASSPORTDOCGRADE>
	{
	}


	public partial class PASSPORTDOCGRADEService : EntityService<PASSPORTDOCGRADEDto, PASSPORTDOCGRADE>, IPASSPORTDOCGRADEService
	{
		public PASSPORTDOCGRADEService(IPASSPORTDOCGRADEAssembler assembler, IPASSPORTDOCGRADERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IPASSPORTCHECKITEMService : IEntityService<PASSPORTCHECKITEMDto, PASSPORTCHECKITEM>
	{
	}


	public partial class PASSPORTCHECKITEMService : EntityService<PASSPORTCHECKITEMDto, PASSPORTCHECKITEM>, IPASSPORTCHECKITEMService
	{
		public PASSPORTCHECKITEMService(IPASSPORTCHECKITEMAssembler assembler, IPASSPORTCHECKITEMRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IOSCECERTService : IEntityService<OSCECERTDto, OSCECERT>
	{
	}


	public partial class OSCECERTService : EntityService<OSCECERTDto, OSCECERT>, IOSCECERTService
	{
		public OSCECERTService(IOSCECERTAssembler assembler, IOSCECERTRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IOSCEBLOCKTIMEService : IEntityService<OSCEBLOCKTIMEDto, OSCEBLOCKTIME>
	{
	}


	public partial class OSCEBLOCKTIMEService : EntityService<OSCEBLOCKTIMEDto, OSCEBLOCKTIME>, IOSCEBLOCKTIMEService
	{
		public OSCEBLOCKTIMEService(IOSCEBLOCKTIMEAssembler assembler, IOSCEBLOCKTIMERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface INURSELISTService : IEntityService<NURSELISTDto, NURSELIST>
	{
	}


	public partial class NURSELISTService : EntityService<NURSELISTDto, NURSELIST>, INURSELISTService
	{
		public NURSELISTService(INURSELISTAssembler assembler, INURSELISTRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface INNOTEITEMService : IEntityService<NNOTEITEMDto, NNOTEITEM>
	{
	}


	public partial class NNOTEITEMService : EntityService<NNOTEITEMDto, NNOTEITEM>, INNOTEITEMService
	{
		public NNOTEITEMService(INNOTEITEMAssembler assembler, INNOTEITEMRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface INNOTEService : IEntityService<NNOTEDto, NNOTE>
	{
	}


	public partial class NNOTEService : EntityService<NNOTEDto, NNOTE>, INNOTEService
	{
		public NNOTEService(INNOTEAssembler assembler, INNOTERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface INEWSVIEWTARGETService : IEntityService<NEWSVIEWTARGETDto, NEWSVIEWTARGET>
	{
	}


	public partial class NEWSVIEWTARGETService : EntityService<NEWSVIEWTARGETDto, NEWSVIEWTARGET>, INEWSVIEWTARGETService
	{
		public NEWSVIEWTARGETService(INEWSVIEWTARGETAssembler assembler, INEWSVIEWTARGETRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface INEWS_ATTACHMENTService : IEntityService<NEWS_ATTACHMENTDto, NEWS_ATTACHMENT>
	{
	}


	public partial class NEWS_ATTACHMENTService : EntityService<NEWS_ATTACHMENTDto, NEWS_ATTACHMENT>, INEWS_ATTACHMENTService
	{
		public NEWS_ATTACHMENTService(INEWS_ATTACHMENTAssembler assembler, INEWS_ATTACHMENTRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface INEWSService : IEntityService<NEWSDto, NEWS>
	{
	}


	public partial class NEWSService : EntityService<NEWSDto, NEWS>, INEWSService
	{
		public NEWSService(INEWSAssembler assembler, INEWSRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IMYLISTDETService : IEntityService<MYLISTDETDto, MYLISTDET>
	{
	}


	public partial class MYLISTDETService : EntityService<MYLISTDETDto, MYLISTDET>, IMYLISTDETService
	{
		public MYLISTDETService(IMYLISTDETAssembler assembler, IMYLISTDETRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IMYLISTService : IEntityService<MYLISTDto, MYLIST>
	{
	}


	public partial class MYLISTService : EntityService<MYLISTDto, MYLIST>, IMYLISTService
	{
		public MYLISTService(IMYLISTAssembler assembler, IMYLISTRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IMONTHLYTEACHPOINTCALCDATUMService : IEntityService<MONTHLYTEACHPOINTCALCDATUMDto, MONTHLYTEACHPOINTCALCDATUM>
	{
	}


	public partial class MONTHLYTEACHPOINTCALCDATUMService : EntityService<MONTHLYTEACHPOINTCALCDATUMDto, MONTHLYTEACHPOINTCALCDATUM>, IMONTHLYTEACHPOINTCALCDATUMService
	{
		public MONTHLYTEACHPOINTCALCDATUMService(IMONTHLYTEACHPOINTCALCDATUMAssembler assembler, IMONTHLYTEACHPOINTCALCDATUMRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IMESSAGEBOARDService : IEntityService<MESSAGEBOARDDto, MESSAGEBOARD>
	{
	}


	public partial class MESSAGEBOARDService : EntityService<MESSAGEBOARDDto, MESSAGEBOARD>, IMESSAGEBOARDService
	{
		public MESSAGEBOARDService(IMESSAGEBOARDAssembler assembler, IMESSAGEBOARDRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IMEMBER_BKService : IEntityService<MEMBER_BKDto, MEMBER_BK>
	{
	}


	public partial class MEMBER_BKService : EntityService<MEMBER_BKDto, MEMBER_BK>, IMEMBER_BKService
	{
		public MEMBER_BKService(IMEMBER_BKAssembler assembler, IMEMBER_BKRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IMEMBERService : IEntityService<MEMBERDto, MEMBER>
	{
	}


	public partial class MEMBERService : EntityService<MEMBERDto, MEMBER>, IMEMBERService
	{
		public MEMBERService(IMEMBERAssembler assembler, IMEMBERRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IMEDICALVOTELISTService : IEntityService<MEDICALVOTELISTDto, MEDICALVOTELIST>
	{
	}


	public partial class MEDICALVOTELISTService : EntityService<MEDICALVOTELISTDto, MEDICALVOTELIST>, IMEDICALVOTELISTService
	{
		public MEDICALVOTELISTService(IMEDICALVOTELISTAssembler assembler, IMEDICALVOTELISTRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IMEDICALTEACHPOINTService : IEntityService<MEDICALTEACHPOINTDto, MEDICALTEACHPOINT>
	{
	}


	public partial class MEDICALTEACHPOINTService : EntityService<MEDICALTEACHPOINTDto, MEDICALTEACHPOINT>, IMEDICALTEACHPOINTService
	{
		public MEDICALTEACHPOINTService(IMEDICALTEACHPOINTAssembler assembler, IMEDICALTEACHPOINTRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface ILOGINLOGService : IEntityService<LOGINLOGDto, LOGINLOG>
	{
	}


	public partial class LOGINLOGService : EntityService<LOGINLOGDto, LOGINLOG>, ILOGINLOGService
	{
		public LOGINLOGService(ILOGINLOGAssembler assembler, ILOGINLOGRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IJOBFORMSETTINGService : IEntityService<JOBFORMSETTINGDto, JOBFORMSETTING>
	{
	}


	public partial class JOBFORMSETTINGService : EntityService<JOBFORMSETTINGDto, JOBFORMSETTING>, IJOBFORMSETTINGService
	{
		public JOBFORMSETTINGService(IJOBFORMSETTINGAssembler assembler, IJOBFORMSETTINGRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IIMPORTTEMPService : IEntityService<IMPORTTEMPDto, IMPORTTEMP>
	{
	}


	public partial class IMPORTTEMPService : EntityService<IMPORTTEMPDto, IMPORTTEMP>, IIMPORTTEMPService
	{
		public IMPORTTEMPService(IIMPORTTEMPAssembler assembler, IIMPORTTEMPRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IIKASA_UPLOADFILEService : IEntityService<IKASA_UPLOADFILEDto, IKASA_UPLOADFILE>
	{
	}


	public partial class IKASA_UPLOADFILEService : EntityService<IKASA_UPLOADFILEDto, IKASA_UPLOADFILE>, IIKASA_UPLOADFILEService
	{
		public IKASA_UPLOADFILEService(IIKASA_UPLOADFILEAssembler assembler, IIKASA_UPLOADFILERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IIKASA_OSCEEXAMSTAGEService : IEntityService<IKASA_OSCEEXAMSTAGEDto, IKASA_OSCEEXAMSTAGE>
	{
	}


	public partial class IKASA_OSCEEXAMSTAGEService : EntityService<IKASA_OSCEEXAMSTAGEDto, IKASA_OSCEEXAMSTAGE>, IIKASA_OSCEEXAMSTAGEService
	{
		public IKASA_OSCEEXAMSTAGEService(IIKASA_OSCEEXAMSTAGEAssembler assembler, IIKASA_OSCEEXAMSTAGERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IIKASA_OSCEEXAMSCOREService : IEntityService<IKASA_OSCEEXAMSCOREDto, IKASA_OSCEEXAMSCORE>
	{
	}


	public partial class IKASA_OSCEEXAMSCOREService : EntityService<IKASA_OSCEEXAMSCOREDto, IKASA_OSCEEXAMSCORE>, IIKASA_OSCEEXAMSCOREService
	{
		public IKASA_OSCEEXAMSCOREService(IIKASA_OSCEEXAMSCOREAssembler assembler, IIKASA_OSCEEXAMSCORERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IIKASA_OSCEEXAMService : IEntityService<IKASA_OSCEEXAMDto, IKASA_OSCEEXAM>
	{
	}


	public partial class IKASA_OSCEEXAMService : EntityService<IKASA_OSCEEXAMDto, IKASA_OSCEEXAM>, IIKASA_OSCEEXAMService
	{
		public IKASA_OSCEEXAMService(IIKASA_OSCEEXAMAssembler assembler, IIKASA_OSCEEXAMRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IIKASA_MENUREFService : IEntityService<IKASA_MENUREFDto, IKASA_MENUREF>
	{
	}


	public partial class IKASA_MENUREFService : EntityService<IKASA_MENUREFDto, IKASA_MENUREF>, IIKASA_MENUREFService
	{
		public IKASA_MENUREFService(IIKASA_MENUREFAssembler assembler, IIKASA_MENUREFRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IIKASA_MENUPARAMService : IEntityService<IKASA_MENUPARAMDto, IKASA_MENUPARAM>
	{
	}


	public partial class IKASA_MENUPARAMService : EntityService<IKASA_MENUPARAMDto, IKASA_MENUPARAM>, IIKASA_MENUPARAMService
	{
		public IKASA_MENUPARAMService(IIKASA_MENUPARAMAssembler assembler, IIKASA_MENUPARAMRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IIKASA_MENUService : IEntityService<IKASA_MENUDto, IKASA_MENU>
	{
	}


	public partial class IKASA_MENUService : EntityService<IKASA_MENUDto, IKASA_MENU>, IIKASA_MENUService
	{
		public IKASA_MENUService(IIKASA_MENUAssembler assembler, IIKASA_MENURepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IIKASA_IPDDATACOUNTService : IEntityService<IKASA_IPDDATACOUNTDto, IKASA_IPDDATACOUNT>
	{
	}


	public partial class IKASA_IPDDATACOUNTService : EntityService<IKASA_IPDDATACOUNTDto, IKASA_IPDDATACOUNT>, IIKASA_IPDDATACOUNTService
	{
		public IKASA_IPDDATACOUNTService(IIKASA_IPDDATACOUNTAssembler assembler, IIKASA_IPDDATACOUNTRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IIKASA_ERCASE_EVALDETService : IEntityService<IKASA_ERCASE_EVALDETDto, IKASA_ERCASE_EVALDET>
	{
	}


	public partial class IKASA_ERCASE_EVALDETService : EntityService<IKASA_ERCASE_EVALDETDto, IKASA_ERCASE_EVALDET>, IIKASA_ERCASE_EVALDETService
	{
		public IKASA_ERCASE_EVALDETService(IIKASA_ERCASE_EVALDETAssembler assembler, IIKASA_ERCASE_EVALDETRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IIKASA_ERCASE_EVALService : IEntityService<IKASA_ERCASE_EVALDto, IKASA_ERCASE_EVAL>
	{
	}


	public partial class IKASA_ERCASE_EVALService : EntityService<IKASA_ERCASE_EVALDto, IKASA_ERCASE_EVAL>, IIKASA_ERCASE_EVALService
	{
		public IKASA_ERCASE_EVALService(IIKASA_ERCASE_EVALAssembler assembler, IIKASA_ERCASE_EVALRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IIKASA_ERCASEService : IEntityService<IKASA_ERCASEDto, IKASA_ERCASE>
	{
	}


	public partial class IKASA_ERCASEService : EntityService<IKASA_ERCASEDto, IKASA_ERCASE>, IIKASA_ERCASEService
	{
		public IKASA_ERCASEService(IIKASA_ERCASEAssembler assembler, IIKASA_ERCASERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IIKASA_ACTUPLOADFILEService : IEntityService<IKASA_ACTUPLOADFILEDto, IKASA_ACTUPLOADFILE>
	{
	}


	public partial class IKASA_ACTUPLOADFILEService : EntityService<IKASA_ACTUPLOADFILEDto, IKASA_ACTUPLOADFILE>, IIKASA_ACTUPLOADFILEService
	{
		public IKASA_ACTUPLOADFILEService(IIKASA_ACTUPLOADFILEAssembler assembler, IIKASA_ACTUPLOADFILERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IHEALTEACHTIMERATEService : IEntityService<HEALTEACHTIMERATEDto, HEALTEACHTIMERATE>
	{
	}


	public partial class HEALTEACHTIMERATEService : EntityService<HEALTEACHTIMERATEDto, HEALTEACHTIMERATE>, IHEALTEACHTIMERATEService
	{
		public HEALTEACHTIMERATEService(IHEALTEACHTIMERATEAssembler assembler, IHEALTEACHTIMERATERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IHEALTEACHTIMEService : IEntityService<HEALTEACHTIMEDto, HEALTEACHTIME>
	{
	}


	public partial class HEALTEACHTIMEService : EntityService<HEALTEACHTIMEDto, HEALTEACHTIME>, IHEALTEACHTIMEService
	{
		public HEALTEACHTIMEService(IHEALTEACHTIMEAssembler assembler, IHEALTEACHTIMERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IGOODVSDATADEService : IEntityService<GOODVSDATADEDto, GOODVSDATADE>
	{
	}


	public partial class GOODVSDATADEService : EntityService<GOODVSDATADEDto, GOODVSDATADE>, IGOODVSDATADEService
	{
		public GOODVSDATADEService(IGOODVSDATADEAssembler assembler, IGOODVSDATADERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IGOODVSDATUMService : IEntityService<GOODVSDATUMDto, GOODVSDATUM>
	{
	}


	public partial class GOODVSDATUMService : EntityService<GOODVSDATUMDto, GOODVSDATUM>, IGOODVSDATUMService
	{
		public GOODVSDATUMService(IGOODVSDATUMAssembler assembler, IGOODVSDATUMRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORMCATEGORYREFService : IEntityService<FORMCATEGORYREFDto, FORMCATEGORYREF>
	{
	}


	public partial class FORMCATEGORYREFService : EntityService<FORMCATEGORYREFDto, FORMCATEGORYREF>, IFORMCATEGORYREFService
	{
		public FORMCATEGORYREFService(IFORMCATEGORYREFAssembler assembler, IFORMCATEGORYREFRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORMCATEGORYService : IEntityService<FORMCATEGORYDto, FORMCATEGORY>
	{
	}


	public partial class FORMCATEGORYService : EntityService<FORMCATEGORYDto, FORMCATEGORY>, IFORMCATEGORYService
	{
		public FORMCATEGORYService(IFORMCATEGORYAssembler assembler, IFORMCATEGORYRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_TODO_LISTService : IEntityService<FORM_TODO_LISTDto, FORM_TODO_LIST>
	{
	}


	public partial class FORM_TODO_LISTService : EntityService<FORM_TODO_LISTDto, FORM_TODO_LIST>, IFORM_TODO_LISTService
	{
		public FORM_TODO_LISTService(IFORM_TODO_LISTAssembler assembler, IFORM_TODO_LISTRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_TEMPLATES_BKService : IEntityService<FORM_TEMPLATES_BKDto, FORM_TEMPLATES_BK>
	{
	}


	public partial class FORM_TEMPLATES_BKService : EntityService<FORM_TEMPLATES_BKDto, FORM_TEMPLATES_BK>, IFORM_TEMPLATES_BKService
	{
		public FORM_TEMPLATES_BKService(IFORM_TEMPLATES_BKAssembler assembler, IFORM_TEMPLATES_BKRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_TEMPLATEService : IEntityService<FORM_TEMPLATEDto, FORM_TEMPLATE>
	{
	}


	public partial class FORM_TEMPLATEService : EntityService<FORM_TEMPLATEDto, FORM_TEMPLATE>, IFORM_TEMPLATEService
	{
		public FORM_TEMPLATEService(IFORM_TEMPLATEAssembler assembler, IFORM_TEMPLATERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_SUBMIT_SQLService : IEntityService<FORM_TEMPLATE_SUBMIT_SQLDto, FORM_TEMPLATE_SUBMIT_SQL>
	{
	}


	public partial class FORM_TEMPLATE_SUBMIT_SQLService : EntityService<FORM_TEMPLATE_SUBMIT_SQLDto, FORM_TEMPLATE_SUBMIT_SQL>, IFORM_TEMPLATE_SUBMIT_SQLService
	{
		public FORM_TEMPLATE_SUBMIT_SQLService(IFORM_TEMPLATE_SUBMIT_SQLAssembler assembler, IFORM_TEMPLATE_SUBMIT_SQLRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_SQLService : IEntityService<FORM_TEMPLATE_SQLDto, FORM_TEMPLATE_SQL>
	{
	}


	public partial class FORM_TEMPLATE_SQLService : EntityService<FORM_TEMPLATE_SQLDto, FORM_TEMPLATE_SQL>, IFORM_TEMPLATE_SQLService
	{
		public FORM_TEMPLATE_SQLService(IFORM_TEMPLATE_SQLAssembler assembler, IFORM_TEMPLATE_SQLRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_SINGLEService : IEntityService<FORM_TEMPLATE_SINGLEDto, FORM_TEMPLATE_SINGLE>
	{
	}


	public partial class FORM_TEMPLATE_SINGLEService : EntityService<FORM_TEMPLATE_SINGLEDto, FORM_TEMPLATE_SINGLE>, IFORM_TEMPLATE_SINGLEService
	{
		public FORM_TEMPLATE_SINGLEService(IFORM_TEMPLATE_SINGLEAssembler assembler, IFORM_TEMPLATE_SINGLERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_SCRIPTService : IEntityService<FORM_TEMPLATE_SCRIPTDto, FORM_TEMPLATE_SCRIPT>
	{
	}


	public partial class FORM_TEMPLATE_SCRIPTService : EntityService<FORM_TEMPLATE_SCRIPTDto, FORM_TEMPLATE_SCRIPT>, IFORM_TEMPLATE_SCRIPTService
	{
		public FORM_TEMPLATE_SCRIPTService(IFORM_TEMPLATE_SCRIPTAssembler assembler, IFORM_TEMPLATE_SCRIPTRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_PERMISSIONService : IEntityService<FORM_TEMPLATE_PERMISSIONDto, FORM_TEMPLATE_PERMISSION>
	{
	}


	public partial class FORM_TEMPLATE_PERMISSIONService : EntityService<FORM_TEMPLATE_PERMISSIONDto, FORM_TEMPLATE_PERMISSION>, IFORM_TEMPLATE_PERMISSIONService
	{
		public FORM_TEMPLATE_PERMISSIONService(IFORM_TEMPLATE_PERMISSIONAssembler assembler, IFORM_TEMPLATE_PERMISSIONRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_NECESSARYService : IEntityService<FORM_TEMPLATE_NECESSARYDto, FORM_TEMPLATE_NECESSARY>
	{
	}


	public partial class FORM_TEMPLATE_NECESSARYService : EntityService<FORM_TEMPLATE_NECESSARYDto, FORM_TEMPLATE_NECESSARY>, IFORM_TEMPLATE_NECESSARYService
	{
		public FORM_TEMPLATE_NECESSARYService(IFORM_TEMPLATE_NECESSARYAssembler assembler, IFORM_TEMPLATE_NECESSARYRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_LIBRARY_OPTIONService : IEntityService<FORM_TEMPLATE_LIBRARY_OPTIONDto, FORM_TEMPLATE_LIBRARY_OPTION>
	{
	}


	public partial class FORM_TEMPLATE_LIBRARY_OPTIONService : EntityService<FORM_TEMPLATE_LIBRARY_OPTIONDto, FORM_TEMPLATE_LIBRARY_OPTION>, IFORM_TEMPLATE_LIBRARY_OPTIONService
	{
		public FORM_TEMPLATE_LIBRARY_OPTIONService(IFORM_TEMPLATE_LIBRARY_OPTIONAssembler assembler, IFORM_TEMPLATE_LIBRARY_OPTIONRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_LIBRARYService : IEntityService<FORM_TEMPLATE_LIBRARYDto, FORM_TEMPLATE_LIBRARY>
	{
	}


	public partial class FORM_TEMPLATE_LIBRARYService : EntityService<FORM_TEMPLATE_LIBRARYDto, FORM_TEMPLATE_LIBRARY>, IFORM_TEMPLATE_LIBRARYService
	{
		public FORM_TEMPLATE_LIBRARYService(IFORM_TEMPLATE_LIBRARYAssembler assembler, IFORM_TEMPLATE_LIBRARYRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_IMAGEService : IEntityService<FORM_TEMPLATE_IMAGEDto, FORM_TEMPLATE_IMAGE>
	{
	}


	public partial class FORM_TEMPLATE_IMAGEService : EntityService<FORM_TEMPLATE_IMAGEDto, FORM_TEMPLATE_IMAGE>, IFORM_TEMPLATE_IMAGEService
	{
		public FORM_TEMPLATE_IMAGEService(IFORM_TEMPLATE_IMAGEAssembler assembler, IFORM_TEMPLATE_IMAGERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_GROUPS_BKService : IEntityService<FORM_TEMPLATE_GROUPS_BKDto, FORM_TEMPLATE_GROUPS_BK>
	{
	}


	public partial class FORM_TEMPLATE_GROUPS_BKService : EntityService<FORM_TEMPLATE_GROUPS_BKDto, FORM_TEMPLATE_GROUPS_BK>, IFORM_TEMPLATE_GROUPS_BKService
	{
		public FORM_TEMPLATE_GROUPS_BKService(IFORM_TEMPLATE_GROUPS_BKAssembler assembler, IFORM_TEMPLATE_GROUPS_BKRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_GROUPService : IEntityService<FORM_TEMPLATE_GROUPDto, FORM_TEMPLATE_GROUP>
	{
	}


	public partial class FORM_TEMPLATE_GROUPService : EntityService<FORM_TEMPLATE_GROUPDto, FORM_TEMPLATE_GROUP>, IFORM_TEMPLATE_GROUPService
	{
		public FORM_TEMPLATE_GROUPService(IFORM_TEMPLATE_GROUPAssembler assembler, IFORM_TEMPLATE_GROUPRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_EXPRESSIONService : IEntityService<FORM_TEMPLATE_EXPRESSIONDto, FORM_TEMPLATE_EXPRESSION>
	{
	}


	public partial class FORM_TEMPLATE_EXPRESSIONService : EntityService<FORM_TEMPLATE_EXPRESSIONDto, FORM_TEMPLATE_EXPRESSION>, IFORM_TEMPLATE_EXPRESSIONService
	{
		public FORM_TEMPLATE_EXPRESSIONService(IFORM_TEMPLATE_EXPRESSIONAssembler assembler, IFORM_TEMPLATE_EXPRESSIONRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_ELEMENTS_BKService : IEntityService<FORM_TEMPLATE_ELEMENTS_BKDto, FORM_TEMPLATE_ELEMENTS_BK>
	{
	}


	public partial class FORM_TEMPLATE_ELEMENTS_BKService : EntityService<FORM_TEMPLATE_ELEMENTS_BKDto, FORM_TEMPLATE_ELEMENTS_BK>, IFORM_TEMPLATE_ELEMENTS_BKService
	{
		public FORM_TEMPLATE_ELEMENTS_BKService(IFORM_TEMPLATE_ELEMENTS_BKAssembler assembler, IFORM_TEMPLATE_ELEMENTS_BKRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_ELEMENTService : IEntityService<FORM_TEMPLATE_ELEMENTDto, FORM_TEMPLATE_ELEMENT>
	{
	}


	public partial class FORM_TEMPLATE_ELEMENTService : EntityService<FORM_TEMPLATE_ELEMENTDto, FORM_TEMPLATE_ELEMENT>, IFORM_TEMPLATE_ELEMENTService
	{
		public FORM_TEMPLATE_ELEMENTService(IFORM_TEMPLATE_ELEMENTAssembler assembler, IFORM_TEMPLATE_ELEMENTRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_ELEMENT_READONLYService : IEntityService<FORM_TEMPLATE_ELEMENT_READONLYDto, FORM_TEMPLATE_ELEMENT_READONLY>
	{
	}


	public partial class FORM_TEMPLATE_ELEMENT_READONLYService : EntityService<FORM_TEMPLATE_ELEMENT_READONLYDto, FORM_TEMPLATE_ELEMENT_READONLY>, IFORM_TEMPLATE_ELEMENT_READONLYService
	{
		public FORM_TEMPLATE_ELEMENT_READONLYService(IFORM_TEMPLATE_ELEMENT_READONLYAssembler assembler, IFORM_TEMPLATE_ELEMENT_READONLYRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_DYNAMIC_ELEMENTService : IEntityService<FORM_TEMPLATE_DYNAMIC_ELEMENTDto, FORM_TEMPLATE_DYNAMIC_ELEMENT>
	{
	}


	public partial class FORM_TEMPLATE_DYNAMIC_ELEMENTService : EntityService<FORM_TEMPLATE_DYNAMIC_ELEMENTDto, FORM_TEMPLATE_DYNAMIC_ELEMENT>, IFORM_TEMPLATE_DYNAMIC_ELEMENTService
	{
		public FORM_TEMPLATE_DYNAMIC_ELEMENTService(IFORM_TEMPLATE_DYNAMIC_ELEMENTAssembler assembler, IFORM_TEMPLATE_DYNAMIC_ELEMENTRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_OPTION_TYPEService : IEntityService<FORM_OPTION_TYPEDto, FORM_OPTION_TYPE>
	{
	}


	public partial class FORM_OPTION_TYPEService : EntityService<FORM_OPTION_TYPEDto, FORM_OPTION_TYPE>, IFORM_OPTION_TYPEService
	{
		public FORM_OPTION_TYPEService(IFORM_OPTION_TYPEAssembler assembler, IFORM_OPTION_TYPERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_INSTANCES_DELLOGService : IEntityService<FORM_INSTANCES_DELLOGDto, FORM_INSTANCES_DELLOG>
	{
	}


	public partial class FORM_INSTANCES_DELLOGService : EntityService<FORM_INSTANCES_DELLOGDto, FORM_INSTANCES_DELLOG>, IFORM_INSTANCES_DELLOGService
	{
		public FORM_INSTANCES_DELLOGService(IFORM_INSTANCES_DELLOGAssembler assembler, IFORM_INSTANCES_DELLOGRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_INSTANCES_BKService : IEntityService<FORM_INSTANCES_BKDto, FORM_INSTANCES_BK>
	{
	}


	public partial class FORM_INSTANCES_BKService : EntityService<FORM_INSTANCES_BKDto, FORM_INSTANCES_BK>, IFORM_INSTANCES_BKService
	{
		public FORM_INSTANCES_BKService(IFORM_INSTANCES_BKAssembler assembler, IFORM_INSTANCES_BKRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_INSTANCEService : IEntityService<FORM_INSTANCEDto, FORM_INSTANCE>
	{
	}


	public partial class FORM_INSTANCEService : EntityService<FORM_INSTANCEDto, FORM_INSTANCE>, IFORM_INSTANCEService
	{
		public FORM_INSTANCEService(IFORM_INSTANCEAssembler assembler, IFORM_INSTANCERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_INSTANCE_TRANSLOGService : IEntityService<FORM_INSTANCE_TRANSLOGDto, FORM_INSTANCE_TRANSLOG>
	{
	}


	public partial class FORM_INSTANCE_TRANSLOGService : EntityService<FORM_INSTANCE_TRANSLOGDto, FORM_INSTANCE_TRANSLOG>, IFORM_INSTANCE_TRANSLOGService
	{
		public FORM_INSTANCE_TRANSLOGService(IFORM_INSTANCE_TRANSLOGAssembler assembler, IFORM_INSTANCE_TRANSLOGRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_INSTANCE_TARGETS_DELLOGService : IEntityService<FORM_INSTANCE_TARGETS_DELLOGDto, FORM_INSTANCE_TARGETS_DELLOG>
	{
	}


	public partial class FORM_INSTANCE_TARGETS_DELLOGService : EntityService<FORM_INSTANCE_TARGETS_DELLOGDto, FORM_INSTANCE_TARGETS_DELLOG>, IFORM_INSTANCE_TARGETS_DELLOGService
	{
		public FORM_INSTANCE_TARGETS_DELLOGService(IFORM_INSTANCE_TARGETS_DELLOGAssembler assembler, IFORM_INSTANCE_TARGETS_DELLOGRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_INSTANCE_TARGETS_BKService : IEntityService<FORM_INSTANCE_TARGETS_BKDto, FORM_INSTANCE_TARGETS_BK>
	{
	}


	public partial class FORM_INSTANCE_TARGETS_BKService : EntityService<FORM_INSTANCE_TARGETS_BKDto, FORM_INSTANCE_TARGETS_BK>, IFORM_INSTANCE_TARGETS_BKService
	{
		public FORM_INSTANCE_TARGETS_BKService(IFORM_INSTANCE_TARGETS_BKAssembler assembler, IFORM_INSTANCE_TARGETS_BKRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_INSTANCE_TARGETService : IEntityService<FORM_INSTANCE_TARGETDto, FORM_INSTANCE_TARGET>
	{
	}


	public partial class FORM_INSTANCE_TARGETService : EntityService<FORM_INSTANCE_TARGETDto, FORM_INSTANCE_TARGET>, IFORM_INSTANCE_TARGETService
	{
		public FORM_INSTANCE_TARGETService(IFORM_INSTANCE_TARGETAssembler assembler, IFORM_INSTANCE_TARGETRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_INSTANCE_RETURN_LOGService : IEntityService<FORM_INSTANCE_RETURN_LOGDto, FORM_INSTANCE_RETURN_LOG>
	{
	}


	public partial class FORM_INSTANCE_RETURN_LOGService : EntityService<FORM_INSTANCE_RETURN_LOGDto, FORM_INSTANCE_RETURN_LOG>, IFORM_INSTANCE_RETURN_LOGService
	{
		public FORM_INSTANCE_RETURN_LOGService(IFORM_INSTANCE_RETURN_LOGAssembler assembler, IFORM_INSTANCE_RETURN_LOGRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_INSTANCE_EXPRESSIONS_BKService : IEntityService<FORM_INSTANCE_EXPRESSIONS_BKDto, FORM_INSTANCE_EXPRESSIONS_BK>
	{
	}


	public partial class FORM_INSTANCE_EXPRESSIONS_BKService : EntityService<FORM_INSTANCE_EXPRESSIONS_BKDto, FORM_INSTANCE_EXPRESSIONS_BK>, IFORM_INSTANCE_EXPRESSIONS_BKService
	{
		public FORM_INSTANCE_EXPRESSIONS_BKService(IFORM_INSTANCE_EXPRESSIONS_BKAssembler assembler, IFORM_INSTANCE_EXPRESSIONS_BKRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_INSTANCE_EXPRESSIONService : IEntityService<FORM_INSTANCE_EXPRESSIONDto, FORM_INSTANCE_EXPRESSION>
	{
	}


	public partial class FORM_INSTANCE_EXPRESSIONService : EntityService<FORM_INSTANCE_EXPRESSIONDto, FORM_INSTANCE_EXPRESSION>, IFORM_INSTANCE_EXPRESSIONService
	{
		public FORM_INSTANCE_EXPRESSIONService(IFORM_INSTANCE_EXPRESSIONAssembler assembler, IFORM_INSTANCE_EXPRESSIONRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_INSTANCE_ELEMENTS_BKService : IEntityService<FORM_INSTANCE_ELEMENTS_BKDto, FORM_INSTANCE_ELEMENTS_BK>
	{
	}


	public partial class FORM_INSTANCE_ELEMENTS_BKService : EntityService<FORM_INSTANCE_ELEMENTS_BKDto, FORM_INSTANCE_ELEMENTS_BK>, IFORM_INSTANCE_ELEMENTS_BKService
	{
		public FORM_INSTANCE_ELEMENTS_BKService(IFORM_INSTANCE_ELEMENTS_BKAssembler assembler, IFORM_INSTANCE_ELEMENTS_BKRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_INSTANCE_ELEMENTService : IEntityService<FORM_INSTANCE_ELEMENTDto, FORM_INSTANCE_ELEMENT>
	{
	}


	public partial class FORM_INSTANCE_ELEMENTService : EntityService<FORM_INSTANCE_ELEMENTDto, FORM_INSTANCE_ELEMENT>, IFORM_INSTANCE_ELEMENTService
	{
		public FORM_INSTANCE_ELEMENTService(IFORM_INSTANCE_ELEMENTAssembler assembler, IFORM_INSTANCE_ELEMENTRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_INSTANCE_BLOCKService : IEntityService<FORM_INSTANCE_BLOCKDto, FORM_INSTANCE_BLOCK>
	{
	}


	public partial class FORM_INSTANCE_BLOCKService : EntityService<FORM_INSTANCE_BLOCKDto, FORM_INSTANCE_BLOCK>, IFORM_INSTANCE_BLOCKService
	{
		public FORM_INSTANCE_BLOCKService(IFORM_INSTANCE_BLOCKAssembler assembler, IFORM_INSTANCE_BLOCKRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFORM_INSTANCE_ATTACHMENTService : IEntityService<FORM_INSTANCE_ATTACHMENTDto, FORM_INSTANCE_ATTACHMENT>
	{
	}


	public partial class FORM_INSTANCE_ATTACHMENTService : EntityService<FORM_INSTANCE_ATTACHMENTDto, FORM_INSTANCE_ATTACHMENT>, IFORM_INSTANCE_ATTACHMENTService
	{
		public FORM_INSTANCE_ATTACHMENTService(IFORM_INSTANCE_ATTACHMENTAssembler assembler, IFORM_INSTANCE_ATTACHMENTRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IFIXMEMBERDATUMService : IEntityService<FIXMEMBERDATUMDto, FIXMEMBERDATUM>
	{
	}


	public partial class FIXMEMBERDATUMService : EntityService<FIXMEMBERDATUMDto, FIXMEMBERDATUM>, IFIXMEMBERDATUMService
	{
		public FIXMEMBERDATUMService(IFIXMEMBERDATUMAssembler assembler, IFIXMEMBERDATUMRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IELEARNINGITEMService : IEntityService<ELEARNINGITEMDto, ELEARNINGITEM>
	{
	}


	public partial class ELEARNINGITEMService : EntityService<ELEARNINGITEMDto, ELEARNINGITEM>, IELEARNINGITEMService
	{
		public ELEARNINGITEMService(IELEARNINGITEMAssembler assembler, IELEARNINGITEMRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IELEARNINGEMPITEMLOGService : IEntityService<ELEARNINGEMPITEMLOGDto, ELEARNINGEMPITEMLOG>
	{
	}


	public partial class ELEARNINGEMPITEMLOGService : EntityService<ELEARNINGEMPITEMLOGDto, ELEARNINGEMPITEMLOG>, IELEARNINGEMPITEMLOGService
	{
		public ELEARNINGEMPITEMLOGService(IELEARNINGEMPITEMLOGAssembler assembler, IELEARNINGEMPITEMLOGRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IELEARNINGEMPITEMService : IEntityService<ELEARNINGEMPITEMDto, ELEARNINGEMPITEM>
	{
	}


	public partial class ELEARNINGEMPITEMService : EntityService<ELEARNINGEMPITEMDto, ELEARNINGEMPITEM>, IELEARNINGEMPITEMService
	{
		public ELEARNINGEMPITEMService(IELEARNINGEMPITEMAssembler assembler, IELEARNINGEMPITEMRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IELEARNINGCLASSService : IEntityService<ELEARNINGCLASSDto, ELEARNINGCLASS>
	{
	}


	public partial class ELEARNINGCLASSService : EntityService<ELEARNINGCLASSDto, ELEARNINGCLASS>, IELEARNINGCLASSService
	{
		public ELEARNINGCLASSService(IELEARNINGCLASSAssembler assembler, IELEARNINGCLASSRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IELEARNINGBOOKINGService : IEntityService<ELEARNINGBOOKINGDto, ELEARNINGBOOKING>
	{
	}


	public partial class ELEARNINGBOOKINGService : EntityService<ELEARNINGBOOKINGDto, ELEARNINGBOOKING>, IELEARNINGBOOKINGService
	{
		public ELEARNINGBOOKINGService(IELEARNINGBOOKINGAssembler assembler, IELEARNINGBOOKINGRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUTERMFORMREQTEMPLATEDETService : IEntityService<EDUTERMFORMREQTEMPLATEDETDto, EDUTERMFORMREQTEMPLATEDET>
	{
	}


	public partial class EDUTERMFORMREQTEMPLATEDETService : EntityService<EDUTERMFORMREQTEMPLATEDETDto, EDUTERMFORMREQTEMPLATEDET>, IEDUTERMFORMREQTEMPLATEDETService
	{
		public EDUTERMFORMREQTEMPLATEDETService(IEDUTERMFORMREQTEMPLATEDETAssembler assembler, IEDUTERMFORMREQTEMPLATEDETRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUTERMFORMREQTEMPLATEService : IEntityService<EDUTERMFORMREQTEMPLATEDto, EDUTERMFORMREQTEMPLATE>
	{
	}


	public partial class EDUTERMFORMREQTEMPLATEService : EntityService<EDUTERMFORMREQTEMPLATEDto, EDUTERMFORMREQTEMPLATE>, IEDUTERMFORMREQTEMPLATEService
	{
		public EDUTERMFORMREQTEMPLATEService(IEDUTERMFORMREQTEMPLATEAssembler assembler, IEDUTERMFORMREQTEMPLATERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUTERMFORMREQService : IEntityService<EDUTERMFORMREQDto, EDUTERMFORMREQ>
	{
	}


	public partial class EDUTERMFORMREQService : EntityService<EDUTERMFORMREQDto, EDUTERMFORMREQ>, IEDUTERMFORMREQService
	{
		public EDUTERMFORMREQService(IEDUTERMFORMREQAssembler assembler, IEDUTERMFORMREQRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUTERMFORMINSTANCEService : IEntityService<EDUTERMFORMINSTANCEDto, EDUTERMFORMINSTANCE>
	{
	}


	public partial class EDUTERMFORMINSTANCEService : EntityService<EDUTERMFORMINSTANCEDto, EDUTERMFORMINSTANCE>, IEDUTERMFORMINSTANCEService
	{
		public EDUTERMFORMINSTANCEService(IEDUTERMFORMINSTANCEAssembler assembler, IEDUTERMFORMINSTANCERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUTERMService : IEntityService<EDUTERMDto, EDUTERM>
	{
	}


	public partial class EDUTERMService : EntityService<EDUTERMDto, EDUTERM>, IEDUTERMService
	{
		public EDUTERMService(IEDUTERMAssembler assembler, IEDUTERMRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUTEAMRUNDOWNService : IEntityService<EDUTEAMRUNDOWNDto, EDUTEAMRUNDOWN>
	{
	}


	public partial class EDUTEAMRUNDOWNService : EntityService<EDUTEAMRUNDOWNDto, EDUTEAMRUNDOWN>, IEDUTEAMRUNDOWNService
	{
		public EDUTEAMRUNDOWNService(IEDUTEAMRUNDOWNAssembler assembler, IEDUTEAMRUNDOWNRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUTEAMMEMBERRUNDOWN_TRANSLOGService : IEntityService<EDUTEAMMEMBERRUNDOWN_TRANSLOGDto, EDUTEAMMEMBERRUNDOWN_TRANSLOG>
	{
	}


	public partial class EDUTEAMMEMBERRUNDOWN_TRANSLOGService : EntityService<EDUTEAMMEMBERRUNDOWN_TRANSLOGDto, EDUTEAMMEMBERRUNDOWN_TRANSLOG>, IEDUTEAMMEMBERRUNDOWN_TRANSLOGService
	{
		public EDUTEAMMEMBERRUNDOWN_TRANSLOGService(IEDUTEAMMEMBERRUNDOWN_TRANSLOGAssembler assembler, IEDUTEAMMEMBERRUNDOWN_TRANSLOGRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUTEAMMEMBERRUNDOWNService : IEntityService<EDUTEAMMEMBERRUNDOWNDto, EDUTEAMMEMBERRUNDOWN>
	{
	}


	public partial class EDUTEAMMEMBERRUNDOWNService : EntityService<EDUTEAMMEMBERRUNDOWNDto, EDUTEAMMEMBERRUNDOWN>, IEDUTEAMMEMBERRUNDOWNService
	{
		public EDUTEAMMEMBERRUNDOWNService(IEDUTEAMMEMBERRUNDOWNAssembler assembler, IEDUTEAMMEMBERRUNDOWNRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUTEAMMEMBERService : IEntityService<EDUTEAMMEMBERDto, EDUTEAMMEMBER>
	{
	}


	public partial class EDUTEAMMEMBERService : EntityService<EDUTEAMMEMBERDto, EDUTEAMMEMBER>, IEDUTEAMMEMBERService
	{
		public EDUTEAMMEMBERService(IEDUTEAMMEMBERAssembler assembler, IEDUTEAMMEMBERRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUTEAMService : IEntityService<EDUTEAMDto, EDUTEAM>
	{
	}


	public partial class EDUTEAMService : EntityService<EDUTEAMDto, EDUTEAM>, IEDUTEAMService
	{
		public EDUTEAMService(IEDUTEAMAssembler assembler, IEDUTEAMRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUTEACHERTYPEService : IEntityService<EDUTEACHERTYPEDto, EDUTEACHERTYPE>
	{
	}


	public partial class EDUTEACHERTYPEService : EntityService<EDUTEACHERTYPEDto, EDUTEACHERTYPE>, IEDUTEACHERTYPEService
	{
		public EDUTEACHERTYPEService(IEDUTEACHERTYPEAssembler assembler, IEDUTEACHERTYPERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUSTOPACTSCHEDULEService : IEntityService<EDUSTOPACTSCHEDULEDto, EDUSTOPACTSCHEDULE>
	{
	}


	public partial class EDUSTOPACTSCHEDULEService : EntityService<EDUSTOPACTSCHEDULEDto, EDUSTOPACTSCHEDULE>, IEDUSTOPACTSCHEDULEService
	{
		public EDUSTOPACTSCHEDULEService(IEDUSTOPACTSCHEDULEAssembler assembler, IEDUSTOPACTSCHEDULERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUSTOPACTATTACHMENTService : IEntityService<EDUSTOPACTATTACHMENTDto, EDUSTOPACTATTACHMENT>
	{
	}


	public partial class EDUSTOPACTATTACHMENTService : EntityService<EDUSTOPACTATTACHMENTDto, EDUSTOPACTATTACHMENT>, IEDUSTOPACTATTACHMENTService
	{
		public EDUSTOPACTATTACHMENTService(IEDUSTOPACTATTACHMENTAssembler assembler, IEDUSTOPACTATTACHMENTRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUSTOPService : IEntityService<EDUSTOPDto, EDUSTOP>
	{
	}


	public partial class EDUSTOPService : EntityService<EDUSTOPDto, EDUSTOP>, IEDUSTOPService
	{
		public EDUSTOPService(IEDUSTOPAssembler assembler, IEDUSTOPRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUSETTINGService : IEntityService<EDUSETTINGDto, EDUSETTING>
	{
	}


	public partial class EDUSETTINGService : EntityService<EDUSETTINGDto, EDUSETTING>, IEDUSETTINGService
	{
		public EDUSETTINGService(IEDUSETTINGAssembler assembler, IEDUSETTINGRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUSENTENCEService : IEntityService<EDUSENTENCEDto, EDUSENTENCE>
	{
	}


	public partial class EDUSENTENCEService : EntityService<EDUSENTENCEDto, EDUSENTENCE>, IEDUSENTENCEService
	{
		public EDUSENTENCEService(IEDUSENTENCEAssembler assembler, IEDUSENTENCERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUSCOREService : IEntityService<EDUSCOREDto, EDUSCORE>
	{
	}


	public partial class EDUSCOREService : EntityService<EDUSCOREDto, EDUSCORE>, IEDUSCOREService
	{
		public EDUSCOREService(IEDUSCOREAssembler assembler, IEDUSCORERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUREFTEACHERService : IEntityService<EDUREFTEACHERDto, EDUREFTEACHER>
	{
	}


	public partial class EDUREFTEACHERService : EntityService<EDUREFTEACHERDto, EDUREFTEACHER>, IEDUREFTEACHERService
	{
		public EDUREFTEACHERService(IEDUREFTEACHERAssembler assembler, IEDUREFTEACHERRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUQUESTIONService : IEntityService<EDUQUESTIONDto, EDUQUESTION>
	{
	}


	public partial class EDUQUESTIONService : EntityService<EDUQUESTIONDto, EDUQUESTION>, IEDUQUESTIONService
	{
		public EDUQUESTIONService(IEDUQUESTIONAssembler assembler, IEDUQUESTIONRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUPASSPORTTEMPLATETARGETService : IEntityService<EDUPASSPORTTEMPLATETARGETDto, EDUPASSPORTTEMPLATETARGET>
	{
	}


	public partial class EDUPASSPORTTEMPLATETARGETService : EntityService<EDUPASSPORTTEMPLATETARGETDto, EDUPASSPORTTEMPLATETARGET>, IEDUPASSPORTTEMPLATETARGETService
	{
		public EDUPASSPORTTEMPLATETARGETService(IEDUPASSPORTTEMPLATETARGETAssembler assembler, IEDUPASSPORTTEMPLATETARGETRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUPASSPORTTEMPLATEITEMService : IEntityService<EDUPASSPORTTEMPLATEITEMDto, EDUPASSPORTTEMPLATEITEM>
	{
	}


	public partial class EDUPASSPORTTEMPLATEITEMService : EntityService<EDUPASSPORTTEMPLATEITEMDto, EDUPASSPORTTEMPLATEITEM>, IEDUPASSPORTTEMPLATEITEMService
	{
		public EDUPASSPORTTEMPLATEITEMService(IEDUPASSPORTTEMPLATEITEMAssembler assembler, IEDUPASSPORTTEMPLATEITEMRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUPASSPORTTEMPLATEService : IEntityService<EDUPASSPORTTEMPLATEDto, EDUPASSPORTTEMPLATE>
	{
	}


	public partial class EDUPASSPORTTEMPLATEService : EntityService<EDUPASSPORTTEMPLATEDto, EDUPASSPORTTEMPLATE>, IEDUPASSPORTTEMPLATEService
	{
		public EDUPASSPORTTEMPLATEService(IEDUPASSPORTTEMPLATEAssembler assembler, IEDUPASSPORTTEMPLATERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUPASSPORTPREFService : IEntityService<EDUPASSPORTPREFDto, EDUPASSPORTPREF>
	{
	}


	public partial class EDUPASSPORTPREFService : EntityService<EDUPASSPORTPREFDto, EDUPASSPORTPREF>, IEDUPASSPORTPREFService
	{
		public EDUPASSPORTPREFService(IEDUPASSPORTPREFAssembler assembler, IEDUPASSPORTPREFRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUPASSPORTITEMTARGETService : IEntityService<EDUPASSPORTITEMTARGETDto, EDUPASSPORTITEMTARGET>
	{
	}


	public partial class EDUPASSPORTITEMTARGETService : EntityService<EDUPASSPORTITEMTARGETDto, EDUPASSPORTITEMTARGET>, IEDUPASSPORTITEMTARGETService
	{
		public EDUPASSPORTITEMTARGETService(IEDUPASSPORTITEMTARGETAssembler assembler, IEDUPASSPORTITEMTARGETRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUPASSPORTITEMDETService : IEntityService<EDUPASSPORTITEMDETDto, EDUPASSPORTITEMDET>
	{
	}


	public partial class EDUPASSPORTITEMDETService : EntityService<EDUPASSPORTITEMDETDto, EDUPASSPORTITEMDET>, IEDUPASSPORTITEMDETService
	{
		public EDUPASSPORTITEMDETService(IEDUPASSPORTITEMDETAssembler assembler, IEDUPASSPORTITEMDETRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUPASSPORTITEMService : IEntityService<EDUPASSPORTITEMDto, EDUPASSPORTITEM>
	{
	}


	public partial class EDUPASSPORTITEMService : EntityService<EDUPASSPORTITEMDto, EDUPASSPORTITEM>, IEDUPASSPORTITEMService
	{
		public EDUPASSPORTITEMService(IEDUPASSPORTITEMAssembler assembler, IEDUPASSPORTITEMRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUPASSPORTINSTANCEService : IEntityService<EDUPASSPORTINSTANCEDto, EDUPASSPORTINSTANCE>
	{
	}


	public partial class EDUPASSPORTINSTANCEService : EntityService<EDUPASSPORTINSTANCEDto, EDUPASSPORTINSTANCE>, IEDUPASSPORTINSTANCEService
	{
		public EDUPASSPORTINSTANCEService(IEDUPASSPORTINSTANCEAssembler assembler, IEDUPASSPORTINSTANCERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUPASSPORTINSITEMREJECTHIService : IEntityService<EDUPASSPORTINSITEMREJECTHIDto, EDUPASSPORTINSITEMREJECTHI>
	{
	}


	public partial class EDUPASSPORTINSITEMREJECTHIService : EntityService<EDUPASSPORTINSITEMREJECTHIDto, EDUPASSPORTINSITEMREJECTHI>, IEDUPASSPORTINSITEMREJECTHIService
	{
		public EDUPASSPORTINSITEMREJECTHIService(IEDUPASSPORTINSITEMREJECTHIAssembler assembler, IEDUPASSPORTINSITEMREJECTHIRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUPASSPORTINSITEMREFService : IEntityService<EDUPASSPORTINSITEMREFDto, EDUPASSPORTINSITEMREF>
	{
	}


	public partial class EDUPASSPORTINSITEMREFService : EntityService<EDUPASSPORTINSITEMREFDto, EDUPASSPORTINSITEMREF>, IEDUPASSPORTINSITEMREFService
	{
		public EDUPASSPORTINSITEMREFService(IEDUPASSPORTINSITEMREFAssembler assembler, IEDUPASSPORTINSITEMREFRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUPASSPORTINSITEMDETService : IEntityService<EDUPASSPORTINSITEMDETDto, EDUPASSPORTINSITEMDET>
	{
	}


	public partial class EDUPASSPORTINSITEMDETService : EntityService<EDUPASSPORTINSITEMDETDto, EDUPASSPORTINSITEMDET>, IEDUPASSPORTINSITEMDETService
	{
		public EDUPASSPORTINSITEMDETService(IEDUPASSPORTINSITEMDETAssembler assembler, IEDUPASSPORTINSITEMDETRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUPASSPORTINSITEMService : IEntityService<EDUPASSPORTINSITEMDto, EDUPASSPORTINSITEM>
	{
	}


	public partial class EDUPASSPORTINSITEMService : EntityService<EDUPASSPORTINSITEMDto, EDUPASSPORTINSITEM>, IEDUPASSPORTINSITEMService
	{
		public EDUPASSPORTINSITEMService(IEDUPASSPORTINSITEMAssembler assembler, IEDUPASSPORTINSITEMRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUNOTETEMPLATEService : IEntityService<EDUNOTETEMPLATEDto, EDUNOTETEMPLATE>
	{
	}


	public partial class EDUNOTETEMPLATEService : EntityService<EDUNOTETEMPLATEDto, EDUNOTETEMPLATE>, IEDUNOTETEMPLATEService
	{
		public EDUNOTETEMPLATEService(IEDUNOTETEMPLATEAssembler assembler, IEDUNOTETEMPLATERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUNOTELISTService : IEntityService<EDUNOTELISTDto, EDUNOTELIST>
	{
	}


	public partial class EDUNOTELISTService : EntityService<EDUNOTELISTDto, EDUNOTELIST>, IEDUNOTELISTService
	{
		public EDUNOTELISTService(IEDUNOTELISTAssembler assembler, IEDUNOTELISTRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUNOTEITEMService : IEntityService<EDUNOTEITEMDto, EDUNOTEITEM>
	{
	}


	public partial class EDUNOTEITEMService : EntityService<EDUNOTEITEMDto, EDUNOTEITEM>, IEDUNOTEITEMService
	{
		public EDUNOTEITEMService(IEDUNOTEITEMAssembler assembler, IEDUNOTEITEMRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUNOTEService : IEntityService<EDUNOTEDto, EDUNOTE>
	{
	}


	public partial class EDUNOTEService : EntityService<EDUNOTEDto, EDUNOTE>, IEDUNOTEService
	{
		public EDUNOTEService(IEDUNOTEAssembler assembler, IEDUNOTERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUNOTALERTSETTINGService : IEntityService<EDUNOTALERTSETTINGDto, EDUNOTALERTSETTING>
	{
	}


	public partial class EDUNOTALERTSETTINGService : EntityService<EDUNOTALERTSETTINGDto, EDUNOTALERTSETTING>, IEDUNOTALERTSETTINGService
	{
		public EDUNOTALERTSETTINGService(IEDUNOTALERTSETTINGAssembler assembler, IEDUNOTALERTSETTINGRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUMENUService : IEntityService<EDUMENUDto, EDUMENU>
	{
	}


	public partial class EDUMENUService : EntityService<EDUMENUDto, EDUMENU>, IEDUMENUService
	{
		public EDUMENUService(IEDUMENUAssembler assembler, IEDUMENURepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUFORMTEMPLATETARGETService : IEntityService<EDUFORMTEMPLATETARGETDto, EDUFORMTEMPLATETARGET>
	{
	}


	public partial class EDUFORMTEMPLATETARGETService : EntityService<EDUFORMTEMPLATETARGETDto, EDUFORMTEMPLATETARGET>, IEDUFORMTEMPLATETARGETService
	{
		public EDUFORMTEMPLATETARGETService(IEDUFORMTEMPLATETARGETAssembler assembler, IEDUFORMTEMPLATETARGETRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUFORMTEMPLATELISTService : IEntityService<EDUFORMTEMPLATELISTDto, EDUFORMTEMPLATELIST>
	{
	}


	public partial class EDUFORMTEMPLATELISTService : EntityService<EDUFORMTEMPLATELISTDto, EDUFORMTEMPLATELIST>, IEDUFORMTEMPLATELISTService
	{
		public EDUFORMTEMPLATELISTService(IEDUFORMTEMPLATELISTAssembler assembler, IEDUFORMTEMPLATELISTRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUFORMSTASTICPERMISSIONService : IEntityService<EDUFORMSTASTICPERMISSIONDto, EDUFORMSTASTICPERMISSION>
	{
	}


	public partial class EDUFORMSTASTICPERMISSIONService : EntityService<EDUFORMSTASTICPERMISSIONDto, EDUFORMSTASTICPERMISSION>, IEDUFORMSTASTICPERMISSIONService
	{
		public EDUFORMSTASTICPERMISSIONService(IEDUFORMSTASTICPERMISSIONAssembler assembler, IEDUFORMSTASTICPERMISSIONRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUACTVIEWTARGETService : IEntityService<EDUACTVIEWTARGETDto, EDUACTVIEWTARGET>
	{
	}


	public partial class EDUACTVIEWTARGETService : EntityService<EDUACTVIEWTARGETDto, EDUACTVIEWTARGET>, IEDUACTVIEWTARGETService
	{
		public EDUACTVIEWTARGETService(IEDUACTVIEWTARGETAssembler assembler, IEDUACTVIEWTARGETRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUACTTYPEROLEREFService : IEntityService<EDUACTTYPEROLEREFDto, EDUACTTYPEROLEREF>
	{
	}


	public partial class EDUACTTYPEROLEREFService : EntityService<EDUACTTYPEROLEREFDto, EDUACTTYPEROLEREF>, IEDUACTTYPEROLEREFService
	{
		public EDUACTTYPEROLEREFService(IEDUACTTYPEROLEREFAssembler assembler, IEDUACTTYPEROLEREFRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUACTTYPEREFService : IEntityService<EDUACTTYPEREFDto, EDUACTTYPEREF>
	{
	}


	public partial class EDUACTTYPEREFService : EntityService<EDUACTTYPEREFDto, EDUACTTYPEREF>, IEDUACTTYPEREFService
	{
		public EDUACTTYPEREFService(IEDUACTTYPEREFAssembler assembler, IEDUACTTYPEREFRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUACTTYPEGROUPINGService : IEntityService<EDUACTTYPEGROUPINGDto, EDUACTTYPEGROUPING>
	{
	}


	public partial class EDUACTTYPEGROUPINGService : EntityService<EDUACTTYPEGROUPINGDto, EDUACTTYPEGROUPING>, IEDUACTTYPEGROUPINGService
	{
		public EDUACTTYPEGROUPINGService(IEDUACTTYPEGROUPINGAssembler assembler, IEDUACTTYPEGROUPINGRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUACTTYPE_BKService : IEntityService<EDUACTTYPE_BKDto, EDUACTTYPE_BK>
	{
	}


	public partial class EDUACTTYPE_BKService : EntityService<EDUACTTYPE_BKDto, EDUACTTYPE_BK>, IEDUACTTYPE_BKService
	{
		public EDUACTTYPE_BKService(IEDUACTTYPE_BKAssembler assembler, IEDUACTTYPE_BKRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUACTTYPEService : IEntityService<EDUACTTYPEDto, EDUACTTYPE>
	{
	}


	public partial class EDUACTTYPEService : EntityService<EDUACTTYPEDto, EDUACTTYPE>, IEDUACTTYPEService
	{
		public EDUACTTYPEService(IEDUACTTYPEAssembler assembler, IEDUACTTYPERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUACTTOPICService : IEntityService<EDUACTTOPICDto, EDUACTTOPIC>
	{
	}


	public partial class EDUACTTOPICService : EntityService<EDUACTTOPICDto, EDUACTTOPIC>, IEDUACTTOPICService
	{
		public EDUACTTOPICService(IEDUACTTOPICAssembler assembler, IEDUACTTOPICRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUACTTARGETService : IEntityService<EDUACTTARGETDto, EDUACTTARGET>
	{
	}


	public partial class EDUACTTARGETService : EntityService<EDUACTTARGETDto, EDUACTTARGET>, IEDUACTTARGETService
	{
		public EDUACTTARGETService(IEDUACTTARGETAssembler assembler, IEDUACTTARGETRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IEDUACTBOOKINGService : IEntityService<EDUACTBOOKINGDto, EDUACTBOOKING>
	{
	}


	public partial class EDUACTBOOKINGService : EntityService<EDUACTBOOKINGDto, EDUACTBOOKING>, IEDUACTBOOKINGService
	{
		public EDUACTBOOKINGService(IEDUACTBOOKINGAssembler assembler, IEDUACTBOOKINGRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IDOCTORPOINTTYPEService : IEntityService<DOCTORPOINTTYPEDto, DOCTORPOINTTYPE>
	{
	}


	public partial class DOCTORPOINTTYPEService : EntityService<DOCTORPOINTTYPEDto, DOCTORPOINTTYPE>, IDOCTORPOINTTYPEService
	{
		public DOCTORPOINTTYPEService(IDOCTORPOINTTYPEAssembler assembler, IDOCTORPOINTTYPERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IDOCTORPOINTCALTYPEService : IEntityService<DOCTORPOINTCALTYPEDto, DOCTORPOINTCALTYPE>
	{
	}


	public partial class DOCTORPOINTCALTYPEService : EntityService<DOCTORPOINTCALTYPEDto, DOCTORPOINTCALTYPE>, IDOCTORPOINTCALTYPEService
	{
		public DOCTORPOINTCALTYPEService(IDOCTORPOINTCALTYPEAssembler assembler, IDOCTORPOINTCALTYPERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IDOCTORPOINTService : IEntityService<DOCTORPOINTDto, DOCTORPOINT>
	{
	}


	public partial class DOCTORPOINTService : EntityService<DOCTORPOINTDto, DOCTORPOINT>, IDOCTORPOINTService
	{
		public DOCTORPOINTService(IDOCTORPOINTAssembler assembler, IDOCTORPOINTRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IDEPSECTEMPService : IEntityService<DEPSECTEMPDto, DEPSECTEMP>
	{
	}


	public partial class DEPSECTEMPService : EntityService<DEPSECTEMPDto, DEPSECTEMP>, IDEPSECTEMPService
	{
		public DEPSECTEMPService(IDEPSECTEMPAssembler assembler, IDEPSECTEMPRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IDEPSECDATUMService : IEntityService<DEPSECDATUMDto, DEPSECDATUM>
	{
	}


	public partial class DEPSECDATUMService : EntityService<DEPSECDATUMDto, DEPSECDATUM>, IDEPSECDATUMService
	{
		public DEPSECDATUMService(IDEPSECDATUMAssembler assembler, IDEPSECDATUMRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface ICLERKIPDNOTEDATUMService : IEntityService<CLERKIPDNOTEDATUMDto, CLERKIPDNOTEDATUM>
	{
	}


	public partial class CLERKIPDNOTEDATUMService : EntityService<CLERKIPDNOTEDATUMDto, CLERKIPDNOTEDATUM>, ICLERKIPDNOTEDATUMService
	{
		public CLERKIPDNOTEDATUMService(ICLERKIPDNOTEDATUMAssembler assembler, ICLERKIPDNOTEDATUMRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface ICICBOOKService : IEntityService<CICBOOKDto, CICBOOK>
	{
	}


	public partial class CICBOOKService : EntityService<CICBOOKDto, CICBOOK>, ICICBOOKService
	{
		public CICBOOKService(ICICBOOKAssembler assembler, ICICBOOKRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IAUTOEDUFORMTEMPLATETARGETService : IEntityService<AUTOEDUFORMTEMPLATETARGETDto, AUTOEDUFORMTEMPLATETARGET>
	{
	}


	public partial class AUTOEDUFORMTEMPLATETARGETService : EntityService<AUTOEDUFORMTEMPLATETARGETDto, AUTOEDUFORMTEMPLATETARGET>, IAUTOEDUFORMTEMPLATETARGETService
	{
		public AUTOEDUFORMTEMPLATETARGETService(IAUTOEDUFORMTEMPLATETARGETAssembler assembler, IAUTOEDUFORMTEMPLATETARGETRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IAUTOEDUFORMTEMPLATESIGNERService : IEntityService<AUTOEDUFORMTEMPLATESIGNERDto, AUTOEDUFORMTEMPLATESIGNER>
	{
	}


	public partial class AUTOEDUFORMTEMPLATESIGNERService : EntityService<AUTOEDUFORMTEMPLATESIGNERDto, AUTOEDUFORMTEMPLATESIGNER>, IAUTOEDUFORMTEMPLATESIGNERService
	{
		public AUTOEDUFORMTEMPLATESIGNERService(IAUTOEDUFORMTEMPLATESIGNERAssembler assembler, IAUTOEDUFORMTEMPLATESIGNERRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IAUTOEDUFORMTEMPLATELISTService : IEntityService<AUTOEDUFORMTEMPLATELISTDto, AUTOEDUFORMTEMPLATELIST>
	{
	}


	public partial class AUTOEDUFORMTEMPLATELISTService : EntityService<AUTOEDUFORMTEMPLATELISTDto, AUTOEDUFORMTEMPLATELIST>, IAUTOEDUFORMTEMPLATELISTService
	{
		public AUTOEDUFORMTEMPLATELISTService(IAUTOEDUFORMTEMPLATELISTAssembler assembler, IAUTOEDUFORMTEMPLATELISTRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IAUTOEDUFORMTEMPLATEEXCEPTService : IEntityService<AUTOEDUFORMTEMPLATEEXCEPTDto, AUTOEDUFORMTEMPLATEEXCEPT>
	{
	}


	public partial class AUTOEDUFORMTEMPLATEEXCEPTService : EntityService<AUTOEDUFORMTEMPLATEEXCEPTDto, AUTOEDUFORMTEMPLATEEXCEPT>, IAUTOEDUFORMTEMPLATEEXCEPTService
	{
		public AUTOEDUFORMTEMPLATEEXCEPTService(IAUTOEDUFORMTEMPLATEEXCEPTAssembler assembler, IAUTOEDUFORMTEMPLATEEXCEPTRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IAUTHROLEService : IEntityService<AUTHROLEDto, AUTHROLE>
	{
	}


	public partial class AUTHROLEService : EntityService<AUTHROLEDto, AUTHROLE>, IAUTHROLEService
	{
		public AUTHROLEService(IAUTHROLEAssembler assembler, IAUTHROLERepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IAUTHMENUService : IEntityService<AUTHMENUDto, AUTHMENU>
	{
	}


	public partial class AUTHMENUService : EntityService<AUTHMENUDto, AUTHMENU>, IAUTHMENUService
	{
		public AUTHMENUService(IAUTHMENUAssembler assembler, IAUTHMENURepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IACTTYPETREE_TEMPService : IEntityService<ACTTYPETREE_TEMPDto, ACTTYPETREE_TEMP>
	{
	}


	public partial class ACTTYPETREE_TEMPService : EntityService<ACTTYPETREE_TEMPDto, ACTTYPETREE_TEMP>, IACTTYPETREE_TEMPService
	{
		public ACTTYPETREE_TEMPService(IACTTYPETREE_TEMPAssembler assembler, IACTTYPETREE_TEMPRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IACCOUNTService : IEntityService<ACCOUNTDto, ACCOUNT>
	{
	}


	public partial class ACCOUNTService : EntityService<ACCOUNTDto, ACCOUNT>, IACCOUNTService
	{
		public ACCOUNTService(IACCOUNTAssembler assembler, IACCOUNTRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IACCOUNTROLEIMPORTService : IEntityService<ACCOUNTROLEIMPORTDto, ACCOUNTROLEIMPORT>
	{
	}


	public partial class ACCOUNTROLEIMPORTService : EntityService<ACCOUNTROLEIMPORTDto, ACCOUNTROLEIMPORT>, IACCOUNTROLEIMPORTService
	{
		public ACCOUNTROLEIMPORTService(IACCOUNTROLEIMPORTAssembler assembler, IACCOUNTROLEIMPORTRepository repository)
			: base(assembler, repository)
		{
		}
	}


	public partial interface IACCOUNTROLEService : IEntityService<ACCOUNTROLEDto, ACCOUNTROLE>
	{
	}


	public partial class ACCOUNTROLEService : EntityService<ACCOUNTROLEDto, ACCOUNTROLE>, IACCOUNTROLEService
	{
		public ACCOUNTROLEService(IACCOUNTROLEAssembler assembler, IACCOUNTROLERepository repository)
			: base(assembler, repository)
		{
		}
	}


}
#pragma warning restore 1591

