#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class AUTHMENU
	{
		private int _mENUID;
		public virtual int MENUID
		{
			get
			{
				return this._mENUID;
			}
			set
			{
				this._mENUID = value;
			}
		}
		
		private string _aUTHID;
		public virtual string AUTHID
		{
			get
			{
				return this._aUTHID;
			}
			set
			{
				this._aUTHID = value;
			}
		}
		
		private string _aUTHTYPE;
		public virtual string AUTHTYPE
		{
			get
			{
				return this._aUTHTYPE;
			}
			set
			{
				this._aUTHTYPE = value;
			}
		}
		
		private DateTime? _eNABLETIME;
		public virtual DateTime? ENABLETIME
		{
			get
			{
				return this._eNABLETIME;
			}
			set
			{
				this._eNABLETIME = value;
			}
		}
		
	}
}
#pragma warning restore 1591
