#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class AUTOEDUFORMTEMPLATETARGET
	{
		private string _aUTOFTTARGETID;
		public virtual string AUTOFTTARGETID
		{
			get
			{
				return this._aUTOFTTARGETID;
			}
			set
			{
				this._aUTOFTTARGETID = value;
			}
		}
		
		private string _aUTOFTLISTID;
		public virtual string AUTOFTLISTID
		{
			get
			{
				return this._aUTOFTLISTID;
			}
			set
			{
				this._aUTOFTLISTID = value;
			}
		}
		
		private string _rOLETYPE;
		public virtual string ROLETYPE
		{
			get
			{
				return this._rOLETYPE;
			}
			set
			{
				this._rOLETYPE = value;
			}
		}
		
		private int? _eXPIREDAYS;
		public virtual int? EXPIREDAYS
		{
			get
			{
				return this._eXPIREDAYS;
			}
			set
			{
				this._eXPIREDAYS = value;
			}
		}
		
		private int _sUBTEMPLATE_ID;
		public virtual int SUBTEMPLATE_ID
		{
			get
			{
				return this._sUBTEMPLATE_ID;
			}
			set
			{
				this._sUBTEMPLATE_ID = value;
			}
		}
		
		private string _uSERDEFINETARGETID;
		public virtual string USERDEFINETARGETID
		{
			get
			{
				return this._uSERDEFINETARGETID;
			}
			set
			{
				this._uSERDEFINETARGETID = value;
			}
		}
		
		private string _tEACHERTYPE;
		public virtual string TEACHERTYPE
		{
			get
			{
				return this._tEACHERTYPE;
			}
			set
			{
				this._tEACHERTYPE = value;
			}
		}
		
		private string _eXPIREDAYSTYPE;
		public virtual string EXPIREDAYSTYPE
		{
			get
			{
				return this._eXPIREDAYSTYPE;
			}
			set
			{
				this._eXPIREDAYSTYPE = value;
			}
		}
		
	}
}
#pragma warning restore 1591
