#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class AUTOEDUFORMTEMPLATELIST
	{
		private string _aUTOFTLISTID;
		public virtual string AUTOFTLISTID
		{
			get
			{
				return this._aUTOFTLISTID;
			}
			set
			{
				this._aUTOFTLISTID = value;
			}
		}
		
		private string _jOBCODE;
		public virtual string JOBCODE
		{
			get
			{
				return this._jOBCODE;
			}
			set
			{
				this._jOBCODE = value;
			}
		}
		
		private int _tEMPLATE_ID;
		public virtual int TEMPLATE_ID
		{
			get
			{
				return this._tEMPLATE_ID;
			}
			set
			{
				this._tEMPLATE_ID = value;
			}
		}
		
		private string _sETTINGNAME;
		public virtual string SETTINGNAME
		{
			get
			{
				return this._sETTINGNAME;
			}
			set
			{
				this._sETTINGNAME = value;
			}
		}
		
		private string _dES;
		public virtual string DES
		{
			get
			{
				return this._dES;
			}
			set
			{
				this._dES = value;
			}
		}
		
		private bool? _eACHSTUDENT;
		public virtual bool? EACHSTUDENT
		{
			get
			{
				return this._eACHSTUDENT;
			}
			set
			{
				this._eACHSTUDENT = value;
			}
		}
		
		private string _dATESHIFTTYPE;
		public virtual string DATESHIFTTYPE
		{
			get
			{
				return this._dATESHIFTTYPE;
			}
			set
			{
				this._dATESHIFTTYPE = value;
			}
		}
		
		private int? _dATESHIFT;
		public virtual int? DATESHIFT
		{
			get
			{
				return this._dATESHIFT;
			}
			set
			{
				this._dATESHIFT = value;
			}
		}
		
		private bool? _mULTITARGET;
		public virtual bool? MULTITARGET
		{
			get
			{
				return this._mULTITARGET;
			}
			set
			{
				this._mULTITARGET = value;
			}
		}
		
		private string _tEACHERTYPE;
		public virtual string TEACHERTYPE
		{
			get
			{
				return this._tEACHERTYPE;
			}
			set
			{
				this._tEACHERTYPE = value;
			}
		}
		
		private int? _sENDFLOOR;
		public virtual int? SENDFLOOR
		{
			get
			{
				return this._sENDFLOOR;
			}
			set
			{
				this._sENDFLOOR = value;
			}
		}
		
		private string _cREATER;
		public virtual string CREATER
		{
			get
			{
				return this._cREATER;
			}
			set
			{
				this._cREATER = value;
			}
		}
		
		private string _sENDORDERSETTING;
		public virtual string SENDORDERSETTING
		{
			get
			{
				return this._sENDORDERSETTING;
			}
			set
			{
				this._sENDORDERSETTING = value;
			}
		}
		
		private string _eDUYEAR;
		public virtual string EDUYEAR
		{
			get
			{
				return this._eDUYEAR;
			}
			set
			{
				this._eDUYEAR = value;
			}
		}
		
		private DateTime? _sDATE;
		public virtual DateTime? SDATE
		{
			get
			{
				return this._sDATE;
			}
			set
			{
				this._sDATE = value;
			}
		}
		
		private DateTime? _eDATE;
		public virtual DateTime? EDATE
		{
			get
			{
				return this._eDATE;
			}
			set
			{
				this._eDATE = value;
			}
		}
		
	}
}
#pragma warning restore 1591
