#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class CLERKIPDNOTEDATUM
	{
		private string _eMPCODE;
		public virtual string EMPCODE
		{
			get
			{
				return this._eMPCODE;
			}
			set
			{
				this._eMPCODE = value;
			}
		}
		
		private string _dEPTCODE;
		public virtual string DEPTCODE
		{
			get
			{
				return this._dEPTCODE;
			}
			set
			{
				this._dEPTCODE = value;
			}
		}
		
		private string _dEPTNAME;
		public virtual string DEPTNAME
		{
			get
			{
				return this._dEPTNAME;
			}
			set
			{
				this._dEPTNAME = value;
			}
		}
		
		private DateTime _tHEDATE;
		public virtual DateTime THEDATE
		{
			get
			{
				return this._tHEDATE;
			}
			set
			{
				this._tHEDATE = value;
			}
		}
		
		private int? _nOTECOUNT;
		public virtual int? NOTECOUNT
		{
			get
			{
				return this._nOTECOUNT;
			}
			set
			{
				this._nOTECOUNT = value;
			}
		}
		
	}
}
#pragma warning restore 1591
