#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMUH.iKASAWebApi.DomainModel.Entities;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class DOCTORPOINTTYPE
	{
		private string _pTYPECODE;
		public virtual string PTYPECODE
		{
			get
			{
				return this._pTYPECODE;
			}
			set
			{
				this._pTYPECODE = value;
			}
		}
		
		private string _pTYPENAME;
		public virtual string PTYPENAME
		{
			get
			{
				return this._pTYPENAME;
			}
			set
			{
				this._pTYPENAME = value;
			}
		}
		
		private string _cTYPECODE;
		public virtual string CTYPECODE
		{
			get
			{
				return this._cTYPECODE;
			}
			set
			{
				this._cTYPECODE = value;
			}
		}
		
		private string _tRAININGTYPECODE;
		public virtual string TRAININGTYPECODE
		{
			get
			{
				return this._tRAININGTYPECODE;
			}
			set
			{
				this._tRAININGTYPECODE = value;
			}
		}
		
		private decimal? _eACHCOUNT;
		public virtual decimal? EACHCOUNT
		{
			get
			{
				return this._eACHCOUNT;
			}
			set
			{
				this._eACHCOUNT = value;
			}
		}
		
		private string _mEMO;
		public virtual string MEMO
		{
			get
			{
				return this._mEMO;
			}
			set
			{
				this._mEMO = value;
			}
		}
		
		private DOCTORPOINTCALTYPE _dOCTORPOINTCALTYPE;
		public virtual DOCTORPOINTCALTYPE DOCTORPOINTCALTYPE
		{
			get
			{
				return this._dOCTORPOINTCALTYPE;
			}
			set
			{
				this._dOCTORPOINTCALTYPE = value;
			}
		}
		
		private IList<DOCTORPOINT> _dOCTORPOINTs = new List<DOCTORPOINT>();
		public virtual IList<DOCTORPOINT> DOCTORPOINTs
		{
			get
			{
				return this._dOCTORPOINTs;
			}
		}
		
	}
}
#pragma warning restore 1591
