#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMUH.iKASAWebApi.DomainModel.Entities;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class DOCTORPOINTCALTYPE
	{
		private string _cTYPECODE;
		public virtual string CTYPECODE
		{
			get
			{
				return this._cTYPECODE;
			}
			set
			{
				this._cTYPECODE = value;
			}
		}
		
		private string _cTYPENAME;
		public virtual string CTYPENAME
		{
			get
			{
				return this._cTYPENAME;
			}
			set
			{
				this._cTYPENAME = value;
			}
		}
		
		private string _cREATER;
		public virtual string CREATER
		{
			get
			{
				return this._cREATER;
			}
			set
			{
				this._cREATER = value;
			}
		}
		
		private DateTime _cREATEDATE;
		public virtual DateTime CREATEDATE
		{
			get
			{
				return this._cREATEDATE;
			}
			set
			{
				this._cREATEDATE = value;
			}
		}
		
		private IList<DOCTORPOINTTYPE> _dOCTORPOINTTYPEs = new List<DOCTORPOINTTYPE>();
		public virtual IList<DOCTORPOINTTYPE> DOCTORPOINTTYPEs
		{
			get
			{
				return this._dOCTORPOINTTYPEs;
			}
		}
		
	}
}
#pragma warning restore 1591
