#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class EDUACTBOOKING
	{
		private string _eDUSTOPACTSCHEDULEID;
		public virtual string EDUSTOPACTSCHEDULEID
		{
			get
			{
				return this._eDUSTOPACTSCHEDULEID;
			}
			set
			{
				this._eDUSTOPACTSCHEDULEID = value;
			}
		}
		
		private string _eMPCODE;
		public virtual string EMPCODE
		{
			get
			{
				return this._eMPCODE;
			}
			set
			{
				this._eMPCODE = value;
			}
		}
		
		private int _bOOKINGID;
		public virtual int BOOKINGID
		{
			get
			{
				return this._bOOKINGID;
			}
			set
			{
				this._bOOKINGID = value;
			}
		}
		
		private DateTime _bOOKTIME;
		public virtual DateTime BOOKTIME
		{
			get
			{
				return this._bOOKTIME;
			}
			set
			{
				this._bOOKTIME = value;
			}
		}
		
	}
}
#pragma warning restore 1591
