#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMUH.iKASAWebApi.DomainModel.Entities;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class EDUACTVIEWTARGET
	{
		private string _eDUSTOPACTSCHEDULEID;
		public virtual string EDUSTOPACTSCHEDULEID
		{
			get
			{
				return this._eDUSTOPACTSCHEDULEID;
			}
			set
			{
				this._eDUSTOPACTSCHEDULEID = value;
			}
		}
		
		private string _tARGETTYPE;
		public virtual string TARGETTYPE
		{
			get
			{
				return this._tARGETTYPE;
			}
			set
			{
				this._tARGETTYPE = value;
			}
		}
		
		private string _tARGETID;
		public virtual string TARGETID
		{
			get
			{
				return this._tARGETID;
			}
			set
			{
				this._tARGETID = value;
			}
		}
		
		private string _rOLETYPE;
		public virtual string ROLETYPE
		{
			get
			{
				return this._rOLETYPE;
			}
			set
			{
				this._rOLETYPE = value;
			}
		}
		
		private DateTime? _tIMEFROM;
		public virtual DateTime? TIMEFROM
		{
			get
			{
				return this._tIMEFROM;
			}
			set
			{
				this._tIMEFROM = value;
			}
		}
		
		private DateTime? _tIMETO;
		public virtual DateTime? TIMETO
		{
			get
			{
				return this._tIMETO;
			}
			set
			{
				this._tIMETO = value;
			}
		}
		
		private string _tARGETJOB;
		public virtual string TARGETJOB
		{
			get
			{
				return this._tARGETJOB;
			}
			set
			{
				this._tARGETJOB = value;
			}
		}
		
		private EDUSTOPACTSCHEDULE _eDUSTOPACTSCHEDULE;
		public virtual EDUSTOPACTSCHEDULE EDUSTOPACTSCHEDULE
		{
			get
			{
				return this._eDUSTOPACTSCHEDULE;
			}
			set
			{
				this._eDUSTOPACTSCHEDULE = value;
			}
		}
		
	}
}
#pragma warning restore 1591
