#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class EDUACTTOPIC
	{
		private string _eDUACTTOPICID;
		public virtual string EDUACTTOPICID
		{
			get
			{
				return this._eDUACTTOPICID;
			}
			set
			{
				this._eDUACTTOPICID = value;
			}
		}
		
		private string _eDUACTTOPICCODE;
		public virtual string EDUACTTOPICCODE
		{
			get
			{
				return this._eDUACTTOPICCODE;
			}
			set
			{
				this._eDUACTTOPICCODE = value;
			}
		}
		
		private string _eDUACTTOPICNAME;
		public virtual string EDUACTTOPICNAME
		{
			get
			{
				return this._eDUACTTOPICNAME;
			}
			set
			{
				this._eDUACTTOPICNAME = value;
			}
		}
		
	}
}
#pragma warning restore 1591
