#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class EDUFORMTEMPLATELIST
	{
		private string _fTLISTID;
		public virtual string FTLISTID
		{
			get
			{
				return this._fTLISTID;
			}
			set
			{
				this._fTLISTID = value;
			}
		}
		
		private int _tEMPLATE_ID;
		public virtual int TEMPLATE_ID
		{
			get
			{
				return this._tEMPLATE_ID;
			}
			set
			{
				this._tEMPLATE_ID = value;
			}
		}
		
		private string _cREATESQL;
		public virtual string CREATESQL
		{
			get
			{
				return this._cREATESQL;
			}
			set
			{
				this._cREATESQL = value;
			}
		}
		
		private string _dES;
		public virtual string DES
		{
			get
			{
				return this._dES;
			}
			set
			{
				this._dES = value;
			}
		}
		
		private string _nAME;
		public virtual string NAME
		{
			get
			{
				return this._nAME;
			}
			set
			{
				this._nAME = value;
			}
		}
		
		private DateTime _eXECUTEDATE;
		public virtual DateTime EXECUTEDATE
		{
			get
			{
				return this._eXECUTEDATE;
			}
			set
			{
				this._eXECUTEDATE = value;
			}
		}
		
		private string _tEMPOTYPE;
		public virtual string TEMPOTYPE
		{
			get
			{
				return this._tEMPOTYPE;
			}
			set
			{
				this._tEMPOTYPE = value;
			}
		}
		
		private string _tEMPOSETTINGS;
		public virtual string TEMPOSETTINGS
		{
			get
			{
				return this._tEMPOSETTINGS;
			}
			set
			{
				this._tEMPOSETTINGS = value;
			}
		}
		
		private string _eDUTERMID;
		public virtual string EDUTERMID
		{
			get
			{
				return this._eDUTERMID;
			}
			set
			{
				this._eDUTERMID = value;
			}
		}
		
		private bool? _eACHSTUDENT;
		public virtual bool? EACHSTUDENT
		{
			get
			{
				return this._eACHSTUDENT;
			}
			set
			{
				this._eACHSTUDENT = value;
			}
		}
		
		private string _aUTOFTLISTID;
		public virtual string AUTOFTLISTID
		{
			get
			{
				return this._aUTOFTLISTID;
			}
			set
			{
				this._aUTOFTLISTID = value;
			}
		}
		
		private System.Nullable<System.Char> _sTATUS;
		public virtual System.Nullable<System.Char> STATUS
		{
			get
			{
				return this._sTATUS;
			}
			set
			{
				this._sTATUS = value;
			}
		}
		
		private string _cREATER;
		public virtual string CREATER
		{
			get
			{
				return this._cREATER;
			}
			set
			{
				this._cREATER = value;
			}
		}
		
		private string _sENDORDERSETTING;
		public virtual string SENDORDERSETTING
		{
			get
			{
				return this._sENDORDERSETTING;
			}
			set
			{
				this._sENDORDERSETTING = value;
			}
		}
		
		private string _eDUYEAR;
		public virtual string EDUYEAR
		{
			get
			{
				return this._eDUYEAR;
			}
			set
			{
				this._eDUYEAR = value;
			}
		}
		
		private string _sENDMONTH;
		public virtual string SENDMONTH
		{
			get
			{
				return this._sENDMONTH;
			}
			set
			{
				this._sENDMONTH = value;
			}
		}
		
		private string _uDSTUDENT;
		public virtual string UDSTUDENT
		{
			get
			{
				return this._uDSTUDENT;
			}
			set
			{
				this._uDSTUDENT = value;
			}
		}
		
	}
}
#pragma warning restore 1591
