#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class EDUNOTETEMPLATE
	{
		private string _nOTETEMPLATEID;
		public virtual string NOTETEMPLATEID
		{
			get
			{
				return this._nOTETEMPLATEID;
			}
			set
			{
				this._nOTETEMPLATEID = value;
			}
		}
		
		private string _nOTECODE;
		public virtual string NOTECODE
		{
			get
			{
				return this._nOTECODE;
			}
			set
			{
				this._nOTECODE = value;
			}
		}
		
		private string _vERSIONCODE;
		public virtual string VERSIONCODE
		{
			get
			{
				return this._vERSIONCODE;
			}
			set
			{
				this._vERSIONCODE = value;
			}
		}
		
		private string _hIERARCODE;
		public virtual string HIERARCODE
		{
			get
			{
				return this._hIERARCODE;
			}
			set
			{
				this._hIERARCODE = value;
			}
		}
		
		private string _dES;
		public virtual string DES
		{
			get
			{
				return this._dES;
			}
			set
			{
				this._dES = value;
			}
		}
		
		private decimal? _sCORE;
		public virtual decimal? SCORE
		{
			get
			{
				return this._sCORE;
			}
			set
			{
				this._sCORE = value;
			}
		}
		
		private string _nOTESUBTYPE;
		public virtual string NOTESUBTYPE
		{
			get
			{
				return this._nOTESUBTYPE;
			}
			set
			{
				this._nOTESUBTYPE = value;
			}
		}
		
		private DateTime? _dATEFROM;
		public virtual DateTime? DATEFROM
		{
			get
			{
				return this._dATEFROM;
			}
			set
			{
				this._dATEFROM = value;
			}
		}
		
		private DateTime? _dATETO;
		public virtual DateTime? DATETO
		{
			get
			{
				return this._dATETO;
			}
			set
			{
				this._dATETO = value;
			}
		}
		
		private System.Nullable<System.Char> _sTATUS;
		public virtual System.Nullable<System.Char> STATUS
		{
			get
			{
				return this._sTATUS;
			}
			set
			{
				this._sTATUS = value;
			}
		}
		
		private short? _iNDENT;
		public virtual short? INDENT
		{
			get
			{
				return this._iNDENT;
			}
			set
			{
				this._iNDENT = value;
			}
		}
		
		private string _kEYWORD;
		public virtual string KEYWORD
		{
			get
			{
				return this._kEYWORD;
			}
			set
			{
				this._kEYWORD = value;
			}
		}
		
	}
}
#pragma warning restore 1591
