#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMUH.iKASAWebApi.DomainModel.Entities;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class EDUNOTE
	{
		private string _nOTEID;
		public virtual string NOTEID
		{
			get
			{
				return this._nOTEID;
			}
			set
			{
				this._nOTEID = value;
			}
		}
		
		private string _nOTECODE;
		public virtual string NOTECODE
		{
			get
			{
				return this._nOTECODE;
			}
			set
			{
				this._nOTECODE = value;
			}
		}
		
		private string _vERSIONCODE;
		public virtual string VERSIONCODE
		{
			get
			{
				return this._vERSIONCODE;
			}
			set
			{
				this._vERSIONCODE = value;
			}
		}
		
		private DateTime? _nOTEDATE;
		public virtual DateTime? NOTEDATE
		{
			get
			{
				return this._nOTEDATE;
			}
			set
			{
				this._nOTEDATE = value;
			}
		}
		
		private System.Nullable<System.Char> _sTATUS;
		public virtual System.Nullable<System.Char> STATUS
		{
			get
			{
				return this._sTATUS;
			}
			set
			{
				this._sTATUS = value;
			}
		}
		
		private string _cREATER;
		public virtual string CREATER
		{
			get
			{
				return this._cREATER;
			}
			set
			{
				this._cREATER = value;
			}
		}
		
		private string _gRADECODE;
		public virtual string GRADECODE
		{
			get
			{
				return this._gRADECODE;
			}
			set
			{
				this._gRADECODE = value;
			}
		}
		
		private DateTime? _cREATEDATE;
		public virtual DateTime? CREATEDATE
		{
			get
			{
				return this._cREATEDATE;
			}
			set
			{
				this._cREATEDATE = value;
			}
		}
		
		private DateTime? _uPDATEDATE;
		public virtual DateTime? UPDATEDATE
		{
			get
			{
				return this._uPDATEDATE;
			}
			set
			{
				this._uPDATEDATE = value;
			}
		}
		
		private string _nSTATION;
		public virtual string NSTATION
		{
			get
			{
				return this._nSTATION;
			}
			set
			{
				this._nSTATION = value;
			}
		}
		
		private string _dEPCODE;
		public virtual string DEPCODE
		{
			get
			{
				return this._dEPCODE;
			}
			set
			{
				this._dEPCODE = value;
			}
		}
		
		private string _wARDCODE;
		public virtual string WARDCODE
		{
			get
			{
				return this._wARDCODE;
			}
			set
			{
				this._wARDCODE = value;
			}
		}
		
		private string _bEDNO;
		public virtual string BEDNO
		{
			get
			{
				return this._bEDNO;
			}
			set
			{
				this._bEDNO = value;
			}
		}
		
		private string _cLINICCODE;
		public virtual string CLINICCODE
		{
			get
			{
				return this._cLINICCODE;
			}
			set
			{
				this._cLINICCODE = value;
			}
		}
		
		private string _dES;
		public virtual string DES
		{
			get
			{
				return this._dES;
			}
			set
			{
				this._dES = value;
			}
		}
		
		private IList<EDUNOTEITEM> _eDUNOTEITEMs = new List<EDUNOTEITEM>();
		public virtual IList<EDUNOTEITEM> EDUNOTEITEMs
		{
			get
			{
				return this._eDUNOTEITEMs;
			}
		}
		
	}
}
#pragma warning restore 1591
