#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMUH.iKASAWebApi.DomainModel.Entities;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class EDUNOTEITEM
	{
		private string _nOTEITEMID;
		public virtual string NOTEITEMID
		{
			get
			{
				return this._nOTEITEMID;
			}
			set
			{
				this._nOTEITEMID = value;
			}
		}
		
		private string _nOTEID;
		public virtual string NOTEID
		{
			get
			{
				return this._nOTEID;
			}
			set
			{
				this._nOTEID = value;
			}
		}
		
		private string _nOTECODE;
		public virtual string NOTECODE
		{
			get
			{
				return this._nOTECODE;
			}
			set
			{
				this._nOTECODE = value;
			}
		}
		
		private decimal? _sCORE;
		public virtual decimal? SCORE
		{
			get
			{
				return this._sCORE;
			}
			set
			{
				this._sCORE = value;
			}
		}
		
		private string _nOTEDES;
		public virtual string NOTEDES
		{
			get
			{
				return this._nOTEDES;
			}
			set
			{
				this._nOTEDES = value;
			}
		}
		
		private DateTime? _nOTEDATE;
		public virtual DateTime? NOTEDATE
		{
			get
			{
				return this._nOTEDATE;
			}
			set
			{
				this._nOTEDATE = value;
			}
		}
		
		private string _cREATER;
		public virtual string CREATER
		{
			get
			{
				return this._cREATER;
			}
			set
			{
				this._cREATER = value;
			}
		}
		
		private EDUNOTE _eDUNOTE;
		public virtual EDUNOTE EDUNOTE
		{
			get
			{
				return this._eDUNOTE;
			}
			set
			{
				this._eDUNOTE = value;
			}
		}
		
	}
}
#pragma warning restore 1591
