#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class EDUNOTELIST
	{
		private string _nOTECODE;
		public virtual string NOTECODE
		{
			get
			{
				return this._nOTECODE;
			}
			set
			{
				this._nOTECODE = value;
			}
		}
		
		private string _cREATESQL;
		public virtual string CREATESQL
		{
			get
			{
				return this._cREATESQL;
			}
			set
			{
				this._cREATESQL = value;
			}
		}
		
		private string _dES;
		public virtual string DES
		{
			get
			{
				return this._dES;
			}
			set
			{
				this._dES = value;
			}
		}
		
		private string _nAME;
		public virtual string NAME
		{
			get
			{
				return this._nAME;
			}
			set
			{
				this._nAME = value;
			}
		}
		
		private string _pARENTNOTECODE;
		public virtual string PARENTNOTECODE
		{
			get
			{
				return this._pARENTNOTECODE;
			}
			set
			{
				this._pARENTNOTECODE = value;
			}
		}
		
	}
}
#pragma warning restore 1591
