#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMUH.iKASAWebApi.DomainModel.Entities;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class EDUPASSPORTTEMPLATE
	{
		private string _tEMPLATEID;
		public virtual string TEMPLATEID
		{
			get
			{
				return this._tEMPLATEID;
			}
			set
			{
				this._tEMPLATEID = value;
			}
		}
		
		private string _tEMPLATENAME;
		public virtual string TEMPLATENAME
		{
			get
			{
				return this._tEMPLATENAME;
			}
			set
			{
				this._tEMPLATENAME = value;
			}
		}
		
		private DateTime? _sDATE;
		public virtual DateTime? SDATE
		{
			get
			{
				return this._sDATE;
			}
			set
			{
				this._sDATE = value;
			}
		}
		
		private DateTime? _eDATE;
		public virtual DateTime? EDATE
		{
			get
			{
				return this._eDATE;
			}
			set
			{
				this._eDATE = value;
			}
		}
		
		private string _sTATUS;
		public virtual string STATUS
		{
			get
			{
				return this._sTATUS;
			}
			set
			{
				this._sTATUS = value;
			}
		}
		
		private string _cREATER;
		public virtual string CREATER
		{
			get
			{
				return this._cREATER;
			}
			set
			{
				this._cREATER = value;
			}
		}
		
		private DateTime? _cREATEDATE;
		public virtual DateTime? CREATEDATE
		{
			get
			{
				return this._cREATEDATE;
			}
			set
			{
				this._cREATEDATE = value;
			}
		}
		
		private string _mODIFIER;
		public virtual string MODIFIER
		{
			get
			{
				return this._mODIFIER;
			}
			set
			{
				this._mODIFIER = value;
			}
		}
		
		private DateTime? _mODIFYDATE;
		public virtual DateTime? MODIFYDATE
		{
			get
			{
				return this._mODIFYDATE;
			}
			set
			{
				this._mODIFYDATE = value;
			}
		}
		
		private string _tEMPLATEDESC;
		public virtual string TEMPLATEDESC
		{
			get
			{
				return this._tEMPLATEDESC;
			}
			set
			{
				this._tEMPLATEDESC = value;
			}
		}
		
		private bool _aLLOWADMINCONFIRM;
		public virtual bool ALLOWADMINCONFIRM
		{
			get
			{
				return this._aLLOWADMINCONFIRM;
			}
			set
			{
				this._aLLOWADMINCONFIRM = value;
			}
		}
		
		private IList<EDUPASSPORTTEMPLATETARGET> _eDUPASSPORTTEMPLATETARGETs = new List<EDUPASSPORTTEMPLATETARGET>();
		public virtual IList<EDUPASSPORTTEMPLATETARGET> EDUPASSPORTTEMPLATETARGETs
		{
			get
			{
				return this._eDUPASSPORTTEMPLATETARGETs;
			}
		}
		
		private IList<EDUPASSPORTTEMPLATEITEM> _eDUPASSPORTTEMPLATEITEMs = new List<EDUPASSPORTTEMPLATEITEM>();
		public virtual IList<EDUPASSPORTTEMPLATEITEM> EDUPASSPORTTEMPLATEITEMs
		{
			get
			{
				return this._eDUPASSPORTTEMPLATEITEMs;
			}
		}
		
	}
}
#pragma warning restore 1591
