#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMUH.iKASAWebApi.DomainModel.Entities;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class EDUPASSPORTITEM
	{
		private string _iTEMID;
		public virtual string ITEMID
		{
			get
			{
				return this._iTEMID;
			}
			set
			{
				this._iTEMID = value;
			}
		}
		
		private string _iTEMNAME;
		public virtual string ITEMNAME
		{
			get
			{
				return this._iTEMNAME;
			}
			set
			{
				this._iTEMNAME = value;
			}
		}
		
		private string _cREATER;
		public virtual string CREATER
		{
			get
			{
				return this._cREATER;
			}
			set
			{
				this._cREATER = value;
			}
		}
		
		private DateTime? _cREATEDATE;
		public virtual DateTime? CREATEDATE
		{
			get
			{
				return this._cREATEDATE;
			}
			set
			{
				this._cREATEDATE = value;
			}
		}
		
		private string _mODIFIER;
		public virtual string MODIFIER
		{
			get
			{
				return this._mODIFIER;
			}
			set
			{
				this._mODIFIER = value;
			}
		}
		
		private DateTime? _mODIFYDATE;
		public virtual DateTime? MODIFYDATE
		{
			get
			{
				return this._mODIFYDATE;
			}
			set
			{
				this._mODIFYDATE = value;
			}
		}
		
		private string _rEMARK;
		public virtual string REMARK
		{
			get
			{
				return this._rEMARK;
			}
			set
			{
				this._rEMARK = value;
			}
		}
		
		private string _sTATUS;
		public virtual string STATUS
		{
			get
			{
				return this._sTATUS;
			}
			set
			{
				this._sTATUS = value;
			}
		}
		
		private bool _iSNECESSARY;
		public virtual bool ISNECESSARY
		{
			get
			{
				return this._iSNECESSARY;
			}
			set
			{
				this._iSNECESSARY = value;
			}
		}
		
		private string _iTEMDESC;
		public virtual string ITEMDESC
		{
			get
			{
				return this._iTEMDESC;
			}
			set
			{
				this._iTEMDESC = value;
			}
		}
		
		private IList<EDUPASSPORTTEMPLATEITEM> _eDUPASSPORTTEMPLATEITEMs = new List<EDUPASSPORTTEMPLATEITEM>();
		public virtual IList<EDUPASSPORTTEMPLATEITEM> EDUPASSPORTTEMPLATEITEMs
		{
			get
			{
				return this._eDUPASSPORTTEMPLATEITEMs;
			}
		}
		
		private IList<EDUPASSPORTPREF> _eDUPASSPORTPREFs = new List<EDUPASSPORTPREF>();
		public virtual IList<EDUPASSPORTPREF> EDUPASSPORTPREFs
		{
			get
			{
				return this._eDUPASSPORTPREFs;
			}
		}
		
		private IList<EDUPASSPORTITEMTARGET> _eDUPASSPORTITEMTARGETs = new List<EDUPASSPORTITEMTARGET>();
		public virtual IList<EDUPASSPORTITEMTARGET> EDUPASSPORTITEMTARGETs
		{
			get
			{
				return this._eDUPASSPORTITEMTARGETs;
			}
		}
		
		private IList<EDUPASSPORTITEMDET> _eDUPASSPORTITEMDETs = new List<EDUPASSPORTITEMDET>();
		public virtual IList<EDUPASSPORTITEMDET> EDUPASSPORTITEMDETs
		{
			get
			{
				return this._eDUPASSPORTITEMDETs;
			}
		}
		
		private IList<EDUPASSPORTINSITEM> _eDUPASSPORTINSITEMs = new List<EDUPASSPORTINSITEM>();
		public virtual IList<EDUPASSPORTINSITEM> EDUPASSPORTINSITEMs
		{
			get
			{
				return this._eDUPASSPORTINSITEMs;
			}
		}
		
	}
}
#pragma warning restore 1591
