#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMUH.iKASAWebApi.DomainModel.Entities;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class EDUPASSPORTINSTANCE
	{
		private string _iNSTANCEID;
		public virtual string INSTANCEID
		{
			get
			{
				return this._iNSTANCEID;
			}
			set
			{
				this._iNSTANCEID = value;
			}
		}
		
		private string _tEMPLATEID;
		public virtual string TEMPLATEID
		{
			get
			{
				return this._tEMPLATEID;
			}
			set
			{
				this._tEMPLATEID = value;
			}
		}
		
		private string _tEMPLATENAME;
		public virtual string TEMPLATENAME
		{
			get
			{
				return this._tEMPLATENAME;
			}
			set
			{
				this._tEMPLATENAME = value;
			}
		}
		
		private string _eMPCODE;
		public virtual string EMPCODE
		{
			get
			{
				return this._eMPCODE;
			}
			set
			{
				this._eMPCODE = value;
			}
		}
		
		private DateTime? _cREATEDATE;
		public virtual DateTime? CREATEDATE
		{
			get
			{
				return this._cREATEDATE;
			}
			set
			{
				this._cREATEDATE = value;
			}
		}
		
		private string _jOBSERIAL;
		public virtual string JOBSERIAL
		{
			get
			{
				return this._jOBSERIAL;
			}
			set
			{
				this._jOBSERIAL = value;
			}
		}
		
		private string _sTATUS;
		public virtual string STATUS
		{
			get
			{
				return this._sTATUS;
			}
			set
			{
				this._sTATUS = value;
			}
		}
		
		private IList<EDUPASSPORTINSITEM> _eDUPASSPORTINSITEMs = new List<EDUPASSPORTINSITEM>();
		public virtual IList<EDUPASSPORTINSITEM> EDUPASSPORTINSITEMs
		{
			get
			{
				return this._eDUPASSPORTINSITEMs;
			}
		}
		
	}
}
#pragma warning restore 1591
