#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMUH.iKASAWebApi.DomainModel.Entities;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class EDUPASSPORTITEMDET
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _iTEMID;
		public virtual string ITEMID
		{
			get
			{
				return this._iTEMID;
			}
			set
			{
				this._iTEMID = value;
			}
		}
		
		private string _fIELDDESC;
		public virtual string FIELDDESC
		{
			get
			{
				return this._fIELDDESC;
			}
			set
			{
				this._fIELDDESC = value;
			}
		}
		
		private string _fIELDTARGET;
		public virtual string FIELDTARGET
		{
			get
			{
				return this._fIELDTARGET;
			}
			set
			{
				this._fIELDTARGET = value;
			}
		}
		
		private int _sEQ;
		public virtual int SEQ
		{
			get
			{
				return this._sEQ;
			}
			set
			{
				this._sEQ = value;
			}
		}
		
		private string _fIELDTYPE;
		public virtual string FIELDTYPE
		{
			get
			{
				return this._fIELDTYPE;
			}
			set
			{
				this._fIELDTYPE = value;
			}
		}
		
		private bool _iSNECESSARY;
		public virtual bool ISNECESSARY
		{
			get
			{
				return this._iSNECESSARY;
			}
			set
			{
				this._iSNECESSARY = value;
			}
		}
		
		private string _sELECTOPTIONS;
		public virtual string SELECTOPTIONS
		{
			get
			{
				return this._sELECTOPTIONS;
			}
			set
			{
				this._sELECTOPTIONS = value;
			}
		}
		
		private EDUPASSPORTITEM _eDUPASSPORTITEM;
		public virtual EDUPASSPORTITEM EDUPASSPORTITEM
		{
			get
			{
				return this._eDUPASSPORTITEM;
			}
			set
			{
				this._eDUPASSPORTITEM = value;
			}
		}
		
	}
}
#pragma warning restore 1591
