#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class EDUPASSPORTINSITEMREJECTHI
	{
		private int _rEJECTID;
		public virtual int REJECTID
		{
			get
			{
				return this._rEJECTID;
			}
			set
			{
				this._rEJECTID = value;
			}
		}
		
		private string _iITEMID;
		public virtual string IITEMID
		{
			get
			{
				return this._iITEMID;
			}
			set
			{
				this._iITEMID = value;
			}
		}
		
		private DateTime? _rEJECTTIME;
		public virtual DateTime? REJECTTIME
		{
			get
			{
				return this._rEJECTTIME;
			}
			set
			{
				this._rEJECTTIME = value;
			}
		}
		
		private string _eMPCODE;
		public virtual string EMPCODE
		{
			get
			{
				return this._eMPCODE;
			}
			set
			{
				this._eMPCODE = value;
			}
		}
		
		private string _rEASON;
		public virtual string REASON
		{
			get
			{
				return this._rEASON;
			}
			set
			{
				this._rEASON = value;
			}
		}
		
	}
}
#pragma warning restore 1591
