#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class EDUQUESTION
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _tARGETROLE;
		public virtual string TARGETROLE
		{
			get
			{
				return this._tARGETROLE;
			}
			set
			{
				this._tARGETROLE = value;
			}
		}
		
		private string _qUESTIONTITLE;
		public virtual string QUESTIONTITLE
		{
			get
			{
				return this._qUESTIONTITLE;
			}
			set
			{
				this._qUESTIONTITLE = value;
			}
		}
		
		private string _qUESTIONSUBJECT;
		public virtual string QUESTIONSUBJECT
		{
			get
			{
				return this._qUESTIONSUBJECT;
			}
			set
			{
				this._qUESTIONSUBJECT = value;
			}
		}
		
		private int _tEMPLATE_ID;
		public virtual int TEMPLATE_ID
		{
			get
			{
				return this._tEMPLATE_ID;
			}
			set
			{
				this._tEMPLATE_ID = value;
			}
		}
		
		private DateTime _sDATE;
		public virtual DateTime SDATE
		{
			get
			{
				return this._sDATE;
			}
			set
			{
				this._sDATE = value;
			}
		}
		
		private DateTime _eDATE;
		public virtual DateTime EDATE
		{
			get
			{
				return this._eDATE;
			}
			set
			{
				this._eDATE = value;
			}
		}
		
		private string _qGROUP;
		public virtual string QGROUP
		{
			get
			{
				return this._qGROUP;
			}
			set
			{
				this._qGROUP = value;
			}
		}
		
		private bool _iSFORCE;
		public virtual bool ISFORCE
		{
			get
			{
				return this._iSFORCE;
			}
			set
			{
				this._iSFORCE = value;
			}
		}
		
	}
}
#pragma warning restore 1591
