#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMUH.iKASAWebApi.DomainModel.Entities;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class EDUSTOPACTSCHEDULE
	{
		private string _eDUSTOPACTSCHEDULEID;
		public virtual string EDUSTOPACTSCHEDULEID
		{
			get
			{
				return this._eDUSTOPACTSCHEDULEID;
			}
			set
			{
				this._eDUSTOPACTSCHEDULEID = value;
			}
		}
		
		private string _eDUACTTOPICID;
		public virtual string EDUACTTOPICID
		{
			get
			{
				return this._eDUACTTOPICID;
			}
			set
			{
				this._eDUACTTOPICID = value;
			}
		}
		
		private string _eDUTERMID;
		public virtual string EDUTERMID
		{
			get
			{
				return this._eDUTERMID;
			}
			set
			{
				this._eDUTERMID = value;
			}
		}
		
		private DateTime? _tIMEFROM;
		public virtual DateTime? TIMEFROM
		{
			get
			{
				return this._tIMEFROM;
			}
			set
			{
				this._tIMEFROM = value;
			}
		}
		
		private DateTime? _tIMETO;
		public virtual DateTime? TIMETO
		{
			get
			{
				return this._tIMETO;
			}
			set
			{
				this._tIMETO = value;
			}
		}
		
		private string _dES;
		public virtual string DES
		{
			get
			{
				return this._dES;
			}
			set
			{
				this._dES = value;
			}
		}
		
		private string _aCTTYPE;
		public virtual string ACTTYPE
		{
			get
			{
				return this._aCTTYPE;
			}
			set
			{
				this._aCTTYPE = value;
			}
		}
		
		private string _cORCHID;
		public virtual string CORCHID
		{
			get
			{
				return this._cORCHID;
			}
			set
			{
				this._cORCHID = value;
			}
		}
		
		private string _lOCATION;
		public virtual string LOCATION
		{
			get
			{
				return this._lOCATION;
			}
			set
			{
				this._lOCATION = value;
			}
		}
		
		private string _aCTTYPEDES;
		public virtual string ACTTYPEDES
		{
			get
			{
				return this._aCTTYPEDES;
			}
			set
			{
				this._aCTTYPEDES = value;
			}
		}
		
		private string _cREATER;
		public virtual string CREATER
		{
			get
			{
				return this._cREATER;
			}
			set
			{
				this._cREATER = value;
			}
		}
		
		private string _lASTMODIFIER;
		public virtual string LASTMODIFIER
		{
			get
			{
				return this._lASTMODIFIER;
			}
			set
			{
				this._lASTMODIFIER = value;
			}
		}
		
		private string _aCTNAME;
		public virtual string ACTNAME
		{
			get
			{
				return this._aCTNAME;
			}
			set
			{
				this._aCTNAME = value;
			}
		}
		
		private string _rEFURL;
		public virtual string REFURL
		{
			get
			{
				return this._rEFURL;
			}
			set
			{
				this._rEFURL = value;
			}
		}
		
		private string _dEPTCODE;
		public virtual string DEPTCODE
		{
			get
			{
				return this._dEPTCODE;
			}
			set
			{
				this._dEPTCODE = value;
			}
		}
		
		private DateTime? _dISPLAYTIMEFROM;
		public virtual DateTime? DISPLAYTIMEFROM
		{
			get
			{
				return this._dISPLAYTIMEFROM;
			}
			set
			{
				this._dISPLAYTIMEFROM = value;
			}
		}
		
		private DateTime? _dISPLAYTIMETO;
		public virtual DateTime? DISPLAYTIMETO
		{
			get
			{
				return this._dISPLAYTIMETO;
			}
			set
			{
				this._dISPLAYTIMETO = value;
			}
		}
		
		private string _aCTRANGE;
		public virtual string ACTRANGE
		{
			get
			{
				return this._aCTRANGE;
			}
			set
			{
				this._aCTRANGE = value;
			}
		}
		
		private string _hOSPCODE;
		public virtual string HOSPCODE
		{
			get
			{
				return this._hOSPCODE;
			}
			set
			{
				this._hOSPCODE = value;
			}
		}
		
		private string _pROPERTYTYPE;
		public virtual string PROPERTYTYPE
		{
			get
			{
				return this._pROPERTYTYPE;
			}
			set
			{
				this._pROPERTYTYPE = value;
			}
		}
		
		private bool _aLLOWBOOKING;
		public virtual bool ALLOWBOOKING
		{
			get
			{
				return this._aLLOWBOOKING;
			}
			set
			{
				this._aLLOWBOOKING = value;
			}
		}
		
		private int? _bOOKINGLIMIT;
		public virtual int? BOOKINGLIMIT
		{
			get
			{
				return this._bOOKINGLIMIT;
			}
			set
			{
				this._bOOKINGLIMIT = value;
			}
		}
		
		private bool _hASOUTSIDESTUDENT;
		public virtual bool HASOUTSIDESTUDENT
		{
			get
			{
				return this._hASOUTSIDESTUDENT;
			}
			set
			{
				this._hASOUTSIDESTUDENT = value;
			}
		}
		
		private bool? _eNABLEREC;
		public virtual bool? ENABLEREC
		{
			get
			{
				return this._eNABLEREC;
			}
			set
			{
				this._eNABLEREC = value;
			}
		}
		
		private int? _rECTEMPLATEID;
		public virtual int? RECTEMPLATEID
		{
			get
			{
				return this._rECTEMPLATEID;
			}
			set
			{
				this._rECTEMPLATEID = value;
			}
		}
		
		private bool _hASTARGETS;
		public virtual bool HASTARGETS
		{
			get
			{
				return this._hASTARGETS;
			}
			set
			{
				this._hASTARGETS = value;
			}
		}
		
		private bool _hASATTACHMENTS;
		public virtual bool HASATTACHMENTS
		{
			get
			{
				return this._hASATTACHMENTS;
			}
			set
			{
				this._hASATTACHMENTS = value;
			}
		}
		
		private IList<RECORDEDUACTREF> _rECORDEDUACTREFs = new List<RECORDEDUACTREF>();
		public virtual IList<RECORDEDUACTREF> RECORDEDUACTREFs
		{
			get
			{
				return this._rECORDEDUACTREFs;
			}
		}
		
		private IList<EDUSTOPACTATTACHMENT> _eDUSTOPACTATTACHMENTs = new List<EDUSTOPACTATTACHMENT>();
		public virtual IList<EDUSTOPACTATTACHMENT> EDUSTOPACTATTACHMENTs
		{
			get
			{
				return this._eDUSTOPACTATTACHMENTs;
			}
		}
		
		private IList<EDUACTVIEWTARGET> _eDUACTVIEWTARGETs = new List<EDUACTVIEWTARGET>();
		public virtual IList<EDUACTVIEWTARGET> EDUACTVIEWTARGETs
		{
			get
			{
				return this._eDUACTVIEWTARGETs;
			}
		}
		
		private IList<EDUACTTYPEREF> _eDUACTTYPEREFs = new List<EDUACTTYPEREF>();
		public virtual IList<EDUACTTYPEREF> EDUACTTYPEREFs
		{
			get
			{
				return this._eDUACTTYPEREFs;
			}
		}
		
		private IList<EDUACTTARGET> _eDUACTTARGETs = new List<EDUACTTARGET>();
		public virtual IList<EDUACTTARGET> EDUACTTARGETs
		{
			get
			{
				return this._eDUACTTARGETs;
			}
		}
		
	}
}
#pragma warning restore 1591
