#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class EDUSETTING
	{
		private string _cODETYPE;
		public virtual string CODETYPE
		{
			get
			{
				return this._cODETYPE;
			}
			set
			{
				this._cODETYPE = value;
			}
		}
		
		private string _cODE;
		public virtual string CODE
		{
			get
			{
				return this._cODE;
			}
			set
			{
				this._cODE = value;
			}
		}
		
		private string _nAME;
		public virtual string NAME
		{
			get
			{
				return this._nAME;
			}
			set
			{
				this._nAME = value;
			}
		}
		
		private string _sETTINGVALUE;
		public virtual string SETTINGVALUE
		{
			get
			{
				return this._sETTINGVALUE;
			}
			set
			{
				this._sETTINGVALUE = value;
			}
		}
		
		private string _dES;
		public virtual string DES
		{
			get
			{
				return this._dES;
			}
			set
			{
				this._dES = value;
			}
		}
		
	}
}
#pragma warning restore 1591
