#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class EDUSENTENCE
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _eMPCODE;
		public virtual string EMPCODE
		{
			get
			{
				return this._eMPCODE;
			}
			set
			{
				this._eMPCODE = value;
			}
		}
		
		private DateTime _cREATEDATE;
		public virtual DateTime CREATEDATE
		{
			get
			{
				return this._cREATEDATE;
			}
			set
			{
				this._cREATEDATE = value;
			}
		}
		
		private DateTime? _mODIFYDATE;
		public virtual DateTime? MODIFYDATE
		{
			get
			{
				return this._mODIFYDATE;
			}
			set
			{
				this._mODIFYDATE = value;
			}
		}
		
		private string _sENTENCE;
		public virtual string SENTENCE
		{
			get
			{
				return this._sENTENCE;
			}
			set
			{
				this._sENTENCE = value;
			}
		}
		
		private bool _iSPUBLIC;
		public virtual bool ISPUBLIC
		{
			get
			{
				return this._iSPUBLIC;
			}
			set
			{
				this._iSPUBLIC = value;
			}
		}
		
	}
}
#pragma warning restore 1591
