#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class EDUTERMFORMREQ
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _eDUTERMID;
		public virtual string EDUTERMID
		{
			get
			{
				return this._eDUTERMID;
			}
			set
			{
				this._eDUTERMID = value;
			}
		}
		
		private string _rEQTYPE;
		public virtual string REQTYPE
		{
			get
			{
				return this._rEQTYPE;
			}
			set
			{
				this._rEQTYPE = value;
			}
		}
		
		private int _rEQID;
		public virtual int REQID
		{
			get
			{
				return this._rEQID;
			}
			set
			{
				this._rEQID = value;
			}
		}
		
		private int _rEQCOUNT;
		public virtual int REQCOUNT
		{
			get
			{
				return this._rEQCOUNT;
			}
			set
			{
				this._rEQCOUNT = value;
			}
		}
		
		private DateTime _cREATEDATE;
		public virtual DateTime CREATEDATE
		{
			get
			{
				return this._cREATEDATE;
			}
			set
			{
				this._cREATEDATE = value;
			}
		}
		
		private string _cREATER;
		public virtual string CREATER
		{
			get
			{
				return this._cREATER;
			}
			set
			{
				this._cREATER = value;
			}
		}
		
		private bool _nEEDPASS;
		public virtual bool NEEDPASS
		{
			get
			{
				return this._nEEDPASS;
			}
			set
			{
				this._nEEDPASS = value;
			}
		}
		
	}
}
#pragma warning restore 1591
