#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMUH.iKASAWebApi.DomainModel.Entities;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class EDUTERMFORMREQTEMPLATE
	{
		private int _tEMPLATEID;
		public virtual int TEMPLATEID
		{
			get
			{
				return this._tEMPLATEID;
			}
			set
			{
				this._tEMPLATEID = value;
			}
		}
		
		private string _tEMPLATENAME;
		public virtual string TEMPLATENAME
		{
			get
			{
				return this._tEMPLATENAME;
			}
			set
			{
				this._tEMPLATENAME = value;
			}
		}
		
		private string _cREATER;
		public virtual string CREATER
		{
			get
			{
				return this._cREATER;
			}
			set
			{
				this._cREATER = value;
			}
		}
		
		private DateTime? _cREATEDATE;
		public virtual DateTime? CREATEDATE
		{
			get
			{
				return this._cREATEDATE;
			}
			set
			{
				this._cREATEDATE = value;
			}
		}
		
		private string _mODIFIER;
		public virtual string MODIFIER
		{
			get
			{
				return this._mODIFIER;
			}
			set
			{
				this._mODIFIER = value;
			}
		}
		
		private DateTime? _mODIFYDATE;
		public virtual DateTime? MODIFYDATE
		{
			get
			{
				return this._mODIFYDATE;
			}
			set
			{
				this._mODIFYDATE = value;
			}
		}
		
		private IList<EDUTERMFORMREQTEMPLATEDET> _eDUTERMFORMREQTEMPLATEDETs = new List<EDUTERMFORMREQTEMPLATEDET>();
		public virtual IList<EDUTERMFORMREQTEMPLATEDET> EDUTERMFORMREQTEMPLATEDETs
		{
			get
			{
				return this._eDUTERMFORMREQTEMPLATEDETs;
			}
		}
		
	}
}
#pragma warning restore 1591
