#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMUH.iKASAWebApi.DomainModel.Entities;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class EDUTEAMRUNDOWN
	{
		private string _eDUTEAMSTOPID;
		public virtual string EDUTEAMSTOPID
		{
			get
			{
				return this._eDUTEAMSTOPID;
			}
			set
			{
				this._eDUTEAMSTOPID = value;
			}
		}
		
		private string _eDUTERMID;
		public virtual string EDUTERMID
		{
			get
			{
				return this._eDUTERMID;
			}
			set
			{
				this._eDUTERMID = value;
			}
		}
		
		private string _eDUTEAMCODE;
		public virtual string EDUTEAMCODE
		{
			get
			{
				return this._eDUTEAMCODE;
			}
			set
			{
				this._eDUTEAMCODE = value;
			}
		}
		
		private DateTime? _dATEFROM;
		public virtual DateTime? DATEFROM
		{
			get
			{
				return this._dATEFROM;
			}
			set
			{
				this._dATEFROM = value;
			}
		}
		
		private DateTime? _dATETO;
		public virtual DateTime? DATETO
		{
			get
			{
				return this._dATETO;
			}
			set
			{
				this._dATETO = value;
			}
		}
		
		private EDUTERM _eDUTERM;
		public virtual EDUTERM EDUTERM
		{
			get
			{
				return this._eDUTERM;
			}
			set
			{
				this._eDUTERM = value;
			}
		}
		
		private EDUTEAM _eDUTEAM;
		public virtual EDUTEAM EDUTEAM
		{
			get
			{
				return this._eDUTEAM;
			}
			set
			{
				this._eDUTEAM = value;
			}
		}
		
	}
}
#pragma warning restore 1591
