#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMUH.iKASAWebApi.DomainModel.Entities;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class ELEARNINGCLASS
	{
		private string _cLASSID;
		public virtual string CLASSID
		{
			get
			{
				return this._cLASSID;
			}
			set
			{
				this._cLASSID = value;
			}
		}
		
		private string _cLASSNAME;
		public virtual string CLASSNAME
		{
			get
			{
				return this._cLASSNAME;
			}
			set
			{
				this._cLASSNAME = value;
			}
		}
		
		private bool _aLLOWBOOKING;
		public virtual bool ALLOWBOOKING
		{
			get
			{
				return this._aLLOWBOOKING;
			}
			set
			{
				this._aLLOWBOOKING = value;
			}
		}
		
		private string _cREATER;
		public virtual string CREATER
		{
			get
			{
				return this._cREATER;
			}
			set
			{
				this._cREATER = value;
			}
		}
		
		private DateTime? _cREATEDATE;
		public virtual DateTime? CREATEDATE
		{
			get
			{
				return this._cREATEDATE;
			}
			set
			{
				this._cREATEDATE = value;
			}
		}
		
		private DateTime? _sDATE;
		public virtual DateTime? SDATE
		{
			get
			{
				return this._sDATE;
			}
			set
			{
				this._sDATE = value;
			}
		}
		
		private DateTime? _eDATE;
		public virtual DateTime? EDATE
		{
			get
			{
				return this._eDATE;
			}
			set
			{
				this._eDATE = value;
			}
		}
		
		private string _sTATUS;
		public virtual string STATUS
		{
			get
			{
				return this._sTATUS;
			}
			set
			{
				this._sTATUS = value;
			}
		}
		
		private IList<ELEARNINGITEM> _eLEARNINGITEMs = new List<ELEARNINGITEM>();
		public virtual IList<ELEARNINGITEM> ELEARNINGITEMs
		{
			get
			{
				return this._eLEARNINGITEMs;
			}
		}
		
		private IList<ELEARNINGBOOKING> _eLEARNINGBOOKINGs = new List<ELEARNINGBOOKING>();
		public virtual IList<ELEARNINGBOOKING> ELEARNINGBOOKINGs
		{
			get
			{
				return this._eLEARNINGBOOKINGs;
			}
		}
		
	}
}
#pragma warning restore 1591
