#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class FORM_INSTANCE_RETURN_LOG
	{
		private int _lOG_ID;
		public virtual int LOG_ID
		{
			get
			{
				return this._lOG_ID;
			}
			set
			{
				this._lOG_ID = value;
			}
		}
		
		private int _iNSTANCE_ID;
		public virtual int INSTANCE_ID
		{
			get
			{
				return this._iNSTANCE_ID;
			}
			set
			{
				this._iNSTANCE_ID = value;
			}
		}
		
		private string _rETURN_REASON;
		public virtual string RETURN_REASON
		{
			get
			{
				return this._rETURN_REASON;
			}
			set
			{
				this._rETURN_REASON = value;
			}
		}
		
		private DateTime? _rETURN_TIME;
		public virtual DateTime? RETURN_TIME
		{
			get
			{
				return this._rETURN_TIME;
			}
			set
			{
				this._rETURN_TIME = value;
			}
		}
		
		private string _rETURN_EMP;
		public virtual string RETURN_EMP
		{
			get
			{
				return this._rETURN_EMP;
			}
			set
			{
				this._rETURN_EMP = value;
			}
		}
		
	}
}
#pragma warning restore 1591
