#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class FORM_TEMPLATE_LIBRARY
	{
		private int _fORM_TEMPLATE_LIBRARY_ID;
		public virtual int FORM_TEMPLATE_LIBRARY_ID
		{
			get
			{
				return this._fORM_TEMPLATE_LIBRARY_ID;
			}
			set
			{
				this._fORM_TEMPLATE_LIBRARY_ID = value;
			}
		}
		
		private int? _fORM_TEMPLATE_ID;
		public virtual int? FORM_TEMPLATE_ID
		{
			get
			{
				return this._fORM_TEMPLATE_ID;
			}
			set
			{
				this._fORM_TEMPLATE_ID = value;
			}
		}
		
		private string _qUESTION_CONTENT;
		public virtual string QUESTION_CONTENT
		{
			get
			{
				return this._qUESTION_CONTENT;
			}
			set
			{
				this._qUESTION_CONTENT = value;
			}
		}
		
		private string _qUESTION_TYPE;
		public virtual string QUESTION_TYPE
		{
			get
			{
				return this._qUESTION_TYPE;
			}
			set
			{
				this._qUESTION_TYPE = value;
			}
		}
		
		private bool _dISPLAY;
		public virtual bool DISPLAY
		{
			get
			{
				return this._dISPLAY;
			}
			set
			{
				this._dISPLAY = value;
			}
		}
		
	}
}
#pragma warning restore 1591
