#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class FORM_INSTANCE_EXPRESSIONS_BK
	{
		private int _iNSTANCE_EXPRESSION_ID;
		public virtual int INSTANCE_EXPRESSION_ID
		{
			get
			{
				return this._iNSTANCE_EXPRESSION_ID;
			}
			set
			{
				this._iNSTANCE_EXPRESSION_ID = value;
			}
		}
		
		private int _tEMPLATE_EXPRESSION_ID;
		public virtual int TEMPLATE_EXPRESSION_ID
		{
			get
			{
				return this._tEMPLATE_EXPRESSION_ID;
			}
			set
			{
				this._tEMPLATE_EXPRESSION_ID = value;
			}
		}
		
		private int _iNSTANCE_ID;
		public virtual int INSTANCE_ID
		{
			get
			{
				return this._iNSTANCE_ID;
			}
			set
			{
				this._iNSTANCE_ID = value;
			}
		}
		
		private double _eXPRESSION_VALUE;
		public virtual double EXPRESSION_VALUE
		{
			get
			{
				return this._eXPRESSION_VALUE;
			}
			set
			{
				this._eXPRESSION_VALUE = value;
			}
		}
		
	}
}
#pragma warning restore 1591
