#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class FORM_INSTANCE_BLOCK
	{
		private int _iNSTANCE_BLOCKS_ID;
		public virtual int INSTANCE_BLOCKS_ID
		{
			get
			{
				return this._iNSTANCE_BLOCKS_ID;
			}
			set
			{
				this._iNSTANCE_BLOCKS_ID = value;
			}
		}
		
		private int _iNSTANCE_ID;
		public virtual int INSTANCE_ID
		{
			get
			{
				return this._iNSTANCE_ID;
			}
			set
			{
				this._iNSTANCE_ID = value;
			}
		}
		
		private string _tABLE_BLOCK_ID;
		public virtual string TABLE_BLOCK_ID
		{
			get
			{
				return this._tABLE_BLOCK_ID;
			}
			set
			{
				this._tABLE_BLOCK_ID = value;
			}
		}
		
		private string _bLOCK_CONTENT;
		public virtual string BLOCK_CONTENT
		{
			get
			{
				return this._bLOCK_CONTENT;
			}
			set
			{
				this._bLOCK_CONTENT = value;
			}
		}
		
		private string _tABLE_BLOCK_TITLE;
		public virtual string TABLE_BLOCK_TITLE
		{
			get
			{
				return this._tABLE_BLOCK_TITLE;
			}
			set
			{
				this._tABLE_BLOCK_TITLE = value;
			}
		}
		
	}
}
#pragma warning restore 1591
