#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class FORM_INSTANCES_DELLOG
	{
		private int _iNSTANCE_ID;
		public virtual int INSTANCE_ID
		{
			get
			{
				return this._iNSTANCE_ID;
			}
			set
			{
				this._iNSTANCE_ID = value;
			}
		}
		
		private int _tEMPLATE_ID;
		public virtual int TEMPLATE_ID
		{
			get
			{
				return this._tEMPLATE_ID;
			}
			set
			{
				this._tEMPLATE_ID = value;
			}
		}
		
		private string _iNSTANCE_NAME;
		public virtual string INSTANCE_NAME
		{
			get
			{
				return this._iNSTANCE_NAME;
			}
			set
			{
				this._iNSTANCE_NAME = value;
			}
		}
		
		private DateTime _iNSTANCE_CREATE_DATETIME;
		public virtual DateTime INSTANCE_CREATE_DATETIME
		{
			get
			{
				return this._iNSTANCE_CREATE_DATETIME;
			}
			set
			{
				this._iNSTANCE_CREATE_DATETIME = value;
			}
		}
		
		private DateTime? _iNSTANCE_ALTER_DATETIME;
		public virtual DateTime? INSTANCE_ALTER_DATETIME
		{
			get
			{
				return this._iNSTANCE_ALTER_DATETIME;
			}
			set
			{
				this._iNSTANCE_ALTER_DATETIME = value;
			}
		}
		
		private string _iNSTANCE_REMARK;
		public virtual string INSTANCE_REMARK
		{
			get
			{
				return this._iNSTANCE_REMARK;
			}
			set
			{
				this._iNSTANCE_REMARK = value;
			}
		}
		
		private string _iNSTANCE_CONTENT;
		public virtual string INSTANCE_CONTENT
		{
			get
			{
				return this._iNSTANCE_CONTENT;
			}
			set
			{
				this._iNSTANCE_CONTENT = value;
			}
		}
		
		private string _iNHOSPID;
		public virtual string INHOSPID
		{
			get
			{
				return this._iNHOSPID;
			}
			set
			{
				this._iNHOSPID = value;
			}
		}
		
		private string _cREATER;
		public virtual string CREATER
		{
			get
			{
				return this._cREATER;
			}
			set
			{
				this._cREATER = value;
			}
		}
		
		private DateTime? _eXPIREDATE;
		public virtual DateTime? EXPIREDATE
		{
			get
			{
				return this._eXPIREDATE;
			}
			set
			{
				this._eXPIREDATE = value;
			}
		}
		
		private string _tARGETTYPE;
		public virtual string TARGETTYPE
		{
			get
			{
				return this._tARGETTYPE;
			}
			set
			{
				this._tARGETTYPE = value;
			}
		}
		
		private string _tARGETID;
		public virtual string TARGETID
		{
			get
			{
				return this._tARGETID;
			}
			set
			{
				this._tARGETID = value;
			}
		}
		
		private Char _sTATUS;
		public virtual Char STATUS
		{
			get
			{
				return this._sTATUS;
			}
			set
			{
				this._sTATUS = value;
			}
		}
		
		private int? _pARENT_INSTANCE_ID;
		public virtual int? PARENT_INSTANCE_ID
		{
			get
			{
				return this._pARENT_INSTANCE_ID;
			}
			set
			{
				this._pARENT_INSTANCE_ID = value;
			}
		}
		
		private string _eVALTARGETID;
		public virtual string EVALTARGETID
		{
			get
			{
				return this._eVALTARGETID;
			}
			set
			{
				this._eVALTARGETID = value;
			}
		}
		
		private bool? _iSPASS;
		public virtual bool? ISPASS
		{
			get
			{
				return this._iSPASS;
			}
			set
			{
				this._iSPASS = value;
			}
		}
		
		private DateTime? _dEL_TIME;
		public virtual DateTime? DEL_TIME
		{
			get
			{
				return this._dEL_TIME;
			}
			set
			{
				this._dEL_TIME = value;
			}
		}
		
	}
}
#pragma warning restore 1591
