#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class FORM_TEMPLATE_EXPRESSION
	{
		private int _tEMPLATE_EXPRESSION_ID;
		public virtual int TEMPLATE_EXPRESSION_ID
		{
			get
			{
				return this._tEMPLATE_EXPRESSION_ID;
			}
			set
			{
				this._tEMPLATE_EXPRESSION_ID = value;
			}
		}
		
		private int _tEMPLATE_ID;
		public virtual int TEMPLATE_ID
		{
			get
			{
				return this._tEMPLATE_ID;
			}
			set
			{
				this._tEMPLATE_ID = value;
			}
		}
		
		private string _tEMPLATE_EXPRESSION_NAME;
		public virtual string TEMPLATE_EXPRESSION_NAME
		{
			get
			{
				return this._tEMPLATE_EXPRESSION_NAME;
			}
			set
			{
				this._tEMPLATE_EXPRESSION_NAME = value;
			}
		}
		
		private string _eXPRESSION;
		public virtual string EXPRESSION
		{
			get
			{
				return this._eXPRESSION;
			}
			set
			{
				this._eXPRESSION = value;
			}
		}
		
		private int _eXECUTE_ORDER;
		public virtual int EXECUTE_ORDER
		{
			get
			{
				return this._eXECUTE_ORDER;
			}
			set
			{
				this._eXECUTE_ORDER = value;
			}
		}
		
		private bool _iSFINALSCORE;
		public virtual bool ISFINALSCORE
		{
			get
			{
				return this._iSFINALSCORE;
			}
			set
			{
				this._iSFINALSCORE = value;
			}
		}
		
		private bool _aLLOWUSERDEFINE;
		public virtual bool ALLOWUSERDEFINE
		{
			get
			{
				return this._aLLOWUSERDEFINE;
			}
			set
			{
				this._aLLOWUSERDEFINE = value;
			}
		}
		
	}
}
#pragma warning restore 1591
