#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class FORM_TODO_LIST
	{
		private int _tODOLISTID;
		public virtual int TODOLISTID
		{
			get
			{
				return this._tODOLISTID;
			}
			set
			{
				this._tODOLISTID = value;
			}
		}
		
		private string _eDUTERMID;
		public virtual string EDUTERMID
		{
			get
			{
				return this._eDUTERMID;
			}
			set
			{
				this._eDUTERMID = value;
			}
		}
		
		private int? _tEMPLATE_ID;
		public virtual int? TEMPLATE_ID
		{
			get
			{
				return this._tEMPLATE_ID;
			}
			set
			{
				this._tEMPLATE_ID = value;
			}
		}
		
		private DateTime? _bEGIN_TIME;
		public virtual DateTime? BEGIN_TIME
		{
			get
			{
				return this._bEGIN_TIME;
			}
			set
			{
				this._bEGIN_TIME = value;
			}
		}
		
		private DateTime? _eND_TIME;
		public virtual DateTime? END_TIME
		{
			get
			{
				return this._eND_TIME;
			}
			set
			{
				this._eND_TIME = value;
			}
		}
		
	}
}
#pragma warning restore 1591
