#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMUH.iKASAWebApi.DomainModel.Entities;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class FORM_TEMPLATE_SUBMIT_SQL
	{
		private int _tEMPLATE_ID;
		public virtual int TEMPLATE_ID
		{
			get
			{
				return this._tEMPLATE_ID;
			}
			set
			{
				this._tEMPLATE_ID = value;
			}
		}
		
		private string _kEY;
		public virtual string KEY
		{
			get
			{
				return this._kEY;
			}
			set
			{
				this._kEY = value;
			}
		}
		
		private string _sOURCEREFSTATEMENT;
		public virtual string SOURCEREFSTATEMENT
		{
			get
			{
				return this._sOURCEREFSTATEMENT;
			}
			set
			{
				this._sOURCEREFSTATEMENT = value;
			}
		}
		
		private bool _eXECUTE_FIRST_TIME;
		public virtual bool EXECUTE_FIRST_TIME
		{
			get
			{
				return this._eXECUTE_FIRST_TIME;
			}
			set
			{
				this._eXECUTE_FIRST_TIME = value;
			}
		}
		
		private FORM_TEMPLATE _fORM_TEMPLATE;
		public virtual FORM_TEMPLATE FORM_TEMPLATE
		{
			get
			{
				return this._fORM_TEMPLATE;
			}
			set
			{
				this._fORM_TEMPLATE = value;
			}
		}
		
	}
}
#pragma warning restore 1591
