#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class GOODVSDATUM
	{
		private int _序號;
		public virtual int 序號
		{
			get
			{
				return this._序號;
			}
			set
			{
				this._序號 = value;
			}
		}
		
		private string _分類;
		public virtual string 分類
		{
			get
			{
				return this._分類;
			}
			set
			{
				this._分類 = value;
			}
		}
		
		private string _部門名稱;
		public virtual string 部門名稱
		{
			get
			{
				return this._部門名稱;
			}
			set
			{
				this._部門名稱 = value;
			}
		}
		
		private string _編制單位;
		public virtual string 編制單位
		{
			get
			{
				return this._編制單位;
			}
			set
			{
				this._編制單位 = value;
			}
		}
		
		private string _員工編號;
		public virtual string 員工編號
		{
			get
			{
				return this._員工編號;
			}
			set
			{
				this._員工編號 = value;
			}
		}
		
		private string _員工姓名;
		public virtual string 員工姓名
		{
			get
			{
				return this._員工姓名;
			}
			set
			{
				this._員工姓名 = value;
			}
		}
		
		private decimal _總分FINAL;
		public virtual decimal 總分FINAL
		{
			get
			{
				return this._總分FINAL;
			}
			set
			{
				this._總分FINAL = value;
			}
		}
		
		private int _分數轉換;
		public virtual int 分數轉換
		{
			get
			{
				return this._分數轉換;
			}
			set
			{
				this._分數轉換 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
