#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class GOODVSDATADE
	{
		private string _期別;
		public virtual string 期別
		{
			get
			{
				return this._期別;
			}
			set
			{
				this._期別 = value;
			}
		}
		
		private string _科別;
		public virtual string 科別
		{
			get
			{
				return this._科別;
			}
			set
			{
				this._科別 = value;
			}
		}
		
		private string _臨床指導老師;
		public virtual string 臨床指導老師
		{
			get
			{
				return this._臨床指導老師;
			}
			set
			{
				this._臨床指導老師 = value;
			}
		}
		
		private int? _填寫人數;
		public virtual int? 填寫人數
		{
			get
			{
				return this._填寫人數;
			}
			set
			{
				this._填寫人數 = value;
			}
		}
		
		private decimal? _教師總滿意度;
		public virtual decimal? 教師總滿意度
		{
			get
			{
				return this._教師總滿意度;
			}
			set
			{
				this._教師總滿意度 = value;
			}
		}
		
		private string _教師提供鼓勵支持之學習氣氛;
		public virtual string 教師提供鼓勵支持之學習氣氛
		{
			get
			{
				return this._教師提供鼓勵支持之學習氣氛;
			}
			set
			{
				this._教師提供鼓勵支持之學習氣氛 = value;
			}
		}
		
		private string _教師給予清楚合理的學習目標;
		public virtual string 教師給予清楚合理的學習目標
		{
			get
			{
				return this._教師給予清楚合理的學習目標;
			}
			set
			{
				this._教師給予清楚合理的學習目標 = value;
			}
		}
		
		private string _教師給予明確回饋與改善建議;
		public virtual string 教師給予明確回饋與改善建議
		{
			get
			{
				return this._教師給予明確回饋與改善建議;
			}
			set
			{
				this._教師給予明確回饋與改善建議 = value;
			}
		}
		
		private string _教師具教學熱忱且願意付出時間從事教學;
		public virtual string 教師具教學熱忱且願意付出時間從事教學
		{
			get
			{
				return this._教師具教學熱忱且願意付出時間從事教學;
			}
			set
			{
				this._教師具教學熱忱且願意付出時間從事教學 = value;
			}
		}
		
		private string _教師展現臨床醫療專業能力;
		public virtual string 教師展現臨床醫療專業能力
		{
			get
			{
				return this._教師展現臨床醫療專業能力;
			}
			set
			{
				this._教師展現臨床醫療專業能力 = value;
			}
		}
		
		private string _職編;
		public virtual string 職編
		{
			get
			{
				return this._職編;
			}
			set
			{
				this._職編 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
