#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class HEALTEACHTIMERATE
	{
		private int _sETTINGID;
		public virtual int SETTINGID
		{
			get
			{
				return this._sETTINGID;
			}
			set
			{
				this._sETTINGID = value;
			}
		}
		
		private string _aCTTYPE;
		public virtual string ACTTYPE
		{
			get
			{
				return this._aCTTYPE;
			}
			set
			{
				this._aCTTYPE = value;
			}
		}
		
		private int? _rATE1;
		public virtual int? RATE1
		{
			get
			{
				return this._rATE1;
			}
			set
			{
				this._rATE1 = value;
			}
		}
		
		private int? _rATE2;
		public virtual int? RATE2
		{
			get
			{
				return this._rATE2;
			}
			set
			{
				this._rATE2 = value;
			}
		}
		
		private int? _wEEKLIMIT;
		public virtual int? WEEKLIMIT
		{
			get
			{
				return this._wEEKLIMIT;
			}
			set
			{
				this._wEEKLIMIT = value;
			}
		}
		
	}
}
#pragma warning restore 1591
