#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class HEALTEACHTIME
	{
		private string _eMPCODE;
		public virtual string EMPCODE
		{
			get
			{
				return this._eMPCODE;
			}
			set
			{
				this._eMPCODE = value;
			}
		}
		
		private DateTime _dATADATE;
		public virtual DateTime DATADATE
		{
			get
			{
				return this._dATADATE;
			}
			set
			{
				this._dATADATE = value;
			}
		}
		
		private string _dEPTCODE;
		public virtual string DEPTCODE
		{
			get
			{
				return this._dEPTCODE;
			}
			set
			{
				this._dEPTCODE = value;
			}
		}
		
		private string _aCTTYPE;
		public virtual string ACTTYPE
		{
			get
			{
				return this._aCTTYPE;
			}
			set
			{
				this._aCTTYPE = value;
			}
		}
		
		private string _tARGETTYPE;
		public virtual string TARGETTYPE
		{
			get
			{
				return this._tARGETTYPE;
			}
			set
			{
				this._tARGETTYPE = value;
			}
		}
		
		private decimal? _tEACHTIME;
		public virtual decimal? TEACHTIME
		{
			get
			{
				return this._tEACHTIME;
			}
			set
			{
				this._tEACHTIME = value;
			}
		}
		
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _hOSPCODE;
		public virtual string HOSPCODE
		{
			get
			{
				return this._hOSPCODE;
			}
			set
			{
				this._hOSPCODE = value;
			}
		}
		
		private string _cREATER;
		public virtual string CREATER
		{
			get
			{
				return this._cREATER;
			}
			set
			{
				this._cREATER = value;
			}
		}
		
		private DateTime? _cREATETIME;
		public virtual DateTime? CREATETIME
		{
			get
			{
				return this._cREATETIME;
			}
			set
			{
				this._cREATETIME = value;
			}
		}
		
	}
}
#pragma warning restore 1591
