#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class IKASA_MENU
	{
		private string _mENUID;
		public virtual string MENUID
		{
			get
			{
				return this._mENUID;
			}
			set
			{
				this._mENUID = value;
			}
		}
		
		private string _mENUTEXT;
		public virtual string MENUTEXT
		{
			get
			{
				return this._mENUTEXT;
			}
			set
			{
				this._mENUTEXT = value;
			}
		}
		
		private string _bGCOLOR;
		public virtual string BGCOLOR
		{
			get
			{
				return this._bGCOLOR;
			}
			set
			{
				this._bGCOLOR = value;
			}
		}
		
		private string _fONTCOLOR;
		public virtual string FONTCOLOR
		{
			get
			{
				return this._fONTCOLOR;
			}
			set
			{
				this._fONTCOLOR = value;
			}
		}
		
		private string _pARENTMENUID;
		public virtual string PARENTMENUID
		{
			get
			{
				return this._pARENTMENUID;
			}
			set
			{
				this._pARENTMENUID = value;
			}
		}
		
		private string _hINTTEXT;
		public virtual string HINTTEXT
		{
			get
			{
				return this._hINTTEXT;
			}
			set
			{
				this._hINTTEXT = value;
			}
		}
		
		private string _rEMARK;
		public virtual string REMARK
		{
			get
			{
				return this._rEMARK;
			}
			set
			{
				this._rEMARK = value;
			}
		}
		
		private DateTime? _eNABLEDATE;
		public virtual DateTime? ENABLEDATE
		{
			get
			{
				return this._eNABLEDATE;
			}
			set
			{
				this._eNABLEDATE = value;
			}
		}
		
		private DateTime? _dISABLEDATE;
		public virtual DateTime? DISABLEDATE
		{
			get
			{
				return this._dISABLEDATE;
			}
			set
			{
				this._dISABLEDATE = value;
			}
		}
		
		private string _iSSHOW;
		public virtual string ISSHOW
		{
			get
			{
				return this._iSSHOW;
			}
			set
			{
				this._iSSHOW = value;
			}
		}
		
		private string _fRAMEURL;
		public virtual string FRAMEURL
		{
			get
			{
				return this._fRAMEURL;
			}
			set
			{
				this._fRAMEURL = value;
			}
		}
		
		private int? _dISPLAYORDER;
		public virtual int? DISPLAYORDER
		{
			get
			{
				return this._dISPLAYORDER;
			}
			set
			{
				this._dISPLAYORDER = value;
			}
		}
		
	}
}
#pragma warning restore 1591
