#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMUH.iKASAWebApi.DomainModel.Entities;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class IKASA_OSCEEXAMSTAGE
	{
		private string _eXAMID;
		public virtual string EXAMID
		{
			get
			{
				return this._eXAMID;
			}
			set
			{
				this._eXAMID = value;
			}
		}
		
		private int _sTAGENO;
		public virtual int STAGENO
		{
			get
			{
				return this._sTAGENO;
			}
			set
			{
				this._sTAGENO = value;
			}
		}
		
		private string _sTAGENAME;
		public virtual string STAGENAME
		{
			get
			{
				return this._sTAGENAME;
			}
			set
			{
				this._sTAGENAME = value;
			}
		}
		
		private decimal? _pASSSCORE;
		public virtual decimal? PASSSCORE
		{
			get
			{
				return this._pASSSCORE;
			}
			set
			{
				this._pASSSCORE = value;
			}
		}
		
		private IKASA_OSCEEXAM _iKASA_OSCEEXAM;
		public virtual IKASA_OSCEEXAM IKASA_OSCEEXAM
		{
			get
			{
				return this._iKASA_OSCEEXAM;
			}
			set
			{
				this._iKASA_OSCEEXAM = value;
			}
		}
		
	}
}
#pragma warning restore 1591
