#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class IKASA_MENUPARAM
	{
		private string _mENUID;
		public virtual string MENUID
		{
			get
			{
				return this._mENUID;
			}
			set
			{
				this._mENUID = value;
			}
		}
		
		private string _pARAMNAME;
		public virtual string PARAMNAME
		{
			get
			{
				return this._pARAMNAME;
			}
			set
			{
				this._pARAMNAME = value;
			}
		}
		
		private string _pARAMVALUE;
		public virtual string PARAMVALUE
		{
			get
			{
				return this._pARAMVALUE;
			}
			set
			{
				this._pARAMVALUE = value;
			}
		}
		
	}
}
#pragma warning restore 1591
