#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class IKASA_ERCASE
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _eMPCODE;
		public virtual string EMPCODE
		{
			get
			{
				return this._eMPCODE;
			}
			set
			{
				this._eMPCODE = value;
			}
		}
		
		private string _sOURCE_SYSTEM;
		public virtual string SOURCE_SYSTEM
		{
			get
			{
				return this._sOURCE_SYSTEM;
			}
			set
			{
				this._sOURCE_SYSTEM = value;
			}
		}
		
		private string _sOURCE_ID;
		public virtual string SOURCE_ID
		{
			get
			{
				return this._sOURCE_ID;
			}
			set
			{
				this._sOURCE_ID = value;
			}
		}
		
		private string _cHART_NO;
		public virtual string CHART_NO
		{
			get
			{
				return this._cHART_NO;
			}
			set
			{
				this._cHART_NO = value;
			}
		}
		
		private string _iCD_CODE;
		public virtual string ICD_CODE
		{
			get
			{
				return this._iCD_CODE;
			}
			set
			{
				this._iCD_CODE = value;
			}
		}
		
		private string _dISEASE_CLASS;
		public virtual string DISEASE_CLASS
		{
			get
			{
				return this._dISEASE_CLASS;
			}
			set
			{
				this._dISEASE_CLASS = value;
			}
		}
		
		private string _dEPT_CODE;
		public virtual string DEPT_CODE
		{
			get
			{
				return this._dEPT_CODE;
			}
			set
			{
				this._dEPT_CODE = value;
			}
		}
		
		private DateTime? _iN_DATE;
		public virtual DateTime? IN_DATE
		{
			get
			{
				return this._iN_DATE;
			}
			set
			{
				this._iN_DATE = value;
			}
		}
		
		private string _pROCEDURE;
		public virtual string PROCEDURE
		{
			get
			{
				return this._pROCEDURE;
			}
			set
			{
				this._pROCEDURE = value;
			}
		}
		
		private string _sTATUS;
		public virtual string STATUS
		{
			get
			{
				return this._sTATUS;
			}
			set
			{
				this._sTATUS = value;
			}
		}
		
		private string _sIGN_TEACHER;
		public virtual string SIGN_TEACHER
		{
			get
			{
				return this._sIGN_TEACHER;
			}
			set
			{
				this._sIGN_TEACHER = value;
			}
		}
		
		private DateTime? _sIGN_DATE;
		public virtual DateTime? SIGN_DATE
		{
			get
			{
				return this._sIGN_DATE;
			}
			set
			{
				this._sIGN_DATE = value;
			}
		}
		
		private string _sIGN_NOTE;
		public virtual string SIGN_NOTE
		{
			get
			{
				return this._sIGN_NOTE;
			}
			set
			{
				this._sIGN_NOTE = value;
			}
		}
		
		private string _iCD_NAME;
		public virtual string ICD_NAME
		{
			get
			{
				return this._iCD_NAME;
			}
			set
			{
				this._iCD_NAME = value;
			}
		}
		
		private string _dEPT_NAME;
		public virtual string DEPT_NAME
		{
			get
			{
				return this._dEPT_NAME;
			}
			set
			{
				this._dEPT_NAME = value;
			}
		}
		
		private int? _dOPSID;
		public virtual int? DOPSID
		{
			get
			{
				return this._dOPSID;
			}
			set
			{
				this._dOPSID = value;
			}
		}
		
		private int? _ePAID;
		public virtual int? EPAID
		{
			get
			{
				return this._ePAID;
			}
			set
			{
				this._ePAID = value;
			}
		}
		
	}
}
#pragma warning restore 1591
