#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class IKASA_IPDDATACOUNT
	{
		private string _eMPCODE;
		public virtual string EMPCODE
		{
			get
			{
				return this._eMPCODE;
			}
			set
			{
				this._eMPCODE = value;
			}
		}
		
		private DateTime _sDATE;
		public virtual DateTime SDATE
		{
			get
			{
				return this._sDATE;
			}
			set
			{
				this._sDATE = value;
			}
		}
		
		private DateTime _eDATE;
		public virtual DateTime EDATE
		{
			get
			{
				return this._eDATE;
			}
			set
			{
				this._eDATE = value;
			}
		}
		
		private int? _iPDNOTECOUNT;
		public virtual int? IPDNOTECOUNT
		{
			get
			{
				return this._iPDNOTECOUNT;
			}
			set
			{
				this._iPDNOTECOUNT = value;
			}
		}
		
		private int? _pRIMARYCARECOUNT;
		public virtual int? PRIMARYCARECOUNT
		{
			get
			{
				return this._pRIMARYCARECOUNT;
			}
			set
			{
				this._pRIMARYCARECOUNT = value;
			}
		}
		
		private decimal? _wORKHOUR;
		public virtual decimal? WORKHOUR
		{
			get
			{
				return this._wORKHOUR;
			}
			set
			{
				this._wORKHOUR = value;
			}
		}
		
	}
}
#pragma warning restore 1591
