#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class IMPORTTEMP
	{
		private string _姓名;
		public virtual string 姓名
		{
			get
			{
				return this._姓名;
			}
			set
			{
				this._姓名 = value;
			}
		}
		
		private string _職編;
		public virtual string 職編
		{
			get
			{
				return this._職編;
			}
			set
			{
				this._職編 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
