#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class LOGINLOG
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _eMPCODE;
		public virtual string EMPCODE
		{
			get
			{
				return this._eMPCODE;
			}
			set
			{
				this._eMPCODE = value;
			}
		}
		
		private DateTime _lOGINTIME;
		public virtual DateTime LOGINTIME
		{
			get
			{
				return this._lOGINTIME;
			}
			set
			{
				this._lOGINTIME = value;
			}
		}
		
		private bool _iSSUCCESS;
		public virtual bool ISSUCCESS
		{
			get
			{
				return this._iSSUCCESS;
			}
			set
			{
				this._iSSUCCESS = value;
			}
		}
		
		private string _lOGINIP;
		public virtual string LOGINIP
		{
			get
			{
				return this._lOGINIP;
			}
			set
			{
				this._lOGINIP = value;
			}
		}
		
	}
}
#pragma warning restore 1591
