#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class MEDICALVOTELIST
	{
		private string _eMPCODE;
		public virtual string EMPCODE
		{
			get
			{
				return this._eMPCODE;
			}
			set
			{
				this._eMPCODE = value;
			}
		}
		
		private string _nAME;
		public virtual string NAME
		{
			get
			{
				return this._nAME;
			}
			set
			{
				this._nAME = value;
			}
		}
		
		private string _dISPLAYNAME;
		public virtual string DISPLAYNAME
		{
			get
			{
				return this._dISPLAYNAME;
			}
			set
			{
				this._dISPLAYNAME = value;
			}
		}
		
		private DateTime _sDATE;
		public virtual DateTime SDATE
		{
			get
			{
				return this._sDATE;
			}
			set
			{
				this._sDATE = value;
			}
		}
		
		private DateTime? _eDATE;
		public virtual DateTime? EDATE
		{
			get
			{
				return this._eDATE;
			}
			set
			{
				this._eDATE = value;
			}
		}
		
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _dEPTCODE;
		public virtual string DEPTCODE
		{
			get
			{
				return this._dEPTCODE;
			}
			set
			{
				this._dEPTCODE = value;
			}
		}
		
		private string _hOSPCODE;
		public virtual string HOSPCODE
		{
			get
			{
				return this._hOSPCODE;
			}
			set
			{
				this._hOSPCODE = value;
			}
		}
		
	}
}
#pragma warning restore 1591
