#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class MEDICALTEACHPOINT
	{
		private string _eMPCODE;
		public virtual string EMPCODE
		{
			get
			{
				return this._eMPCODE;
			}
			set
			{
				this._eMPCODE = value;
			}
		}
		
		private DateTime _dATADATE;
		public virtual DateTime DATADATE
		{
			get
			{
				return this._dATADATE;
			}
			set
			{
				this._dATADATE = value;
			}
		}
		
		private string _dEPTCODE;
		public virtual string DEPTCODE
		{
			get
			{
				return this._dEPTCODE;
			}
			set
			{
				this._dEPTCODE = value;
			}
		}
		
		private decimal? _bASETEACHPOINT;
		public virtual decimal? BASETEACHPOINT
		{
			get
			{
				return this._bASETEACHPOINT;
			}
			set
			{
				this._bASETEACHPOINT = value;
			}
		}
		
		private string _iD;
		public virtual string ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _hOSPCODE;
		public virtual string HOSPCODE
		{
			get
			{
				return this._hOSPCODE;
			}
			set
			{
				this._hOSPCODE = value;
			}
		}
		
		private string _cREATER;
		public virtual string CREATER
		{
			get
			{
				return this._cREATER;
			}
			set
			{
				this._cREATER = value;
			}
		}
		
		private DateTime? _cREATETIME;
		public virtual DateTime? CREATETIME
		{
			get
			{
				return this._cREATETIME;
			}
			set
			{
				this._cREATETIME = value;
			}
		}
		
		private decimal? _bASERATIO;
		public virtual decimal? BASERATIO
		{
			get
			{
				return this._bASERATIO;
			}
			set
			{
				this._bASERATIO = value;
			}
		}
		
		private decimal? _tEACHERPOINT;
		public virtual decimal? TEACHERPOINT
		{
			get
			{
				return this._tEACHERPOINT;
			}
			set
			{
				this._tEACHERPOINT = value;
			}
		}
		
		private decimal? _sTRAINPOINT;
		public virtual decimal? STRAINPOINT
		{
			get
			{
				return this._sTRAINPOINT;
			}
			set
			{
				this._sTRAINPOINT = value;
			}
		}
		
		private string _rEMARK;
		public virtual string REMARK
		{
			get
			{
				return this._rEMARK;
			}
			set
			{
				this._rEMARK = value;
			}
		}
		
		private string _rEVIEWSTATUS;
		public virtual string REVIEWSTATUS
		{
			get
			{
				return this._rEVIEWSTATUS;
			}
			set
			{
				this._rEVIEWSTATUS = value;
			}
		}
		
	}
}
#pragma warning restore 1591
