#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class MONTHLYTEACHPOINTCALCDATUM
	{
		private DateTime _cALDATE;
		public virtual DateTime CALDATE
		{
			get
			{
				return this._cALDATE;
			}
			set
			{
				this._cALDATE = value;
			}
		}
		
		private string _eMPCODE;
		public virtual string EMPCODE
		{
			get
			{
				return this._eMPCODE;
			}
			set
			{
				this._eMPCODE = value;
			}
		}
		
		private DateTime _sDATE;
		public virtual DateTime SDATE
		{
			get
			{
				return this._sDATE;
			}
			set
			{
				this._sDATE = value;
			}
		}
		
		private DateTime _eDATE;
		public virtual DateTime EDATE
		{
			get
			{
				return this._eDATE;
			}
			set
			{
				this._eDATE = value;
			}
		}
		
		private bool _iSLATEST;
		public virtual bool ISLATEST
		{
			get
			{
				return this._iSLATEST;
			}
			set
			{
				this._iSLATEST = value;
			}
		}
		
		private string _pARAM0;
		public virtual string PARAM0
		{
			get
			{
				return this._pARAM0;
			}
			set
			{
				this._pARAM0 = value;
			}
		}
		
		private string _pARAM1;
		public virtual string PARAM1
		{
			get
			{
				return this._pARAM1;
			}
			set
			{
				this._pARAM1 = value;
			}
		}
		
		private string _pARAM2;
		public virtual string PARAM2
		{
			get
			{
				return this._pARAM2;
			}
			set
			{
				this._pARAM2 = value;
			}
		}
		
		private string _pARAM3;
		public virtual string PARAM3
		{
			get
			{
				return this._pARAM3;
			}
			set
			{
				this._pARAM3 = value;
			}
		}
		
		private string _pARAM4;
		public virtual string PARAM4
		{
			get
			{
				return this._pARAM4;
			}
			set
			{
				this._pARAM4 = value;
			}
		}
		
		private string _pARAM5;
		public virtual string PARAM5
		{
			get
			{
				return this._pARAM5;
			}
			set
			{
				this._pARAM5 = value;
			}
		}
		
		private string _pARAM6;
		public virtual string PARAM6
		{
			get
			{
				return this._pARAM6;
			}
			set
			{
				this._pARAM6 = value;
			}
		}
		
		private string _pARAM7;
		public virtual string PARAM7
		{
			get
			{
				return this._pARAM7;
			}
			set
			{
				this._pARAM7 = value;
			}
		}
		
		private string _pARAM8;
		public virtual string PARAM8
		{
			get
			{
				return this._pARAM8;
			}
			set
			{
				this._pARAM8 = value;
			}
		}
		
		private string _pARAM9;
		public virtual string PARAM9
		{
			get
			{
				return this._pARAM9;
			}
			set
			{
				this._pARAM9 = value;
			}
		}
		
		private string _pARAM10;
		public virtual string PARAM10
		{
			get
			{
				return this._pARAM10;
			}
			set
			{
				this._pARAM10 = value;
			}
		}
		
		private string _pARAM11;
		public virtual string PARAM11
		{
			get
			{
				return this._pARAM11;
			}
			set
			{
				this._pARAM11 = value;
			}
		}
		
		private string _pARAM12;
		public virtual string PARAM12
		{
			get
			{
				return this._pARAM12;
			}
			set
			{
				this._pARAM12 = value;
			}
		}
		
		private string _pARAM13;
		public virtual string PARAM13
		{
			get
			{
				return this._pARAM13;
			}
			set
			{
				this._pARAM13 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
