#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class NNOTE
	{
		private string _nNOTEID;
		public virtual string NNOTEID
		{
			get
			{
				return this._nNOTEID;
			}
			set
			{
				this._nNOTEID = value;
			}
		}
		
		private string _nURSINGNOTECODE;
		public virtual string NURSINGNOTECODE
		{
			get
			{
				return this._nURSINGNOTECODE;
			}
			set
			{
				this._nURSINGNOTECODE = value;
			}
		}
		
		private string _vERSIONCODE;
		public virtual string VERSIONCODE
		{
			get
			{
				return this._vERSIONCODE;
			}
			set
			{
				this._vERSIONCODE = value;
			}
		}
		
		private DateTime? _nOTEDATE;
		public virtual DateTime? NOTEDATE
		{
			get
			{
				return this._nOTEDATE;
			}
			set
			{
				this._nOTEDATE = value;
			}
		}
		
		private string _cHART_NO;
		public virtual string CHART_NO
		{
			get
			{
				return this._cHART_NO;
			}
			set
			{
				this._cHART_NO = value;
			}
		}
		
		private string _pATIENT_NAME;
		public virtual string PATIENT_NAME
		{
			get
			{
				return this._pATIENT_NAME;
			}
			set
			{
				this._pATIENT_NAME = value;
			}
		}
		
		private string _cREATER;
		public virtual string CREATER
		{
			get
			{
				return this._cREATER;
			}
			set
			{
				this._cREATER = value;
			}
		}
		
		private string _cREATER_NAME;
		public virtual string CREATER_NAME
		{
			get
			{
				return this._cREATER_NAME;
			}
			set
			{
				this._cREATER_NAME = value;
			}
		}
		
		private string _iNHOSPID;
		public virtual string INHOSPID
		{
			get
			{
				return this._iNHOSPID;
			}
			set
			{
				this._iNHOSPID = value;
			}
		}
		
		private DateTime? _uPDATEDATE;
		public virtual DateTime? UPDATEDATE
		{
			get
			{
				return this._uPDATEDATE;
			}
			set
			{
				this._uPDATEDATE = value;
			}
		}
		
	}
}
#pragma warning restore 1591
