#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class NURSELIST
	{
		private string _序號;
		public virtual string 序號
		{
			get
			{
				return this._序號;
			}
			set
			{
				this._序號 = value;
			}
		}
		
		private string _部門名稱;
		public virtual string 部門名稱
		{
			get
			{
				return this._部門名稱;
			}
			set
			{
				this._部門名稱 = value;
			}
		}
		
		private string _單位;
		public virtual string 單位
		{
			get
			{
				return this._單位;
			}
			set
			{
				this._單位 = value;
			}
		}
		
		private string _員工編號;
		public virtual string 員工編號
		{
			get
			{
				return this._員工編號;
			}
			set
			{
				this._員工編號 = value;
			}
		}
		
		private string _員工姓名;
		public virtual string 員工姓名
		{
			get
			{
				return this._員工姓名;
			}
			set
			{
				this._員工姓名 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
