#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class OSCEBLOCKTIME
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _eMPCODE;
		public virtual string EMPCODE
		{
			get
			{
				return this._eMPCODE;
			}
			set
			{
				this._eMPCODE = value;
			}
		}
		
		private string _cLASSNAME;
		public virtual string CLASSNAME
		{
			get
			{
				return this._cLASSNAME;
			}
			set
			{
				this._cLASSNAME = value;
			}
		}
		
		private DateTime? _cLASSDATE;
		public virtual DateTime? CLASSDATE
		{
			get
			{
				return this._cLASSDATE;
			}
			set
			{
				this._cLASSDATE = value;
			}
		}
		
		private decimal? _tRAININGTIME;
		public virtual decimal? TRAININGTIME
		{
			get
			{
				return this._tRAININGTIME;
			}
			set
			{
				this._tRAININGTIME = value;
			}
		}
		
		private string _cREATER;
		public virtual string CREATER
		{
			get
			{
				return this._cREATER;
			}
			set
			{
				this._cREATER = value;
			}
		}
		
		private DateTime? _cREATEDATE;
		public virtual DateTime? CREATEDATE
		{
			get
			{
				return this._cREATEDATE;
			}
			set
			{
				this._cREATEDATE = value;
			}
		}
		
		private string _sTATUS;
		public virtual string STATUS
		{
			get
			{
				return this._sTATUS;
			}
			set
			{
				this._sTATUS = value;
			}
		}
		
	}
}
#pragma warning restore 1591
