#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMUH.iKASAWebApi.DomainModel.Entities;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class PASSPORTCHECKITEM
	{
		private int _iTEMCODE;
		public virtual int ITEMCODE
		{
			get
			{
				return this._iTEMCODE;
			}
			set
			{
				this._iTEMCODE = value;
			}
		}
		
		private string _iTEMNAME;
		public virtual string ITEMNAME
		{
			get
			{
				return this._iTEMNAME;
			}
			set
			{
				this._iTEMNAME = value;
			}
		}
		
		private string _cREATEDMAN;
		public virtual string CREATEDMAN
		{
			get
			{
				return this._cREATEDMAN;
			}
			set
			{
				this._cREATEDMAN = value;
			}
		}
		
		private DateTime? _cREATEDTIME;
		public virtual DateTime? CREATEDTIME
		{
			get
			{
				return this._cREATEDTIME;
			}
			set
			{
				this._cREATEDTIME = value;
			}
		}
		
		private string _tOPTEAMCODE;
		public virtual string TOPTEAMCODE
		{
			get
			{
				return this._tOPTEAMCODE;
			}
			set
			{
				this._tOPTEAMCODE = value;
			}
		}
		
		private int _iTEMGROUP;
		public virtual int ITEMGROUP
		{
			get
			{
				return this._iTEMGROUP;
			}
			set
			{
				this._iTEMGROUP = value;
			}
		}
		
		private IList<PASSPORTSTUDENTAPPLICATIONITEMFAILLOG> _pASSPORTSTUDENTAPPLICATIONITEMFAILLOGs = new List<PASSPORTSTUDENTAPPLICATIONITEMFAILLOG>();
		public virtual IList<PASSPORTSTUDENTAPPLICATIONITEMFAILLOG> PASSPORTSTUDENTAPPLICATIONITEMFAILLOGs
		{
			get
			{
				return this._pASSPORTSTUDENTAPPLICATIONITEMFAILLOGs;
			}
		}
		
		private IList<PASSPORTSTUDENTAPPLICATIONITEM_BK2> _pASSPORTSTUDENTAPPLICATIONITEM_BK2 = new List<PASSPORTSTUDENTAPPLICATIONITEM_BK2>();
		public virtual IList<PASSPORTSTUDENTAPPLICATIONITEM_BK2> PASSPORTSTUDENTAPPLICATIONITEM_BK2
		{
			get
			{
				return this._pASSPORTSTUDENTAPPLICATIONITEM_BK2;
			}
		}
		
		private IList<PASSPORTSTUDENTAPPLICATIONITEM_BK> _pASSPORTSTUDENTAPPLICATIONITEM_BKs = new List<PASSPORTSTUDENTAPPLICATIONITEM_BK>();
		public virtual IList<PASSPORTSTUDENTAPPLICATIONITEM_BK> PASSPORTSTUDENTAPPLICATIONITEM_BKs
		{
			get
			{
				return this._pASSPORTSTUDENTAPPLICATIONITEM_BKs;
			}
		}
		
		private IList<PASSPORTSTUDENTAPPLICATIONITEM> _pASSPORTSTUDENTAPPLICATIONITEMs = new List<PASSPORTSTUDENTAPPLICATIONITEM>();
		public virtual IList<PASSPORTSTUDENTAPPLICATIONITEM> PASSPORTSTUDENTAPPLICATIONITEMs
		{
			get
			{
				return this._pASSPORTSTUDENTAPPLICATIONITEMs;
			}
		}
		
		private IList<PASSPORTJOBTITLEITEM_BK> _pASSPORTJOBTITLEITEM_BKs = new List<PASSPORTJOBTITLEITEM_BK>();
		public virtual IList<PASSPORTJOBTITLEITEM_BK> PASSPORTJOBTITLEITEM_BKs
		{
			get
			{
				return this._pASSPORTJOBTITLEITEM_BKs;
			}
		}
		
		private IList<PASSPORTJOBTITLEITEM> _pASSPORTJOBTITLEITEMs = new List<PASSPORTJOBTITLEITEM>();
		public virtual IList<PASSPORTJOBTITLEITEM> PASSPORTJOBTITLEITEMs
		{
			get
			{
				return this._pASSPORTJOBTITLEITEMs;
			}
		}
		
	}
}
#pragma warning restore 1591
