#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class PASSPORTDOCGRADE
	{
		private string _tITLECODE;
		public virtual string TITLECODE
		{
			get
			{
				return this._tITLECODE;
			}
			set
			{
				this._tITLECODE = value;
			}
		}
		
		private int? _gRADE;
		public virtual int? GRADE
		{
			get
			{
				return this._gRADE;
			}
			set
			{
				this._gRADE = value;
			}
		}
		
	}
}
#pragma warning restore 1591
