#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMUH.iKASAWebApi.DomainModel.Entities;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class PASSPORTJOBTITLEITEM
	{
		private string _jOBTITLECODE;
		public virtual string JOBTITLECODE
		{
			get
			{
				return this._jOBTITLECODE;
			}
			set
			{
				this._jOBTITLECODE = value;
			}
		}
		
		private int _iTEMCODE;
		public virtual int ITEMCODE
		{
			get
			{
				return this._iTEMCODE;
			}
			set
			{
				this._iTEMCODE = value;
			}
		}
		
		private string _aUTHORIZELEVEL;
		public virtual string AUTHORIZELEVEL
		{
			get
			{
				return this._aUTHORIZELEVEL;
			}
			set
			{
				this._aUTHORIZELEVEL = value;
			}
		}
		
		private int? _aUTHENTICATEFREQUENCY;
		public virtual int? AUTHENTICATEFREQUENCY
		{
			get
			{
				return this._aUTHENTICATEFREQUENCY;
			}
			set
			{
				this._aUTHENTICATEFREQUENCY = value;
			}
		}
		
		private bool? _iSNEEDFINALCHECK;
		public virtual bool? ISNEEDFINALCHECK
		{
			get
			{
				return this._iSNEEDFINALCHECK;
			}
			set
			{
				this._iSNEEDFINALCHECK = value;
			}
		}
		
		private string _eXAUTHORIZELEVEL;
		public virtual string EXAUTHORIZELEVEL
		{
			get
			{
				return this._eXAUTHORIZELEVEL;
			}
			set
			{
				this._eXAUTHORIZELEVEL = value;
			}
		}
		
		private PASSPORTCHECKITEM _pASSPORTCHECKITEM;
		public virtual PASSPORTCHECKITEM PASSPORTCHECKITEM
		{
			get
			{
				return this._pASSPORTCHECKITEM;
			}
			set
			{
				this._pASSPORTCHECKITEM = value;
			}
		}
		
	}
}
#pragma warning restore 1591
