#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMUH.iKASAWebApi.DomainModel.Entities;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class RECORDINSDET
	{
		private string _iNSTANCEID;
		public virtual string INSTANCEID
		{
			get
			{
				return this._iNSTANCEID;
			}
			set
			{
				this._iNSTANCEID = value;
			}
		}
		
		private string _cONTROLID;
		public virtual string CONTROLID
		{
			get
			{
				return this._cONTROLID;
			}
			set
			{
				this._cONTROLID = value;
			}
		}
		
		private string _cONTROLVALUE;
		public virtual string CONTROLVALUE
		{
			get
			{
				return this._cONTROLVALUE;
			}
			set
			{
				this._cONTROLVALUE = value;
			}
		}
		
		private RECORDINSTANCE _rECORDINSTANCE;
		public virtual RECORDINSTANCE RECORDINSTANCE
		{
			get
			{
				return this._rECORDINSTANCE;
			}
			set
			{
				this._rECORDINSTANCE = value;
			}
		}
		
	}
}
#pragma warning restore 1591
