#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMUH.iKASAWebApi.DomainModel.Entities;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class RECORDINSSIGNIN
	{
		private string _iNSTANCEID;
		public virtual string INSTANCEID
		{
			get
			{
				return this._iNSTANCEID;
			}
			set
			{
				this._iNSTANCEID = value;
			}
		}
		
		private string _eMPCODE;
		public virtual string EMPCODE
		{
			get
			{
				return this._eMPCODE;
			}
			set
			{
				this._eMPCODE = value;
			}
		}
		
		private DateTime? _sIGNTIME;
		public virtual DateTime? SIGNTIME
		{
			get
			{
				return this._sIGNTIME;
			}
			set
			{
				this._sIGNTIME = value;
			}
		}
		
		private string _sIGNPATH;
		public virtual string SIGNPATH
		{
			get
			{
				return this._sIGNPATH;
			}
			set
			{
				this._sIGNPATH = value;
			}
		}
		
		private string _rOLETYPE;
		public virtual string ROLETYPE
		{
			get
			{
				return this._rOLETYPE;
			}
			set
			{
				this._rOLETYPE = value;
			}
		}
		
		private string _tARGETJOB;
		public virtual string TARGETJOB
		{
			get
			{
				return this._tARGETJOB;
			}
			set
			{
				this._tARGETJOB = value;
			}
		}
		
		private RECORDINSTANCE _rECORDINSTANCE;
		public virtual RECORDINSTANCE RECORDINSTANCE
		{
			get
			{
				return this._rECORDINSTANCE;
			}
			set
			{
				this._rECORDINSTANCE = value;
			}
		}
		
	}
}
#pragma warning restore 1591
