#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class RECORDINSTANCEREJECTLOG
	{
		private string _iNSTANCEID;
		public virtual string INSTANCEID
		{
			get
			{
				return this._iNSTANCEID;
			}
			set
			{
				this._iNSTANCEID = value;
			}
		}
		
		private string _eMPCODE;
		public virtual string EMPCODE
		{
			get
			{
				return this._eMPCODE;
			}
			set
			{
				this._eMPCODE = value;
			}
		}
		
		private string _rEJECTREASON;
		public virtual string REJECTREASON
		{
			get
			{
				return this._rEJECTREASON;
			}
			set
			{
				this._rEJECTREASON = value;
			}
		}
		
		private string _oLDSTATUS;
		public virtual string OLDSTATUS
		{
			get
			{
				return this._oLDSTATUS;
			}
			set
			{
				this._oLDSTATUS = value;
			}
		}
		
		private string _nEWSTATUS;
		public virtual string NEWSTATUS
		{
			get
			{
				return this._nEWSTATUS;
			}
			set
			{
				this._nEWSTATUS = value;
			}
		}
		
		private DateTime? _rEJECTTIME;
		public virtual DateTime? REJECTTIME
		{
			get
			{
				return this._rEJECTTIME;
			}
			set
			{
				this._rEJECTTIME = value;
			}
		}
		
		private int _lOGID;
		public virtual int LOGID
		{
			get
			{
				return this._lOGID;
			}
			set
			{
				this._lOGID = value;
			}
		}
		
	}
}
#pragma warning restore 1591
