#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class REPORTDATATEMP
	{
		private string _表單序號;
		public virtual string 表單序號
		{
			get
			{
				return this._表單序號;
			}
			set
			{
				this._表單序號 = value;
			}
		}
		
		private string _填寫人職編;
		public virtual string 填寫人職編
		{
			get
			{
				return this._填寫人職編;
			}
			set
			{
				this._填寫人職編 = value;
			}
		}
		
		private string _填寫人姓名;
		public virtual string 填寫人姓名
		{
			get
			{
				return this._填寫人姓名;
			}
			set
			{
				this._填寫人姓名 = value;
			}
		}
		
		private string _填寫狀態;
		public virtual string 填寫狀態
		{
			get
			{
				return this._填寫狀態;
			}
			set
			{
				this._填寫狀態 = value;
			}
		}
		
		private string _考核對象;
		public virtual string 考核對象
		{
			get
			{
				return this._考核對象;
			}
			set
			{
				this._考核對象 = value;
			}
		}
		
		private string _課程名稱完整;
		public virtual string 課程名稱完整
		{
			get
			{
				return this._課程名稱完整;
			}
			set
			{
				this._課程名稱完整 = value;
			}
		}
		
		private string _受訓院區;
		public virtual string 受訓院區
		{
			get
			{
				return this._受訓院區;
			}
			set
			{
				this._受訓院區 = value;
			}
		}
		
		private string _受訓科別;
		public virtual string 受訓科別
		{
			get
			{
				return this._受訓科別;
			}
			set
			{
				this._受訓科別 = value;
			}
		}
		
		private string _受訓期間;
		public virtual string 受訓期間
		{
			get
			{
				return this._受訓期間;
			}
			set
			{
				this._受訓期間 = value;
			}
		}
		
		private string _vS1;
		public virtual string VS1
		{
			get
			{
				return this._vS1;
			}
			set
			{
				this._vS1 = value;
			}
		}
		
		private string _vS1姓名;
		public virtual string VS1姓名
		{
			get
			{
				return this._vS1姓名;
			}
			set
			{
				this._vS1姓名 = value;
			}
		}
		
		private string _vS1教師提供鼓勵支持之學習氣氛;
		public virtual string VS1教師提供鼓勵支持之學習氣氛
		{
			get
			{
				return this._vS1教師提供鼓勵支持之學習氣氛;
			}
			set
			{
				this._vS1教師提供鼓勵支持之學習氣氛 = value;
			}
		}
		
		private string _vS1教師給予清楚合理的學習目標;
		public virtual string VS1教師給予清楚合理的學習目標
		{
			get
			{
				return this._vS1教師給予清楚合理的學習目標;
			}
			set
			{
				this._vS1教師給予清楚合理的學習目標 = value;
			}
		}
		
		private string _vS1教師給予明確回饋與改善建議;
		public virtual string VS1教師給予明確回饋與改善建議
		{
			get
			{
				return this._vS1教師給予明確回饋與改善建議;
			}
			set
			{
				this._vS1教師給予明確回饋與改善建議 = value;
			}
		}
		
		private string _vS1教師具教學熱忱願意付出時間從事教學上的表現;
		public virtual string VS1教師具教學熱忱願意付出時間從事教學上的表現
		{
			get
			{
				return this._vS1教師具教學熱忱願意付出時間從事教學上的表現;
			}
			set
			{
				this._vS1教師具教學熱忱願意付出時間從事教學上的表現 = value;
			}
		}
		
		private string _vS1教師展現臨床醫療專業能力和行為表現;
		public virtual string VS1教師展現臨床醫療專業能力和行為表現
		{
			get
			{
				return this._vS1教師展現臨床醫療專業能力和行為表現;
			}
			set
			{
				this._vS1教師展現臨床醫療專業能力和行為表現 = value;
			}
		}
		
		private string _vS2;
		public virtual string VS2
		{
			get
			{
				return this._vS2;
			}
			set
			{
				this._vS2 = value;
			}
		}
		
		private string _vS2姓名;
		public virtual string VS2姓名
		{
			get
			{
				return this._vS2姓名;
			}
			set
			{
				this._vS2姓名 = value;
			}
		}
		
		private string _vS2教師提供鼓勵支持之學習氣氛;
		public virtual string VS2教師提供鼓勵支持之學習氣氛
		{
			get
			{
				return this._vS2教師提供鼓勵支持之學習氣氛;
			}
			set
			{
				this._vS2教師提供鼓勵支持之學習氣氛 = value;
			}
		}
		
		private string _vS2教師給予清楚合理的學習目標;
		public virtual string VS2教師給予清楚合理的學習目標
		{
			get
			{
				return this._vS2教師給予清楚合理的學習目標;
			}
			set
			{
				this._vS2教師給予清楚合理的學習目標 = value;
			}
		}
		
		private string _vS2教師給予明確回饋與改善建議;
		public virtual string VS2教師給予明確回饋與改善建議
		{
			get
			{
				return this._vS2教師給予明確回饋與改善建議;
			}
			set
			{
				this._vS2教師給予明確回饋與改善建議 = value;
			}
		}
		
		private string _vS2教師具教學熱忱願意付出時間從事教學上的表現;
		public virtual string VS2教師具教學熱忱願意付出時間從事教學上的表現
		{
			get
			{
				return this._vS2教師具教學熱忱願意付出時間從事教學上的表現;
			}
			set
			{
				this._vS2教師具教學熱忱願意付出時間從事教學上的表現 = value;
			}
		}
		
		private string _vS2教師展現臨床醫療專業能力和行為表現;
		public virtual string VS2教師展現臨床醫療專業能力和行為表現
		{
			get
			{
				return this._vS2教師展現臨床醫療專業能力和行為表現;
			}
			set
			{
				this._vS2教師展現臨床醫療專業能力和行為表現 = value;
			}
		}
		
		private string _r1;
		public virtual string R1
		{
			get
			{
				return this._r1;
			}
			set
			{
				this._r1 = value;
			}
		}
		
		private string _r1姓名;
		public virtual string R1姓名
		{
			get
			{
				return this._r1姓名;
			}
			set
			{
				this._r1姓名 = value;
			}
		}
		
		private string _r1教師提供鼓勵支持之學習氣氛;
		public virtual string R1教師提供鼓勵支持之學習氣氛
		{
			get
			{
				return this._r1教師提供鼓勵支持之學習氣氛;
			}
			set
			{
				this._r1教師提供鼓勵支持之學習氣氛 = value;
			}
		}
		
		private string _r1教師給予清楚合理的學習目標;
		public virtual string R1教師給予清楚合理的學習目標
		{
			get
			{
				return this._r1教師給予清楚合理的學習目標;
			}
			set
			{
				this._r1教師給予清楚合理的學習目標 = value;
			}
		}
		
		private string _r1教師給予明確回饋與改善建議;
		public virtual string R1教師給予明確回饋與改善建議
		{
			get
			{
				return this._r1教師給予明確回饋與改善建議;
			}
			set
			{
				this._r1教師給予明確回饋與改善建議 = value;
			}
		}
		
		private string _r1教師具教學熱忱願意付出時間從事教學上的表現;
		public virtual string R1教師具教學熱忱願意付出時間從事教學上的表現
		{
			get
			{
				return this._r1教師具教學熱忱願意付出時間從事教學上的表現;
			}
			set
			{
				this._r1教師具教學熱忱願意付出時間從事教學上的表現 = value;
			}
		}
		
		private string _r1教師展現臨床醫療專業能力和行為表現;
		public virtual string R1教師展現臨床醫療專業能力和行為表現
		{
			get
			{
				return this._r1教師展現臨床醫療專業能力和行為表現;
			}
			set
			{
				this._r1教師展現臨床醫療專業能力和行為表現 = value;
			}
		}
		
		private string _r2;
		public virtual string R2
		{
			get
			{
				return this._r2;
			}
			set
			{
				this._r2 = value;
			}
		}
		
		private string _r2姓名;
		public virtual string R2姓名
		{
			get
			{
				return this._r2姓名;
			}
			set
			{
				this._r2姓名 = value;
			}
		}
		
		private string _r2教師提供鼓勵支持之學習氣氛;
		public virtual string R2教師提供鼓勵支持之學習氣氛
		{
			get
			{
				return this._r2教師提供鼓勵支持之學習氣氛;
			}
			set
			{
				this._r2教師提供鼓勵支持之學習氣氛 = value;
			}
		}
		
		private string _r2教師給予清楚合理的學習目標;
		public virtual string R2教師給予清楚合理的學習目標
		{
			get
			{
				return this._r2教師給予清楚合理的學習目標;
			}
			set
			{
				this._r2教師給予清楚合理的學習目標 = value;
			}
		}
		
		private string _r2教師給予明確回饋與改善建議;
		public virtual string R2教師給予明確回饋與改善建議
		{
			get
			{
				return this._r2教師給予明確回饋與改善建議;
			}
			set
			{
				this._r2教師給予明確回饋與改善建議 = value;
			}
		}
		
		private string _r2教師具教學熱忱願意付出時間從事教學上的表現;
		public virtual string R2教師具教學熱忱願意付出時間從事教學上的表現
		{
			get
			{
				return this._r2教師具教學熱忱願意付出時間從事教學上的表現;
			}
			set
			{
				this._r2教師具教學熱忱願意付出時間從事教學上的表現 = value;
			}
		}
		
		private string _r2教師展現臨床醫療專業能力和行為表現;
		public virtual string R2教師展現臨床醫療專業能力和行為表現
		{
			get
			{
				return this._r2教師展現臨床醫療專業能力和行為表現;
			}
			set
			{
				this._r2教師展現臨床醫療專業能力和行為表現 = value;
			}
		}
		
		private string _臨床單位提供清楚的教學計畫或學習指引對學習有幫助;
		public virtual string 臨床單位提供清楚的教學計畫或學習指引對學習有幫助
		{
			get
			{
				return this._臨床單位提供清楚的教學計畫或學習指引對學習有幫助;
			}
			set
			{
				this._臨床單位提供清楚的教學計畫或學習指引對學習有幫助 = value;
			}
		}
		
		private string _臨床單位學術活動如討論會及教學課程安排適當且落實施行;
		public virtual string 臨床單位學術活動如討論會及教學課程安排適當且落實施行
		{
			get
			{
				return this._臨床單位學術活動如討論會及教學課程安排適當且落實施行;
			}
			set
			{
				this._臨床單位學術活動如討論會及教學課程安排適當且落實施行 = value;
			}
		}
		
		private string _臨床單位提升我的完整行醫專業能力;
		public virtual string 臨床單位提升我的完整行醫專業能力
		{
			get
			{
				return this._臨床單位提升我的完整行醫專業能力;
			}
			set
			{
				this._臨床單位提升我的完整行醫專業能力 = value;
			}
		}
		
		private string _臨床單位的工作負荷安排合宜關切我的身心健全;
		public virtual string 臨床單位的工作負荷安排合宜關切我的身心健全
		{
			get
			{
				return this._臨床單位的工作負荷安排合宜關切我的身心健全;
			}
			set
			{
				this._臨床單位的工作負荷安排合宜關切我的身心健全 = value;
			}
		}
		
		private string _與其他醫療人員跨領域團隊互動良好獲得必要的協助;
		public virtual string 與其他醫療人員跨領域團隊互動良好獲得必要的協助
		{
			get
			{
				return this._與其他醫療人員跨領域團隊互動良好獲得必要的協助;
			}
			set
			{
				this._與其他醫療人員跨領域團隊互動良好獲得必要的協助 = value;
			}
		}
		
		private string _對臨床指導教師與臨床科室的具體回饋或建議;
		public virtual string 對臨床指導教師與臨床科室的具體回饋或建議
		{
			get
			{
				return this._對臨床指導教師與臨床科室的具體回饋或建議;
			}
			set
			{
				this._對臨床指導教師與臨床科室的具體回饋或建議 = value;
			}
		}
		
		private string _科別代碼;
		public virtual string 科別代碼
		{
			get
			{
				return this._科別代碼;
			}
			set
			{
				this._科別代碼 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
