#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class SCHEDULERLOG
	{
		private string _fUNCTIONNAME;
		public virtual string FUNCTIONNAME
		{
			get
			{
				return this._fUNCTIONNAME;
			}
			set
			{
				this._fUNCTIONNAME = value;
			}
		}
		
		private string _lOGCONTENT;
		public virtual string LOGCONTENT
		{
			get
			{
				return this._lOGCONTENT;
			}
			set
			{
				this._lOGCONTENT = value;
			}
		}
		
		private DateTime? _lOGTIME;
		public virtual DateTime? LOGTIME
		{
			get
			{
				return this._lOGTIME;
			}
			set
			{
				this._lOGTIME = value;
			}
		}
		
		private int _lOGID;
		public virtual int LOGID
		{
			get
			{
				return this._lOGID;
			}
			set
			{
				this._lOGID = value;
			}
		}
		
		private string _lOGPARAMETER;
		public virtual string LOGPARAMETER
		{
			get
			{
				return this._lOGPARAMETER;
			}
			set
			{
				this._lOGPARAMETER = value;
			}
		}
		
	}
}
#pragma warning restore 1591
