#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMUH.iKASAWebApi.DomainModel.Entities;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class SCORESETTING
	{
		private string _sETTINGID;
		public virtual string SETTINGID
		{
			get
			{
				return this._sETTINGID;
			}
			set
			{
				this._sETTINGID = value;
			}
		}
		
		private string _dEPTCODE;
		public virtual string DEPTCODE
		{
			get
			{
				return this._dEPTCODE;
			}
			set
			{
				this._dEPTCODE = value;
			}
		}
		
		private string _sETTINGNAME;
		public virtual string SETTINGNAME
		{
			get
			{
				return this._sETTINGNAME;
			}
			set
			{
				this._sETTINGNAME = value;
			}
		}
		
		private string _cREATER;
		public virtual string CREATER
		{
			get
			{
				return this._cREATER;
			}
			set
			{
				this._cREATER = value;
			}
		}
		
		private DateTime? _cREATEDATE;
		public virtual DateTime? CREATEDATE
		{
			get
			{
				return this._cREATEDATE;
			}
			set
			{
				this._cREATEDATE = value;
			}
		}
		
		private string _mODIFIER;
		public virtual string MODIFIER
		{
			get
			{
				return this._mODIFIER;
			}
			set
			{
				this._mODIFIER = value;
			}
		}
		
		private DateTime? _mODIFYDATE;
		public virtual DateTime? MODIFYDATE
		{
			get
			{
				return this._mODIFYDATE;
			}
			set
			{
				this._mODIFYDATE = value;
			}
		}
		
		private IList<SCORESETTINGSCORETYPE> _sCORESETTINGSCORETYPEs = new List<SCORESETTINGSCORETYPE>();
		public virtual IList<SCORESETTINGSCORETYPE> SCORESETTINGSCORETYPEs
		{
			get
			{
				return this._sCORESETTINGSCORETYPEs;
			}
		}
		
		private IList<SCORESETTINGJOB> _sCORESETTINGJOBs = new List<SCORESETTINGJOB>();
		public virtual IList<SCORESETTINGJOB> SCORESETTINGJOBs
		{
			get
			{
				return this._sCORESETTINGJOBs;
			}
		}
		
		private IList<SCORESETTINGDETAIL> _sCORESETTINGDETAILs = new List<SCORESETTINGDETAIL>();
		public virtual IList<SCORESETTINGDETAIL> SCORESETTINGDETAILs
		{
			get
			{
				return this._sCORESETTINGDETAILs;
			}
		}
		
		private IList<SCOREINSTANCE> _sCOREINSTANCEs = new List<SCOREINSTANCE>();
		public virtual IList<SCOREINSTANCE> SCOREINSTANCEs
		{
			get
			{
				return this._sCOREINSTANCEs;
			}
		}
		
	}
}
#pragma warning restore 1591
