#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMUH.iKASAWebApi.DomainModel.Entities;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class SCOREINSTANCEDETAIL
	{
		private int _iNSTANCEDETAILID;
		public virtual int INSTANCEDETAILID
		{
			get
			{
				return this._iNSTANCEDETAILID;
			}
			set
			{
				this._iNSTANCEDETAILID = value;
			}
		}
		
		private string _iNSTANCEID;
		public virtual string INSTANCEID
		{
			get
			{
				return this._iNSTANCEID;
			}
			set
			{
				this._iNSTANCEID = value;
			}
		}
		
		private string _sETTINGID;
		public virtual string SETTINGID
		{
			get
			{
				return this._sETTINGID;
			}
			set
			{
				this._sETTINGID = value;
			}
		}
		
		private string _vALUETYPE;
		public virtual string VALUETYPE
		{
			get
			{
				return this._vALUETYPE;
			}
			set
			{
				this._vALUETYPE = value;
			}
		}
		
		private string _vALUEID;
		public virtual string VALUEID
		{
			get
			{
				return this._vALUEID;
			}
			set
			{
				this._vALUEID = value;
			}
		}
		
		private string _tARGETID;
		public virtual string TARGETID
		{
			get
			{
				return this._tARGETID;
			}
			set
			{
				this._tARGETID = value;
			}
		}
		
		private decimal? _sCOREPERCENT;
		public virtual decimal? SCOREPERCENT
		{
			get
			{
				return this._sCOREPERCENT;
			}
			set
			{
				this._sCOREPERCENT = value;
			}
		}
		
		private decimal? _sCORE;
		public virtual decimal? SCORE
		{
			get
			{
				return this._sCORE;
			}
			set
			{
				this._sCORE = value;
			}
		}
		
		private string _mODIFIER;
		public virtual string MODIFIER
		{
			get
			{
				return this._mODIFIER;
			}
			set
			{
				this._mODIFIER = value;
			}
		}
		
		private DateTime? _mODIFYDATE;
		public virtual DateTime? MODIFYDATE
		{
			get
			{
				return this._mODIFYDATE;
			}
			set
			{
				this._mODIFYDATE = value;
			}
		}
		
		private SCOREINSTANCE _sCOREINSTANCE;
		public virtual SCOREINSTANCE SCOREINSTANCE
		{
			get
			{
				return this._sCOREINSTANCE;
			}
			set
			{
				this._sCOREINSTANCE = value;
			}
		}
		
	}
}
#pragma warning restore 1591
