#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMUH.iKASAWebApi.DomainModel.Entities;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class SCOREINSTANCE
	{
		private string _iNSTANCEID;
		public virtual string INSTANCEID
		{
			get
			{
				return this._iNSTANCEID;
			}
			set
			{
				this._iNSTANCEID = value;
			}
		}
		
		private string _sETTINGID;
		public virtual string SETTINGID
		{
			get
			{
				return this._sETTINGID;
			}
			set
			{
				this._sETTINGID = value;
			}
		}
		
		private DateTime _dATASDATE;
		public virtual DateTime DATASDATE
		{
			get
			{
				return this._dATASDATE;
			}
			set
			{
				this._dATASDATE = value;
			}
		}
		
		private DateTime _dATAEDATE;
		public virtual DateTime DATAEDATE
		{
			get
			{
				return this._dATAEDATE;
			}
			set
			{
				this._dATAEDATE = value;
			}
		}
		
		private string _cREATER;
		public virtual string CREATER
		{
			get
			{
				return this._cREATER;
			}
			set
			{
				this._cREATER = value;
			}
		}
		
		private DateTime _cREATEDATE;
		public virtual DateTime CREATEDATE
		{
			get
			{
				return this._cREATEDATE;
			}
			set
			{
				this._cREATEDATE = value;
			}
		}
		
		private string _mODIFIER;
		public virtual string MODIFIER
		{
			get
			{
				return this._mODIFIER;
			}
			set
			{
				this._mODIFIER = value;
			}
		}
		
		private DateTime? _mODIFYDATE;
		public virtual DateTime? MODIFYDATE
		{
			get
			{
				return this._mODIFYDATE;
			}
			set
			{
				this._mODIFYDATE = value;
			}
		}
		
		private SCORESETTING _sCORESETTING;
		public virtual SCORESETTING SCORESETTING
		{
			get
			{
				return this._sCORESETTING;
			}
			set
			{
				this._sCORESETTING = value;
			}
		}
		
		private IList<SCOREINSTANCEDETAIL> _sCOREINSTANCEDETAILs = new List<SCOREINSTANCEDETAIL>();
		public virtual IList<SCOREINSTANCEDETAIL> SCOREINSTANCEDETAILs
		{
			get
			{
				return this._sCOREINSTANCEDETAILs;
			}
		}
		
	}
}
#pragma warning restore 1591
