#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMUH.iKASAWebApi.DomainModel.Entities;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class TEACHPOINTITEMREQUIRE
	{
		private int _iTEMID;
		public virtual int ITEMID
		{
			get
			{
				return this._iTEMID;
			}
			set
			{
				this._iTEMID = value;
			}
		}
		
		private string _rEQTYPE;
		public virtual string REQTYPE
		{
			get
			{
				return this._rEQTYPE;
			}
			set
			{
				this._rEQTYPE = value;
			}
		}
		
		private string _rEQID;
		public virtual string REQID
		{
			get
			{
				return this._rEQID;
			}
			set
			{
				this._rEQID = value;
			}
		}
		
		private decimal? _rEQCOUNT;
		public virtual decimal? REQCOUNT
		{
			get
			{
				return this._rEQCOUNT;
			}
			set
			{
				this._rEQCOUNT = value;
			}
		}
		
		private decimal? _rEQRATE;
		public virtual decimal? REQRATE
		{
			get
			{
				return this._rEQRATE;
			}
			set
			{
				this._rEQRATE = value;
			}
		}
		
		private TEACHPOINTITEM _tEACHPOINTITEM;
		public virtual TEACHPOINTITEM TEACHPOINTITEM
		{
			get
			{
				return this._tEACHPOINTITEM;
			}
			set
			{
				this._tEACHPOINTITEM = value;
			}
		}
		
	}
}
#pragma warning restore 1591
