#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMUH.iKASAWebApi.DomainModel.Entities;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class TEACHPOINTCALCTYPEREF
	{
		private int _tYPEID;
		public virtual int TYPEID
		{
			get
			{
				return this._tYPEID;
			}
			set
			{
				this._tYPEID = value;
			}
		}
		
		private int _iTEMID;
		public virtual int ITEMID
		{
			get
			{
				return this._iTEMID;
			}
			set
			{
				this._iTEMID = value;
			}
		}
		
		private TEACHPOINTITEM _tEACHPOINTITEM;
		public virtual TEACHPOINTITEM TEACHPOINTITEM
		{
			get
			{
				return this._tEACHPOINTITEM;
			}
			set
			{
				this._tEACHPOINTITEM = value;
			}
		}
		
	}
}
#pragma warning restore 1591
