#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMUH.iKASAWebApi.DomainModel.Entities;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class TEACHPOINTITEM
	{
		private int _iTEMID;
		public virtual int ITEMID
		{
			get
			{
				return this._iTEMID;
			}
			set
			{
				this._iTEMID = value;
			}
		}
		
		private string _iTEMNAME;
		public virtual string ITEMNAME
		{
			get
			{
				return this._iTEMNAME;
			}
			set
			{
				this._iTEMNAME = value;
			}
		}
		
		private string _iTEMTYPE;
		public virtual string ITEMTYPE
		{
			get
			{
				return this._iTEMTYPE;
			}
			set
			{
				this._iTEMTYPE = value;
			}
		}
		
		private string _pOINTUNIT;
		public virtual string POINTUNIT
		{
			get
			{
				return this._pOINTUNIT;
			}
			set
			{
				this._pOINTUNIT = value;
			}
		}
		
		private decimal? _eACHPOINT;
		public virtual decimal? EACHPOINT
		{
			get
			{
				return this._eACHPOINT;
			}
			set
			{
				this._eACHPOINT = value;
			}
		}
		
		private string _eACHUNIT;
		public virtual string EACHUNIT
		{
			get
			{
				return this._eACHUNIT;
			}
			set
			{
				this._eACHUNIT = value;
			}
		}
		
		private decimal? _mAXPOINT;
		public virtual decimal? MAXPOINT
		{
			get
			{
				return this._mAXPOINT;
			}
			set
			{
				this._mAXPOINT = value;
			}
		}
		
		private string _mAXPOINTEVALRANGE;
		public virtual string MAXPOINTEVALRANGE
		{
			get
			{
				return this._mAXPOINTEVALRANGE;
			}
			set
			{
				this._mAXPOINTEVALRANGE = value;
			}
		}
		
		private string _rEMARK;
		public virtual string REMARK
		{
			get
			{
				return this._rEMARK;
			}
			set
			{
				this._rEMARK = value;
			}
		}
		
		private string _tRAININGTYPE;
		public virtual string TRAININGTYPE
		{
			get
			{
				return this._tRAININGTYPE;
			}
			set
			{
				this._tRAININGTYPE = value;
			}
		}
		
		private IList<TEACHPOINTREF> _tEACHPOINTREFs = new List<TEACHPOINTREF>();
		public virtual IList<TEACHPOINTREF> TEACHPOINTREFs
		{
			get
			{
				return this._tEACHPOINTREFs;
			}
		}
		
		private IList<TEACHPOINTJOBITEM> _tEACHPOINTJOBITEMs = new List<TEACHPOINTJOBITEM>();
		public virtual IList<TEACHPOINTJOBITEM> TEACHPOINTJOBITEMs
		{
			get
			{
				return this._tEACHPOINTJOBITEMs;
			}
		}
		
		private IList<TEACHPOINTITEMREQUIRE> _tEACHPOINTITEMREQUIREs = new List<TEACHPOINTITEMREQUIRE>();
		public virtual IList<TEACHPOINTITEMREQUIRE> TEACHPOINTITEMREQUIREs
		{
			get
			{
				return this._tEACHPOINTITEMREQUIREs;
			}
		}
		
		private IList<TEACHPOINTEMPITEMDATUM> _tEACHPOINTEMPITEMDATa = new List<TEACHPOINTEMPITEMDATUM>();
		public virtual IList<TEACHPOINTEMPITEMDATUM> TEACHPOINTEMPITEMDATa
		{
			get
			{
				return this._tEACHPOINTEMPITEMDATa;
			}
		}
		
		private IList<TEACHPOINTCALCTYPEREF> _tEACHPOINTCALCTYPEREFs = new List<TEACHPOINTCALCTYPEREF>();
		public virtual IList<TEACHPOINTCALCTYPEREF> TEACHPOINTCALCTYPEREFs
		{
			get
			{
				return this._tEACHPOINTCALCTYPEREFs;
			}
		}
		
	}
}
#pragma warning restore 1591
