#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class TEACHTIMETYPE
	{
		private string _sETTINGTYPE;
		public virtual string SETTINGTYPE
		{
			get
			{
				return this._sETTINGTYPE;
			}
			set
			{
				this._sETTINGTYPE = value;
			}
		}
		
		private bool _nEEDATTACHMENT;
		public virtual bool NEEDATTACHMENT
		{
			get
			{
				return this._nEEDATTACHMENT;
			}
			set
			{
				this._nEEDATTACHMENT = value;
			}
		}
		
		private bool _nEEDMEMBER;
		public virtual bool NEEDMEMBER
		{
			get
			{
				return this._nEEDMEMBER;
			}
			set
			{
				this._nEEDMEMBER = value;
			}
		}
		
		private string _dISABLE;
		public virtual string DISABLE
		{
			get
			{
				return this._dISABLE;
			}
			set
			{
				this._dISABLE = value;
			}
		}
		
		private bool _lOADFORMDATA;
		public virtual bool LOADFORMDATA
		{
			get
			{
				return this._lOADFORMDATA;
			}
			set
			{
				this._lOADFORMDATA = value;
			}
		}
		
		private bool _aLLOWKPI;
		public virtual bool ALLOWKPI
		{
			get
			{
				return this._aLLOWKPI;
			}
			set
			{
				this._aLLOWKPI = value;
			}
		}
		
	}
}
#pragma warning restore 1591
