#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class TEST
	{
		private string _cOLUMN_1;
		public virtual string COLUMN_1
		{
			get
			{
				return this._cOLUMN_1;
			}
			set
			{
				this._cOLUMN_1 = value;
			}
		}
		
		private int _cOLUMN_2;
		public virtual int COLUMN_2
		{
			get
			{
				return this._cOLUMN_2;
			}
			set
			{
				this._cOLUMN_2 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
