#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class TRAININGTIME
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _eDUYEAR;
		public virtual string EDUYEAR
		{
			get
			{
				return this._eDUYEAR;
			}
			set
			{
				this._eDUYEAR = value;
			}
		}
		
		private int? _sEMESTER;
		public virtual int? SEMESTER
		{
			get
			{
				return this._sEMESTER;
			}
			set
			{
				this._sEMESTER = value;
			}
		}
		
		private string _hOSPITAL;
		public virtual string HOSPITAL
		{
			get
			{
				return this._hOSPITAL;
			}
			set
			{
				this._hOSPITAL = value;
			}
		}
		
		private string _eMPCODE;
		public virtual string EMPCODE
		{
			get
			{
				return this._eMPCODE;
			}
			set
			{
				this._eMPCODE = value;
			}
		}
		
		private string _rOLE;
		public virtual string ROLE
		{
			get
			{
				return this._rOLE;
			}
			set
			{
				this._rOLE = value;
			}
		}
		
		private DateTime? _tRAININGTIME1;
		public virtual DateTime? TRAININGTIME1
		{
			get
			{
				return this._tRAININGTIME1;
			}
			set
			{
				this._tRAININGTIME1 = value;
			}
		}
		
		private decimal? _tIMEHOUR;
		public virtual decimal? TIMEHOUR
		{
			get
			{
				return this._tIMEHOUR;
			}
			set
			{
				this._tIMEHOUR = value;
			}
		}
		
		private string _cLASSNAME;
		public virtual string CLASSNAME
		{
			get
			{
				return this._cLASSNAME;
			}
			set
			{
				this._cLASSNAME = value;
			}
		}
		
		private string _cLASSTYPE;
		public virtual string CLASSTYPE
		{
			get
			{
				return this._cLASSTYPE;
			}
			set
			{
				this._cLASSTYPE = value;
			}
		}
		
		private string _cREATER;
		public virtual string CREATER
		{
			get
			{
				return this._cREATER;
			}
			set
			{
				this._cREATER = value;
			}
		}
		
		private DateTime? _cREATETIME;
		public virtual DateTime? CREATETIME
		{
			get
			{
				return this._cREATETIME;
			}
			set
			{
				this._cREATETIME = value;
			}
		}
		
		private string _sTATUS;
		public virtual string STATUS
		{
			get
			{
				return this._sTATUS;
			}
			set
			{
				this._sTATUS = value;
			}
		}
		
	}
}
#pragma warning restore 1591
