#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMUH.iKASAWebApi.DomainModel.Entities;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class VOTEJOB
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private int _mAINID;
		public virtual int MAINID
		{
			get
			{
				return this._mAINID;
			}
			set
			{
				this._mAINID = value;
			}
		}
		
		private string _jOBCODE;
		public virtual string JOBCODE
		{
			get
			{
				return this._jOBCODE;
			}
			set
			{
				this._jOBCODE = value;
			}
		}
		
		private VOTEMAIN _vOTEMAIN;
		public virtual VOTEMAIN VOTEMAIN
		{
			get
			{
				return this._vOTEMAIN;
			}
			set
			{
				this._vOTEMAIN = value;
			}
		}
		
	}
}
#pragma warning restore 1591
