#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMUH.iKASAWebApi.DomainModel.Entities;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class VOTEGCOND
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private int _gROUPID;
		public virtual int GROUPID
		{
			get
			{
				return this._gROUPID;
			}
			set
			{
				this._gROUPID = value;
			}
		}
		
		private string _cODE;
		public virtual string CODE
		{
			get
			{
				return this._cODE;
			}
			set
			{
				this._cODE = value;
			}
		}
		
		private string _cONDTYPE;
		public virtual string CONDTYPE
		{
			get
			{
				return this._cONDTYPE;
			}
			set
			{
				this._cONDTYPE = value;
			}
		}
		
		private VOTEGROUP _vOTEGROUP;
		public virtual VOTEGROUP VOTEGROUP
		{
			get
			{
				return this._vOTEGROUP;
			}
			set
			{
				this._vOTEGROUP = value;
			}
		}
		
	}
}
#pragma warning restore 1591
