#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMUH.iKASAWebApi.DomainModel.Entities;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class VOTEMAIN
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _vOTENAME;
		public virtual string VOTENAME
		{
			get
			{
				return this._vOTENAME;
			}
			set
			{
				this._vOTENAME = value;
			}
		}
		
		private DateTime? _sDATE;
		public virtual DateTime? SDATE
		{
			get
			{
				return this._sDATE;
			}
			set
			{
				this._sDATE = value;
			}
		}
		
		private DateTime? _eDATE;
		public virtual DateTime? EDATE
		{
			get
			{
				return this._eDATE;
			}
			set
			{
				this._eDATE = value;
			}
		}
		
		private string _cREATER;
		public virtual string CREATER
		{
			get
			{
				return this._cREATER;
			}
			set
			{
				this._cREATER = value;
			}
		}
		
		private string _vOTETYPE;
		public virtual string VOTETYPE
		{
			get
			{
				return this._vOTETYPE;
			}
			set
			{
				this._vOTETYPE = value;
			}
		}
		
		private string _hOSPCODE;
		public virtual string HOSPCODE
		{
			get
			{
				return this._hOSPCODE;
			}
			set
			{
				this._hOSPCODE = value;
			}
		}
		
		private string _hEADER;
		public virtual string HEADER
		{
			get
			{
				return this._hEADER;
			}
			set
			{
				this._hEADER = value;
			}
		}
		
		private IList<VOTETARGET> _vOTETARGETs = new List<VOTETARGET>();
		public virtual IList<VOTETARGET> VOTETARGETs
		{
			get
			{
				return this._vOTETARGETs;
			}
		}
		
		private IList<VOTEJOB> _vOTEJOBs = new List<VOTEJOB>();
		public virtual IList<VOTEJOB> VOTEJOBs
		{
			get
			{
				return this._vOTEJOBs;
			}
		}
		
		private IList<VOTEGROUP> _vOTEGROUPs = new List<VOTEGROUP>();
		public virtual IList<VOTEGROUP> VOTEGROUPs
		{
			get
			{
				return this._vOTEGROUPs;
			}
		}
		
	}
}
#pragma warning restore 1591
