#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class 抓MAIL暫存
	{
		private string _姓名;
		public virtual string 姓名
		{
			get
			{
				return this._姓名;
			}
			set
			{
				this._姓名 = value;
			}
		}
		
		private string _身分證字號;
		public virtual string 身分證字號
		{
			get
			{
				return this._身分證字號;
			}
			set
			{
				this._身分證字號 = value;
			}
		}
		
		private string _eMAIL;
		public virtual string EMAIL
		{
			get
			{
				return this._eMAIL;
			}
			set
			{
				this._eMAIL = value;
			}
		}
		
		private string _離職;
		public virtual string 離職
		{
			get
			{
				return this._離職;
			}
			set
			{
				this._離職 = value;
			}
		}
		
		private string _職類;
		public virtual string 職類
		{
			get
			{
				return this._職類;
			}
			set
			{
				this._職類 = value;
			}
		}
		
		private string _師生別;
		public virtual string 師生別
		{
			get
			{
				return this._師生別;
			}
			set
			{
				this._師生別 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
