#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMUH.iKASAWebApi.DomainModel.Entities	
{
	public partial class 移課程暫存
	{
		private string _課程ID;
		public virtual string 課程ID
		{
			get
			{
				return this._課程ID;
			}
			set
			{
				this._課程ID = value;
			}
		}
		
		private string _新課程名稱;
		public virtual string 新課程名稱
		{
			get
			{
				return this._新課程名稱;
			}
			set
			{
				this._新課程名稱 = value;
			}
		}
		
		private string _移至課程ID;
		public virtual string 移至課程ID
		{
			get
			{
				return this._移至課程ID;
			}
			set
			{
				this._移至課程ID = value;
			}
		}
		
		private string _原課程名稱;
		public virtual string 原課程名稱
		{
			get
			{
				return this._原課程名稱;
			}
			set
			{
				this._原課程名稱 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
