

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections;
using System.Collections.Generic;
using AppFramework.Infrastructure.Data.Repositories;
using Telerik.OpenAccess;
using KMUH.iKASAWebApi.DomainModel.Entities;

namespace KMUH.iKASAWebApi.Infrastructure.Data.Repositories
{
	public partial interface I移課程暫存Repository : IRepository<移課程暫存>
	{
	}


	public partial class 移課程暫存Repository : Repository<移課程暫存>, I移課程暫存Repository
	{
		public 移課程暫存Repository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface I抓MAIL暫存Repository : IRepository<抓MAIL暫存>
	{
	}


	public partial class 抓MAIL暫存Repository : Repository<抓MAIL暫存>, I抓MAIL暫存Repository
	{
		public 抓MAIL暫存Repository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface I住院醫師暫存Repository : IRepository<住院醫師暫存>
	{
	}


	public partial class 住院醫師暫存Repository : Repository<住院醫師暫存>, I住院醫師暫存Repository
	{
		public 住院醫師暫存Repository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface I西醫受訓人員名單Repository : IRepository<西醫受訓人員名單>
	{
	}


	public partial class 西醫受訓人員名單Repository : Repository<西醫受訓人員名單>, I西醫受訓人員名單Repository
	{
		public 西醫受訓人員名單Repository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IVOTEUSERDEFINELISTRepository : IRepository<VOTEUSERDEFINELIST>
	{
	}


	public partial class VOTEUSERDEFINELISTRepository : Repository<VOTEUSERDEFINELIST>, IVOTEUSERDEFINELISTRepository
	{
		public VOTEUSERDEFINELISTRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IVOTETEMPDATUMRepository : IRepository<VOTETEMPDATUM>
	{
	}


	public partial class VOTETEMPDATUMRepository : Repository<VOTETEMPDATUM>, IVOTETEMPDATUMRepository
	{
		public VOTETEMPDATUMRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IVOTETARGETRepository : IRepository<VOTETARGET>
	{
	}


	public partial class VOTETARGETRepository : Repository<VOTETARGET>, IVOTETARGETRepository
	{
		public VOTETARGETRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IVOTEMAINRepository : IRepository<VOTEMAIN>
	{
	}


	public partial class VOTEMAINRepository : Repository<VOTEMAIN>, IVOTEMAINRepository
	{
		public VOTEMAINRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IVOTEJOBRepository : IRepository<VOTEJOB>
	{
	}


	public partial class VOTEJOBRepository : Repository<VOTEJOB>, IVOTEJOBRepository
	{
		public VOTEJOBRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IVOTEINSTANCERepository : IRepository<VOTEINSTANCE>
	{
	}


	public partial class VOTEINSTANCERepository : Repository<VOTEINSTANCE>, IVOTEINSTANCERepository
	{
		public VOTEINSTANCERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IVOTEINSDETRepository : IRepository<VOTEINSDET>
	{
	}


	public partial class VOTEINSDETRepository : Repository<VOTEINSDET>, IVOTEINSDETRepository
	{
		public VOTEINSDETRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IVOTEGROUPRepository : IRepository<VOTEGROUP>
	{
	}


	public partial class VOTEGROUPRepository : Repository<VOTEGROUP>, IVOTEGROUPRepository
	{
		public VOTEGROUPRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IVOTEGCONDRepository : IRepository<VOTEGCOND>
	{
	}


	public partial class VOTEGCONDRepository : Repository<VOTEGCOND>, IVOTEGCONDRepository
	{
		public VOTEGCONDRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface ITRAININGTIMERepository : IRepository<TRAININGTIME>
	{
	}


	public partial class TRAININGTIMERepository : Repository<TRAININGTIME>, ITRAININGTIMERepository
	{
		public TRAININGTIMERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface ITESTRepository : IRepository<TEST>
	{
	}


	public partial class TESTRepository : Repository<TEST>, ITESTRepository
	{
		public TESTRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface ITEACHTIMETYPERepository : IRepository<TEACHTIMETYPE>
	{
	}


	public partial class TEACHTIMETYPERepository : Repository<TEACHTIMETYPE>, ITEACHTIMETYPERepository
	{
		public TEACHTIMETYPERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface ITEACHTIMERATERepository : IRepository<TEACHTIMERATE>
	{
	}


	public partial class TEACHTIMERATERepository : Repository<TEACHTIMERATE>, ITEACHTIMERATERepository
	{
		public TEACHTIMERATERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface ITEACHTIMEKPIREFTEMPRepository : IRepository<TEACHTIMEKPIREFTEMP>
	{
	}


	public partial class TEACHTIMEKPIREFTEMPRepository : Repository<TEACHTIMEKPIREFTEMP>, ITEACHTIMEKPIREFTEMPRepository
	{
		public TEACHTIMEKPIREFTEMPRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface ITEACHTIMEKPIREFRepository : IRepository<TEACHTIMEKPIREF>
	{
	}


	public partial class TEACHTIMEKPIREFRepository : Repository<TEACHTIMEKPIREF>, ITEACHTIMEKPIREFRepository
	{
		public TEACHTIMEKPIREFRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface ITEACHPOINTREFRepository : IRepository<TEACHPOINTREF>
	{
	}


	public partial class TEACHPOINTREFRepository : Repository<TEACHPOINTREF>, ITEACHPOINTREFRepository
	{
		public TEACHPOINTREFRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface ITEACHPOINTJOBITEMRepository : IRepository<TEACHPOINTJOBITEM>
	{
	}


	public partial class TEACHPOINTJOBITEMRepository : Repository<TEACHPOINTJOBITEM>, ITEACHPOINTJOBITEMRepository
	{
		public TEACHPOINTJOBITEMRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface ITEACHPOINTITEMREQUIRERepository : IRepository<TEACHPOINTITEMREQUIRE>
	{
	}


	public partial class TEACHPOINTITEMREQUIRERepository : Repository<TEACHPOINTITEMREQUIRE>, ITEACHPOINTITEMREQUIRERepository
	{
		public TEACHPOINTITEMREQUIRERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface ITEACHPOINTITEMRepository : IRepository<TEACHPOINTITEM>
	{
	}


	public partial class TEACHPOINTITEMRepository : Repository<TEACHPOINTITEM>, ITEACHPOINTITEMRepository
	{
		public TEACHPOINTITEMRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface ITEACHPOINTEMPITEMDATUMRepository : IRepository<TEACHPOINTEMPITEMDATUM>
	{
	}


	public partial class TEACHPOINTEMPITEMDATUMRepository : Repository<TEACHPOINTEMPITEMDATUM>, ITEACHPOINTEMPITEMDATUMRepository
	{
		public TEACHPOINTEMPITEMDATUMRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface ITEACHPOINTCALCTYPEREFRepository : IRepository<TEACHPOINTCALCTYPEREF>
	{
	}


	public partial class TEACHPOINTCALCTYPEREFRepository : Repository<TEACHPOINTCALCTYPEREF>, ITEACHPOINTCALCTYPEREFRepository
	{
		public TEACHPOINTCALCTYPEREFRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface ITEACHPOINTCALCTYPERepository : IRepository<TEACHPOINTCALCTYPE>
	{
	}


	public partial class TEACHPOINTCALCTYPERepository : Repository<TEACHPOINTCALCTYPE>, ITEACHPOINTCALCTYPERepository
	{
		public TEACHPOINTCALCTYPERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface ISCORESETTINGSCORETYPERepository : IRepository<SCORESETTINGSCORETYPE>
	{
	}


	public partial class SCORESETTINGSCORETYPERepository : Repository<SCORESETTINGSCORETYPE>, ISCORESETTINGSCORETYPERepository
	{
		public SCORESETTINGSCORETYPERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface ISCORESETTINGJOBRepository : IRepository<SCORESETTINGJOB>
	{
	}


	public partial class SCORESETTINGJOBRepository : Repository<SCORESETTINGJOB>, ISCORESETTINGJOBRepository
	{
		public SCORESETTINGJOBRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface ISCORESETTINGDETAILRepository : IRepository<SCORESETTINGDETAIL>
	{
	}


	public partial class SCORESETTINGDETAILRepository : Repository<SCORESETTINGDETAIL>, ISCORESETTINGDETAILRepository
	{
		public SCORESETTINGDETAILRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface ISCORESETTINGRepository : IRepository<SCORESETTING>
	{
	}


	public partial class SCORESETTINGRepository : Repository<SCORESETTING>, ISCORESETTINGRepository
	{
		public SCORESETTINGRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface ISCOREINSTANCEDETAILRepository : IRepository<SCOREINSTANCEDETAIL>
	{
	}


	public partial class SCOREINSTANCEDETAILRepository : Repository<SCOREINSTANCEDETAIL>, ISCOREINSTANCEDETAILRepository
	{
		public SCOREINSTANCEDETAILRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface ISCOREINSTANCERepository : IRepository<SCOREINSTANCE>
	{
	}


	public partial class SCOREINSTANCERepository : Repository<SCOREINSTANCE>, ISCOREINSTANCERepository
	{
		public SCOREINSTANCERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface ISCHEDULERLOGRepository : IRepository<SCHEDULERLOG>
	{
	}


	public partial class SCHEDULERLOGRepository : Repository<SCHEDULERLOG>, ISCHEDULERLOGRepository
	{
		public SCHEDULERLOGRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IR分級資料Repository : IRepository<R分級資料>
	{
	}


	public partial class R分級資料Repository : Repository<R分級資料>, IR分級資料Repository
	{
		public R分級資料Repository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IREPORTDATATEMPRepository : IRepository<REPORTDATATEMP>
	{
	}


	public partial class REPORTDATATEMPRepository : Repository<REPORTDATATEMP>, IREPORTDATATEMPRepository
	{
		public REPORTDATATEMPRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IRECORDTEMPLATERepository : IRepository<RECORDTEMPLATE>
	{
	}


	public partial class RECORDTEMPLATERepository : Repository<RECORDTEMPLATE>, IRECORDTEMPLATERepository
	{
		public RECORDTEMPLATERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IRECORDINSVIEWERRepository : IRepository<RECORDINSVIEWER>
	{
	}


	public partial class RECORDINSVIEWERRepository : Repository<RECORDINSVIEWER>, IRECORDINSVIEWERRepository
	{
		public RECORDINSVIEWERRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IRECORDINSTANCEREJECTLOGRepository : IRepository<RECORDINSTANCEREJECTLOG>
	{
	}


	public partial class RECORDINSTANCEREJECTLOGRepository : Repository<RECORDINSTANCEREJECTLOG>, IRECORDINSTANCEREJECTLOGRepository
	{
		public RECORDINSTANCEREJECTLOGRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IRECORDINSTANCERepository : IRepository<RECORDINSTANCE>
	{
	}


	public partial class RECORDINSTANCERepository : Repository<RECORDINSTANCE>, IRECORDINSTANCERepository
	{
		public RECORDINSTANCERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IRECORDINSSIGNINRepository : IRepository<RECORDINSSIGNIN>
	{
	}


	public partial class RECORDINSSIGNINRepository : Repository<RECORDINSSIGNIN>, IRECORDINSSIGNINRepository
	{
		public RECORDINSSIGNINRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IRECORDINSREADERRepository : IRepository<RECORDINSREADER>
	{
	}


	public partial class RECORDINSREADERRepository : Repository<RECORDINSREADER>, IRECORDINSREADERRepository
	{
		public RECORDINSREADERRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IRECORDINSDETRepository : IRepository<RECORDINSDET>
	{
	}


	public partial class RECORDINSDETRepository : Repository<RECORDINSDET>, IRECORDINSDETRepository
	{
		public RECORDINSDETRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IRECORDEDUACTREFRepository : IRepository<RECORDEDUACTREF>
	{
	}


	public partial class RECORDEDUACTREFRepository : Repository<RECORDEDUACTREF>, IRECORDEDUACTREFRepository
	{
		public RECORDEDUACTREFRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IPSNOPDRepository : IRepository<PSNOPD>
	{
	}


	public partial class PSNOPDRepository : Repository<PSNOPD>, IPSNOPDRepository
	{
		public PSNOPDRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IPASSPORTSTUDENTAPPLICATIONITEMFAILLOGRepository : IRepository<PASSPORTSTUDENTAPPLICATIONITEMFAILLOG>
	{
	}


	public partial class PASSPORTSTUDENTAPPLICATIONITEMFAILLOGRepository : Repository<PASSPORTSTUDENTAPPLICATIONITEMFAILLOG>, IPASSPORTSTUDENTAPPLICATIONITEMFAILLOGRepository
	{
		public PASSPORTSTUDENTAPPLICATIONITEMFAILLOGRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IPASSPORTSTUDENTAPPLICATIONITEM_BK2Repository : IRepository<PASSPORTSTUDENTAPPLICATIONITEM_BK2>
	{
	}


	public partial class PASSPORTSTUDENTAPPLICATIONITEM_BK2Repository : Repository<PASSPORTSTUDENTAPPLICATIONITEM_BK2>, IPASSPORTSTUDENTAPPLICATIONITEM_BK2Repository
	{
		public PASSPORTSTUDENTAPPLICATIONITEM_BK2Repository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IPASSPORTSTUDENTAPPLICATIONITEM_BKRepository : IRepository<PASSPORTSTUDENTAPPLICATIONITEM_BK>
	{
	}


	public partial class PASSPORTSTUDENTAPPLICATIONITEM_BKRepository : Repository<PASSPORTSTUDENTAPPLICATIONITEM_BK>, IPASSPORTSTUDENTAPPLICATIONITEM_BKRepository
	{
		public PASSPORTSTUDENTAPPLICATIONITEM_BKRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IPASSPORTSTUDENTAPPLICATIONITEMRepository : IRepository<PASSPORTSTUDENTAPPLICATIONITEM>
	{
	}


	public partial class PASSPORTSTUDENTAPPLICATIONITEMRepository : Repository<PASSPORTSTUDENTAPPLICATIONITEM>, IPASSPORTSTUDENTAPPLICATIONITEMRepository
	{
		public PASSPORTSTUDENTAPPLICATIONITEMRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IPASSPORTSPECIALLISTRepository : IRepository<PASSPORTSPECIALLIST>
	{
	}


	public partial class PASSPORTSPECIALLISTRepository : Repository<PASSPORTSPECIALLIST>, IPASSPORTSPECIALLISTRepository
	{
		public PASSPORTSPECIALLISTRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IPASSPORTJOBTITLEITEM_BKRepository : IRepository<PASSPORTJOBTITLEITEM_BK>
	{
	}


	public partial class PASSPORTJOBTITLEITEM_BKRepository : Repository<PASSPORTJOBTITLEITEM_BK>, IPASSPORTJOBTITLEITEM_BKRepository
	{
		public PASSPORTJOBTITLEITEM_BKRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IPASSPORTJOBTITLEITEMRepository : IRepository<PASSPORTJOBTITLEITEM>
	{
	}


	public partial class PASSPORTJOBTITLEITEMRepository : Repository<PASSPORTJOBTITLEITEM>, IPASSPORTJOBTITLEITEMRepository
	{
		public PASSPORTJOBTITLEITEMRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IPASSPORTJOBFINALMANRepository : IRepository<PASSPORTJOBFINALMAN>
	{
	}


	public partial class PASSPORTJOBFINALMANRepository : Repository<PASSPORTJOBFINALMAN>, IPASSPORTJOBFINALMANRepository
	{
		public PASSPORTJOBFINALMANRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IPASSPORTDOCGRADERepository : IRepository<PASSPORTDOCGRADE>
	{
	}


	public partial class PASSPORTDOCGRADERepository : Repository<PASSPORTDOCGRADE>, IPASSPORTDOCGRADERepository
	{
		public PASSPORTDOCGRADERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IPASSPORTCHECKITEMRepository : IRepository<PASSPORTCHECKITEM>
	{
	}


	public partial class PASSPORTCHECKITEMRepository : Repository<PASSPORTCHECKITEM>, IPASSPORTCHECKITEMRepository
	{
		public PASSPORTCHECKITEMRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IOSCECERTRepository : IRepository<OSCECERT>
	{
	}


	public partial class OSCECERTRepository : Repository<OSCECERT>, IOSCECERTRepository
	{
		public OSCECERTRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IOSCEBLOCKTIMERepository : IRepository<OSCEBLOCKTIME>
	{
	}


	public partial class OSCEBLOCKTIMERepository : Repository<OSCEBLOCKTIME>, IOSCEBLOCKTIMERepository
	{
		public OSCEBLOCKTIMERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface INURSELISTRepository : IRepository<NURSELIST>
	{
	}


	public partial class NURSELISTRepository : Repository<NURSELIST>, INURSELISTRepository
	{
		public NURSELISTRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface INNOTEITEMRepository : IRepository<NNOTEITEM>
	{
	}


	public partial class NNOTEITEMRepository : Repository<NNOTEITEM>, INNOTEITEMRepository
	{
		public NNOTEITEMRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface INNOTERepository : IRepository<NNOTE>
	{
	}


	public partial class NNOTERepository : Repository<NNOTE>, INNOTERepository
	{
		public NNOTERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface INEWSVIEWTARGETRepository : IRepository<NEWSVIEWTARGET>
	{
	}


	public partial class NEWSVIEWTARGETRepository : Repository<NEWSVIEWTARGET>, INEWSVIEWTARGETRepository
	{
		public NEWSVIEWTARGETRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface INEWS_ATTACHMENTRepository : IRepository<NEWS_ATTACHMENT>
	{
	}


	public partial class NEWS_ATTACHMENTRepository : Repository<NEWS_ATTACHMENT>, INEWS_ATTACHMENTRepository
	{
		public NEWS_ATTACHMENTRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface INEWSRepository : IRepository<NEWS>
	{
	}


	public partial class NEWSRepository : Repository<NEWS>, INEWSRepository
	{
		public NEWSRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IMYLISTDETRepository : IRepository<MYLISTDET>
	{
	}


	public partial class MYLISTDETRepository : Repository<MYLISTDET>, IMYLISTDETRepository
	{
		public MYLISTDETRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IMYLISTRepository : IRepository<MYLIST>
	{
	}


	public partial class MYLISTRepository : Repository<MYLIST>, IMYLISTRepository
	{
		public MYLISTRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IMONTHLYTEACHPOINTCALCDATUMRepository : IRepository<MONTHLYTEACHPOINTCALCDATUM>
	{
	}


	public partial class MONTHLYTEACHPOINTCALCDATUMRepository : Repository<MONTHLYTEACHPOINTCALCDATUM>, IMONTHLYTEACHPOINTCALCDATUMRepository
	{
		public MONTHLYTEACHPOINTCALCDATUMRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IMESSAGEBOARDRepository : IRepository<MESSAGEBOARD>
	{
	}


	public partial class MESSAGEBOARDRepository : Repository<MESSAGEBOARD>, IMESSAGEBOARDRepository
	{
		public MESSAGEBOARDRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IMEMBER_BKRepository : IRepository<MEMBER_BK>
	{
	}


	public partial class MEMBER_BKRepository : Repository<MEMBER_BK>, IMEMBER_BKRepository
	{
		public MEMBER_BKRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IMEMBERRepository : IRepository<MEMBER>
	{
	}


	public partial class MEMBERRepository : Repository<MEMBER>, IMEMBERRepository
	{
		public MEMBERRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IMEDICALVOTELISTRepository : IRepository<MEDICALVOTELIST>
	{
	}


	public partial class MEDICALVOTELISTRepository : Repository<MEDICALVOTELIST>, IMEDICALVOTELISTRepository
	{
		public MEDICALVOTELISTRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IMEDICALTEACHPOINTRepository : IRepository<MEDICALTEACHPOINT>
	{
	}


	public partial class MEDICALTEACHPOINTRepository : Repository<MEDICALTEACHPOINT>, IMEDICALTEACHPOINTRepository
	{
		public MEDICALTEACHPOINTRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface ILOGINLOGRepository : IRepository<LOGINLOG>
	{
	}


	public partial class LOGINLOGRepository : Repository<LOGINLOG>, ILOGINLOGRepository
	{
		public LOGINLOGRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IJOBFORMSETTINGRepository : IRepository<JOBFORMSETTING>
	{
	}


	public partial class JOBFORMSETTINGRepository : Repository<JOBFORMSETTING>, IJOBFORMSETTINGRepository
	{
		public JOBFORMSETTINGRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IIMPORTTEMPRepository : IRepository<IMPORTTEMP>
	{
	}


	public partial class IMPORTTEMPRepository : Repository<IMPORTTEMP>, IIMPORTTEMPRepository
	{
		public IMPORTTEMPRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IIKASA_UPLOADFILERepository : IRepository<IKASA_UPLOADFILE>
	{
	}


	public partial class IKASA_UPLOADFILERepository : Repository<IKASA_UPLOADFILE>, IIKASA_UPLOADFILERepository
	{
		public IKASA_UPLOADFILERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IIKASA_OSCEEXAMSTAGERepository : IRepository<IKASA_OSCEEXAMSTAGE>
	{
	}


	public partial class IKASA_OSCEEXAMSTAGERepository : Repository<IKASA_OSCEEXAMSTAGE>, IIKASA_OSCEEXAMSTAGERepository
	{
		public IKASA_OSCEEXAMSTAGERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IIKASA_OSCEEXAMSCORERepository : IRepository<IKASA_OSCEEXAMSCORE>
	{
	}


	public partial class IKASA_OSCEEXAMSCORERepository : Repository<IKASA_OSCEEXAMSCORE>, IIKASA_OSCEEXAMSCORERepository
	{
		public IKASA_OSCEEXAMSCORERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IIKASA_OSCEEXAMRepository : IRepository<IKASA_OSCEEXAM>
	{
	}


	public partial class IKASA_OSCEEXAMRepository : Repository<IKASA_OSCEEXAM>, IIKASA_OSCEEXAMRepository
	{
		public IKASA_OSCEEXAMRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IIKASA_MENUREFRepository : IRepository<IKASA_MENUREF>
	{
	}


	public partial class IKASA_MENUREFRepository : Repository<IKASA_MENUREF>, IIKASA_MENUREFRepository
	{
		public IKASA_MENUREFRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IIKASA_MENUPARAMRepository : IRepository<IKASA_MENUPARAM>
	{
	}


	public partial class IKASA_MENUPARAMRepository : Repository<IKASA_MENUPARAM>, IIKASA_MENUPARAMRepository
	{
		public IKASA_MENUPARAMRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IIKASA_MENURepository : IRepository<IKASA_MENU>
	{
	}


	public partial class IKASA_MENURepository : Repository<IKASA_MENU>, IIKASA_MENURepository
	{
		public IKASA_MENURepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IIKASA_IPDDATACOUNTRepository : IRepository<IKASA_IPDDATACOUNT>
	{
	}


	public partial class IKASA_IPDDATACOUNTRepository : Repository<IKASA_IPDDATACOUNT>, IIKASA_IPDDATACOUNTRepository
	{
		public IKASA_IPDDATACOUNTRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IIKASA_ERCASE_EVALDETRepository : IRepository<IKASA_ERCASE_EVALDET>
	{
	}


	public partial class IKASA_ERCASE_EVALDETRepository : Repository<IKASA_ERCASE_EVALDET>, IIKASA_ERCASE_EVALDETRepository
	{
		public IKASA_ERCASE_EVALDETRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IIKASA_ERCASE_EVALRepository : IRepository<IKASA_ERCASE_EVAL>
	{
	}


	public partial class IKASA_ERCASE_EVALRepository : Repository<IKASA_ERCASE_EVAL>, IIKASA_ERCASE_EVALRepository
	{
		public IKASA_ERCASE_EVALRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IIKASA_ERCASERepository : IRepository<IKASA_ERCASE>
	{
	}


	public partial class IKASA_ERCASERepository : Repository<IKASA_ERCASE>, IIKASA_ERCASERepository
	{
		public IKASA_ERCASERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IIKASA_ACTUPLOADFILERepository : IRepository<IKASA_ACTUPLOADFILE>
	{
	}


	public partial class IKASA_ACTUPLOADFILERepository : Repository<IKASA_ACTUPLOADFILE>, IIKASA_ACTUPLOADFILERepository
	{
		public IKASA_ACTUPLOADFILERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IHEALTEACHTIMERATERepository : IRepository<HEALTEACHTIMERATE>
	{
	}


	public partial class HEALTEACHTIMERATERepository : Repository<HEALTEACHTIMERATE>, IHEALTEACHTIMERATERepository
	{
		public HEALTEACHTIMERATERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IHEALTEACHTIMERepository : IRepository<HEALTEACHTIME>
	{
	}


	public partial class HEALTEACHTIMERepository : Repository<HEALTEACHTIME>, IHEALTEACHTIMERepository
	{
		public HEALTEACHTIMERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IGOODVSDATADERepository : IRepository<GOODVSDATADE>
	{
	}


	public partial class GOODVSDATADERepository : Repository<GOODVSDATADE>, IGOODVSDATADERepository
	{
		public GOODVSDATADERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IGOODVSDATUMRepository : IRepository<GOODVSDATUM>
	{
	}


	public partial class GOODVSDATUMRepository : Repository<GOODVSDATUM>, IGOODVSDATUMRepository
	{
		public GOODVSDATUMRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORMCATEGORYREFRepository : IRepository<FORMCATEGORYREF>
	{
	}


	public partial class FORMCATEGORYREFRepository : Repository<FORMCATEGORYREF>, IFORMCATEGORYREFRepository
	{
		public FORMCATEGORYREFRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORMCATEGORYRepository : IRepository<FORMCATEGORY>
	{
	}


	public partial class FORMCATEGORYRepository : Repository<FORMCATEGORY>, IFORMCATEGORYRepository
	{
		public FORMCATEGORYRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_TODO_LISTRepository : IRepository<FORM_TODO_LIST>
	{
	}


	public partial class FORM_TODO_LISTRepository : Repository<FORM_TODO_LIST>, IFORM_TODO_LISTRepository
	{
		public FORM_TODO_LISTRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_TEMPLATES_BKRepository : IRepository<FORM_TEMPLATES_BK>
	{
	}


	public partial class FORM_TEMPLATES_BKRepository : Repository<FORM_TEMPLATES_BK>, IFORM_TEMPLATES_BKRepository
	{
		public FORM_TEMPLATES_BKRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_TEMPLATERepository : IRepository<FORM_TEMPLATE>
	{
	}


	public partial class FORM_TEMPLATERepository : Repository<FORM_TEMPLATE>, IFORM_TEMPLATERepository
	{
		public FORM_TEMPLATERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_SUBMIT_SQLRepository : IRepository<FORM_TEMPLATE_SUBMIT_SQL>
	{
	}


	public partial class FORM_TEMPLATE_SUBMIT_SQLRepository : Repository<FORM_TEMPLATE_SUBMIT_SQL>, IFORM_TEMPLATE_SUBMIT_SQLRepository
	{
		public FORM_TEMPLATE_SUBMIT_SQLRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_SQLRepository : IRepository<FORM_TEMPLATE_SQL>
	{
	}


	public partial class FORM_TEMPLATE_SQLRepository : Repository<FORM_TEMPLATE_SQL>, IFORM_TEMPLATE_SQLRepository
	{
		public FORM_TEMPLATE_SQLRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_SINGLERepository : IRepository<FORM_TEMPLATE_SINGLE>
	{
	}


	public partial class FORM_TEMPLATE_SINGLERepository : Repository<FORM_TEMPLATE_SINGLE>, IFORM_TEMPLATE_SINGLERepository
	{
		public FORM_TEMPLATE_SINGLERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_SCRIPTRepository : IRepository<FORM_TEMPLATE_SCRIPT>
	{
	}


	public partial class FORM_TEMPLATE_SCRIPTRepository : Repository<FORM_TEMPLATE_SCRIPT>, IFORM_TEMPLATE_SCRIPTRepository
	{
		public FORM_TEMPLATE_SCRIPTRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_PERMISSIONRepository : IRepository<FORM_TEMPLATE_PERMISSION>
	{
	}


	public partial class FORM_TEMPLATE_PERMISSIONRepository : Repository<FORM_TEMPLATE_PERMISSION>, IFORM_TEMPLATE_PERMISSIONRepository
	{
		public FORM_TEMPLATE_PERMISSIONRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_NECESSARYRepository : IRepository<FORM_TEMPLATE_NECESSARY>
	{
	}


	public partial class FORM_TEMPLATE_NECESSARYRepository : Repository<FORM_TEMPLATE_NECESSARY>, IFORM_TEMPLATE_NECESSARYRepository
	{
		public FORM_TEMPLATE_NECESSARYRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_LIBRARY_OPTIONRepository : IRepository<FORM_TEMPLATE_LIBRARY_OPTION>
	{
	}


	public partial class FORM_TEMPLATE_LIBRARY_OPTIONRepository : Repository<FORM_TEMPLATE_LIBRARY_OPTION>, IFORM_TEMPLATE_LIBRARY_OPTIONRepository
	{
		public FORM_TEMPLATE_LIBRARY_OPTIONRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_LIBRARYRepository : IRepository<FORM_TEMPLATE_LIBRARY>
	{
	}


	public partial class FORM_TEMPLATE_LIBRARYRepository : Repository<FORM_TEMPLATE_LIBRARY>, IFORM_TEMPLATE_LIBRARYRepository
	{
		public FORM_TEMPLATE_LIBRARYRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_IMAGERepository : IRepository<FORM_TEMPLATE_IMAGE>
	{
	}


	public partial class FORM_TEMPLATE_IMAGERepository : Repository<FORM_TEMPLATE_IMAGE>, IFORM_TEMPLATE_IMAGERepository
	{
		public FORM_TEMPLATE_IMAGERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_GROUPS_BKRepository : IRepository<FORM_TEMPLATE_GROUPS_BK>
	{
	}


	public partial class FORM_TEMPLATE_GROUPS_BKRepository : Repository<FORM_TEMPLATE_GROUPS_BK>, IFORM_TEMPLATE_GROUPS_BKRepository
	{
		public FORM_TEMPLATE_GROUPS_BKRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_GROUPRepository : IRepository<FORM_TEMPLATE_GROUP>
	{
	}


	public partial class FORM_TEMPLATE_GROUPRepository : Repository<FORM_TEMPLATE_GROUP>, IFORM_TEMPLATE_GROUPRepository
	{
		public FORM_TEMPLATE_GROUPRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_EXPRESSIONRepository : IRepository<FORM_TEMPLATE_EXPRESSION>
	{
	}


	public partial class FORM_TEMPLATE_EXPRESSIONRepository : Repository<FORM_TEMPLATE_EXPRESSION>, IFORM_TEMPLATE_EXPRESSIONRepository
	{
		public FORM_TEMPLATE_EXPRESSIONRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_ELEMENTS_BKRepository : IRepository<FORM_TEMPLATE_ELEMENTS_BK>
	{
	}


	public partial class FORM_TEMPLATE_ELEMENTS_BKRepository : Repository<FORM_TEMPLATE_ELEMENTS_BK>, IFORM_TEMPLATE_ELEMENTS_BKRepository
	{
		public FORM_TEMPLATE_ELEMENTS_BKRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_ELEMENTRepository : IRepository<FORM_TEMPLATE_ELEMENT>
	{
	}


	public partial class FORM_TEMPLATE_ELEMENTRepository : Repository<FORM_TEMPLATE_ELEMENT>, IFORM_TEMPLATE_ELEMENTRepository
	{
		public FORM_TEMPLATE_ELEMENTRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_ELEMENT_READONLYRepository : IRepository<FORM_TEMPLATE_ELEMENT_READONLY>
	{
	}


	public partial class FORM_TEMPLATE_ELEMENT_READONLYRepository : Repository<FORM_TEMPLATE_ELEMENT_READONLY>, IFORM_TEMPLATE_ELEMENT_READONLYRepository
	{
		public FORM_TEMPLATE_ELEMENT_READONLYRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_TEMPLATE_DYNAMIC_ELEMENTRepository : IRepository<FORM_TEMPLATE_DYNAMIC_ELEMENT>
	{
	}


	public partial class FORM_TEMPLATE_DYNAMIC_ELEMENTRepository : Repository<FORM_TEMPLATE_DYNAMIC_ELEMENT>, IFORM_TEMPLATE_DYNAMIC_ELEMENTRepository
	{
		public FORM_TEMPLATE_DYNAMIC_ELEMENTRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_OPTION_TYPERepository : IRepository<FORM_OPTION_TYPE>
	{
	}


	public partial class FORM_OPTION_TYPERepository : Repository<FORM_OPTION_TYPE>, IFORM_OPTION_TYPERepository
	{
		public FORM_OPTION_TYPERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_INSTANCES_DELLOGRepository : IRepository<FORM_INSTANCES_DELLOG>
	{
	}


	public partial class FORM_INSTANCES_DELLOGRepository : Repository<FORM_INSTANCES_DELLOG>, IFORM_INSTANCES_DELLOGRepository
	{
		public FORM_INSTANCES_DELLOGRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_INSTANCES_BKRepository : IRepository<FORM_INSTANCES_BK>
	{
	}


	public partial class FORM_INSTANCES_BKRepository : Repository<FORM_INSTANCES_BK>, IFORM_INSTANCES_BKRepository
	{
		public FORM_INSTANCES_BKRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_INSTANCERepository : IRepository<FORM_INSTANCE>
	{
	}


	public partial class FORM_INSTANCERepository : Repository<FORM_INSTANCE>, IFORM_INSTANCERepository
	{
		public FORM_INSTANCERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_INSTANCE_TRANSLOGRepository : IRepository<FORM_INSTANCE_TRANSLOG>
	{
	}


	public partial class FORM_INSTANCE_TRANSLOGRepository : Repository<FORM_INSTANCE_TRANSLOG>, IFORM_INSTANCE_TRANSLOGRepository
	{
		public FORM_INSTANCE_TRANSLOGRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_INSTANCE_TARGETS_DELLOGRepository : IRepository<FORM_INSTANCE_TARGETS_DELLOG>
	{
	}


	public partial class FORM_INSTANCE_TARGETS_DELLOGRepository : Repository<FORM_INSTANCE_TARGETS_DELLOG>, IFORM_INSTANCE_TARGETS_DELLOGRepository
	{
		public FORM_INSTANCE_TARGETS_DELLOGRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_INSTANCE_TARGETS_BKRepository : IRepository<FORM_INSTANCE_TARGETS_BK>
	{
	}


	public partial class FORM_INSTANCE_TARGETS_BKRepository : Repository<FORM_INSTANCE_TARGETS_BK>, IFORM_INSTANCE_TARGETS_BKRepository
	{
		public FORM_INSTANCE_TARGETS_BKRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_INSTANCE_TARGETRepository : IRepository<FORM_INSTANCE_TARGET>
	{
	}


	public partial class FORM_INSTANCE_TARGETRepository : Repository<FORM_INSTANCE_TARGET>, IFORM_INSTANCE_TARGETRepository
	{
		public FORM_INSTANCE_TARGETRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_INSTANCE_RETURN_LOGRepository : IRepository<FORM_INSTANCE_RETURN_LOG>
	{
	}


	public partial class FORM_INSTANCE_RETURN_LOGRepository : Repository<FORM_INSTANCE_RETURN_LOG>, IFORM_INSTANCE_RETURN_LOGRepository
	{
		public FORM_INSTANCE_RETURN_LOGRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_INSTANCE_EXPRESSIONS_BKRepository : IRepository<FORM_INSTANCE_EXPRESSIONS_BK>
	{
	}


	public partial class FORM_INSTANCE_EXPRESSIONS_BKRepository : Repository<FORM_INSTANCE_EXPRESSIONS_BK>, IFORM_INSTANCE_EXPRESSIONS_BKRepository
	{
		public FORM_INSTANCE_EXPRESSIONS_BKRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_INSTANCE_EXPRESSIONRepository : IRepository<FORM_INSTANCE_EXPRESSION>
	{
	}


	public partial class FORM_INSTANCE_EXPRESSIONRepository : Repository<FORM_INSTANCE_EXPRESSION>, IFORM_INSTANCE_EXPRESSIONRepository
	{
		public FORM_INSTANCE_EXPRESSIONRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_INSTANCE_ELEMENTS_BKRepository : IRepository<FORM_INSTANCE_ELEMENTS_BK>
	{
	}


	public partial class FORM_INSTANCE_ELEMENTS_BKRepository : Repository<FORM_INSTANCE_ELEMENTS_BK>, IFORM_INSTANCE_ELEMENTS_BKRepository
	{
		public FORM_INSTANCE_ELEMENTS_BKRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_INSTANCE_ELEMENTRepository : IRepository<FORM_INSTANCE_ELEMENT>
	{
	}


	public partial class FORM_INSTANCE_ELEMENTRepository : Repository<FORM_INSTANCE_ELEMENT>, IFORM_INSTANCE_ELEMENTRepository
	{
		public FORM_INSTANCE_ELEMENTRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_INSTANCE_BLOCKRepository : IRepository<FORM_INSTANCE_BLOCK>
	{
	}


	public partial class FORM_INSTANCE_BLOCKRepository : Repository<FORM_INSTANCE_BLOCK>, IFORM_INSTANCE_BLOCKRepository
	{
		public FORM_INSTANCE_BLOCKRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFORM_INSTANCE_ATTACHMENTRepository : IRepository<FORM_INSTANCE_ATTACHMENT>
	{
	}


	public partial class FORM_INSTANCE_ATTACHMENTRepository : Repository<FORM_INSTANCE_ATTACHMENT>, IFORM_INSTANCE_ATTACHMENTRepository
	{
		public FORM_INSTANCE_ATTACHMENTRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IFIXMEMBERDATUMRepository : IRepository<FIXMEMBERDATUM>
	{
	}


	public partial class FIXMEMBERDATUMRepository : Repository<FIXMEMBERDATUM>, IFIXMEMBERDATUMRepository
	{
		public FIXMEMBERDATUMRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IELEARNINGITEMRepository : IRepository<ELEARNINGITEM>
	{
	}


	public partial class ELEARNINGITEMRepository : Repository<ELEARNINGITEM>, IELEARNINGITEMRepository
	{
		public ELEARNINGITEMRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IELEARNINGEMPITEMLOGRepository : IRepository<ELEARNINGEMPITEMLOG>
	{
	}


	public partial class ELEARNINGEMPITEMLOGRepository : Repository<ELEARNINGEMPITEMLOG>, IELEARNINGEMPITEMLOGRepository
	{
		public ELEARNINGEMPITEMLOGRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IELEARNINGEMPITEMRepository : IRepository<ELEARNINGEMPITEM>
	{
	}


	public partial class ELEARNINGEMPITEMRepository : Repository<ELEARNINGEMPITEM>, IELEARNINGEMPITEMRepository
	{
		public ELEARNINGEMPITEMRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IELEARNINGCLASSRepository : IRepository<ELEARNINGCLASS>
	{
	}


	public partial class ELEARNINGCLASSRepository : Repository<ELEARNINGCLASS>, IELEARNINGCLASSRepository
	{
		public ELEARNINGCLASSRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IELEARNINGBOOKINGRepository : IRepository<ELEARNINGBOOKING>
	{
	}


	public partial class ELEARNINGBOOKINGRepository : Repository<ELEARNINGBOOKING>, IELEARNINGBOOKINGRepository
	{
		public ELEARNINGBOOKINGRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUTERMFORMREQTEMPLATEDETRepository : IRepository<EDUTERMFORMREQTEMPLATEDET>
	{
	}


	public partial class EDUTERMFORMREQTEMPLATEDETRepository : Repository<EDUTERMFORMREQTEMPLATEDET>, IEDUTERMFORMREQTEMPLATEDETRepository
	{
		public EDUTERMFORMREQTEMPLATEDETRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUTERMFORMREQTEMPLATERepository : IRepository<EDUTERMFORMREQTEMPLATE>
	{
	}


	public partial class EDUTERMFORMREQTEMPLATERepository : Repository<EDUTERMFORMREQTEMPLATE>, IEDUTERMFORMREQTEMPLATERepository
	{
		public EDUTERMFORMREQTEMPLATERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUTERMFORMREQRepository : IRepository<EDUTERMFORMREQ>
	{
	}


	public partial class EDUTERMFORMREQRepository : Repository<EDUTERMFORMREQ>, IEDUTERMFORMREQRepository
	{
		public EDUTERMFORMREQRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUTERMFORMINSTANCERepository : IRepository<EDUTERMFORMINSTANCE>
	{
	}


	public partial class EDUTERMFORMINSTANCERepository : Repository<EDUTERMFORMINSTANCE>, IEDUTERMFORMINSTANCERepository
	{
		public EDUTERMFORMINSTANCERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUTERMRepository : IRepository<EDUTERM>
	{
	}


	public partial class EDUTERMRepository : Repository<EDUTERM>, IEDUTERMRepository
	{
		public EDUTERMRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUTEAMRUNDOWNRepository : IRepository<EDUTEAMRUNDOWN>
	{
	}


	public partial class EDUTEAMRUNDOWNRepository : Repository<EDUTEAMRUNDOWN>, IEDUTEAMRUNDOWNRepository
	{
		public EDUTEAMRUNDOWNRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUTEAMMEMBERRUNDOWN_TRANSLOGRepository : IRepository<EDUTEAMMEMBERRUNDOWN_TRANSLOG>
	{
	}


	public partial class EDUTEAMMEMBERRUNDOWN_TRANSLOGRepository : Repository<EDUTEAMMEMBERRUNDOWN_TRANSLOG>, IEDUTEAMMEMBERRUNDOWN_TRANSLOGRepository
	{
		public EDUTEAMMEMBERRUNDOWN_TRANSLOGRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUTEAMMEMBERRUNDOWNRepository : IRepository<EDUTEAMMEMBERRUNDOWN>
	{
	}


	public partial class EDUTEAMMEMBERRUNDOWNRepository : Repository<EDUTEAMMEMBERRUNDOWN>, IEDUTEAMMEMBERRUNDOWNRepository
	{
		public EDUTEAMMEMBERRUNDOWNRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUTEAMMEMBERRepository : IRepository<EDUTEAMMEMBER>
	{
	}


	public partial class EDUTEAMMEMBERRepository : Repository<EDUTEAMMEMBER>, IEDUTEAMMEMBERRepository
	{
		public EDUTEAMMEMBERRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUTEAMRepository : IRepository<EDUTEAM>
	{
	}


	public partial class EDUTEAMRepository : Repository<EDUTEAM>, IEDUTEAMRepository
	{
		public EDUTEAMRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUTEACHERTYPERepository : IRepository<EDUTEACHERTYPE>
	{
	}


	public partial class EDUTEACHERTYPERepository : Repository<EDUTEACHERTYPE>, IEDUTEACHERTYPERepository
	{
		public EDUTEACHERTYPERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUSTOPACTSCHEDULERepository : IRepository<EDUSTOPACTSCHEDULE>
	{
	}


	public partial class EDUSTOPACTSCHEDULERepository : Repository<EDUSTOPACTSCHEDULE>, IEDUSTOPACTSCHEDULERepository
	{
		public EDUSTOPACTSCHEDULERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUSTOPACTATTACHMENTRepository : IRepository<EDUSTOPACTATTACHMENT>
	{
	}


	public partial class EDUSTOPACTATTACHMENTRepository : Repository<EDUSTOPACTATTACHMENT>, IEDUSTOPACTATTACHMENTRepository
	{
		public EDUSTOPACTATTACHMENTRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUSTOPRepository : IRepository<EDUSTOP>
	{
	}


	public partial class EDUSTOPRepository : Repository<EDUSTOP>, IEDUSTOPRepository
	{
		public EDUSTOPRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUSETTINGRepository : IRepository<EDUSETTING>
	{
	}


	public partial class EDUSETTINGRepository : Repository<EDUSETTING>, IEDUSETTINGRepository
	{
		public EDUSETTINGRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUSENTENCERepository : IRepository<EDUSENTENCE>
	{
	}


	public partial class EDUSENTENCERepository : Repository<EDUSENTENCE>, IEDUSENTENCERepository
	{
		public EDUSENTENCERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUSCORERepository : IRepository<EDUSCORE>
	{
	}


	public partial class EDUSCORERepository : Repository<EDUSCORE>, IEDUSCORERepository
	{
		public EDUSCORERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUREFTEACHERRepository : IRepository<EDUREFTEACHER>
	{
	}


	public partial class EDUREFTEACHERRepository : Repository<EDUREFTEACHER>, IEDUREFTEACHERRepository
	{
		public EDUREFTEACHERRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUQUESTIONRepository : IRepository<EDUQUESTION>
	{
	}


	public partial class EDUQUESTIONRepository : Repository<EDUQUESTION>, IEDUQUESTIONRepository
	{
		public EDUQUESTIONRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUPASSPORTTEMPLATETARGETRepository : IRepository<EDUPASSPORTTEMPLATETARGET>
	{
	}


	public partial class EDUPASSPORTTEMPLATETARGETRepository : Repository<EDUPASSPORTTEMPLATETARGET>, IEDUPASSPORTTEMPLATETARGETRepository
	{
		public EDUPASSPORTTEMPLATETARGETRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUPASSPORTTEMPLATEITEMRepository : IRepository<EDUPASSPORTTEMPLATEITEM>
	{
	}


	public partial class EDUPASSPORTTEMPLATEITEMRepository : Repository<EDUPASSPORTTEMPLATEITEM>, IEDUPASSPORTTEMPLATEITEMRepository
	{
		public EDUPASSPORTTEMPLATEITEMRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUPASSPORTTEMPLATERepository : IRepository<EDUPASSPORTTEMPLATE>
	{
	}


	public partial class EDUPASSPORTTEMPLATERepository : Repository<EDUPASSPORTTEMPLATE>, IEDUPASSPORTTEMPLATERepository
	{
		public EDUPASSPORTTEMPLATERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUPASSPORTPREFRepository : IRepository<EDUPASSPORTPREF>
	{
	}


	public partial class EDUPASSPORTPREFRepository : Repository<EDUPASSPORTPREF>, IEDUPASSPORTPREFRepository
	{
		public EDUPASSPORTPREFRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUPASSPORTITEMTARGETRepository : IRepository<EDUPASSPORTITEMTARGET>
	{
	}


	public partial class EDUPASSPORTITEMTARGETRepository : Repository<EDUPASSPORTITEMTARGET>, IEDUPASSPORTITEMTARGETRepository
	{
		public EDUPASSPORTITEMTARGETRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUPASSPORTITEMDETRepository : IRepository<EDUPASSPORTITEMDET>
	{
	}


	public partial class EDUPASSPORTITEMDETRepository : Repository<EDUPASSPORTITEMDET>, IEDUPASSPORTITEMDETRepository
	{
		public EDUPASSPORTITEMDETRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUPASSPORTITEMRepository : IRepository<EDUPASSPORTITEM>
	{
	}


	public partial class EDUPASSPORTITEMRepository : Repository<EDUPASSPORTITEM>, IEDUPASSPORTITEMRepository
	{
		public EDUPASSPORTITEMRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUPASSPORTINSTANCERepository : IRepository<EDUPASSPORTINSTANCE>
	{
	}


	public partial class EDUPASSPORTINSTANCERepository : Repository<EDUPASSPORTINSTANCE>, IEDUPASSPORTINSTANCERepository
	{
		public EDUPASSPORTINSTANCERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUPASSPORTINSITEMREJECTHIRepository : IRepository<EDUPASSPORTINSITEMREJECTHI>
	{
	}


	public partial class EDUPASSPORTINSITEMREJECTHIRepository : Repository<EDUPASSPORTINSITEMREJECTHI>, IEDUPASSPORTINSITEMREJECTHIRepository
	{
		public EDUPASSPORTINSITEMREJECTHIRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUPASSPORTINSITEMREFRepository : IRepository<EDUPASSPORTINSITEMREF>
	{
	}


	public partial class EDUPASSPORTINSITEMREFRepository : Repository<EDUPASSPORTINSITEMREF>, IEDUPASSPORTINSITEMREFRepository
	{
		public EDUPASSPORTINSITEMREFRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUPASSPORTINSITEMDETRepository : IRepository<EDUPASSPORTINSITEMDET>
	{
	}


	public partial class EDUPASSPORTINSITEMDETRepository : Repository<EDUPASSPORTINSITEMDET>, IEDUPASSPORTINSITEMDETRepository
	{
		public EDUPASSPORTINSITEMDETRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUPASSPORTINSITEMRepository : IRepository<EDUPASSPORTINSITEM>
	{
	}


	public partial class EDUPASSPORTINSITEMRepository : Repository<EDUPASSPORTINSITEM>, IEDUPASSPORTINSITEMRepository
	{
		public EDUPASSPORTINSITEMRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUNOTETEMPLATERepository : IRepository<EDUNOTETEMPLATE>
	{
	}


	public partial class EDUNOTETEMPLATERepository : Repository<EDUNOTETEMPLATE>, IEDUNOTETEMPLATERepository
	{
		public EDUNOTETEMPLATERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUNOTELISTRepository : IRepository<EDUNOTELIST>
	{
	}


	public partial class EDUNOTELISTRepository : Repository<EDUNOTELIST>, IEDUNOTELISTRepository
	{
		public EDUNOTELISTRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUNOTEITEMRepository : IRepository<EDUNOTEITEM>
	{
	}


	public partial class EDUNOTEITEMRepository : Repository<EDUNOTEITEM>, IEDUNOTEITEMRepository
	{
		public EDUNOTEITEMRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUNOTERepository : IRepository<EDUNOTE>
	{
	}


	public partial class EDUNOTERepository : Repository<EDUNOTE>, IEDUNOTERepository
	{
		public EDUNOTERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUNOTALERTSETTINGRepository : IRepository<EDUNOTALERTSETTING>
	{
	}


	public partial class EDUNOTALERTSETTINGRepository : Repository<EDUNOTALERTSETTING>, IEDUNOTALERTSETTINGRepository
	{
		public EDUNOTALERTSETTINGRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUMENURepository : IRepository<EDUMENU>
	{
	}


	public partial class EDUMENURepository : Repository<EDUMENU>, IEDUMENURepository
	{
		public EDUMENURepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUFORMTEMPLATETARGETRepository : IRepository<EDUFORMTEMPLATETARGET>
	{
	}


	public partial class EDUFORMTEMPLATETARGETRepository : Repository<EDUFORMTEMPLATETARGET>, IEDUFORMTEMPLATETARGETRepository
	{
		public EDUFORMTEMPLATETARGETRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUFORMTEMPLATELISTRepository : IRepository<EDUFORMTEMPLATELIST>
	{
	}


	public partial class EDUFORMTEMPLATELISTRepository : Repository<EDUFORMTEMPLATELIST>, IEDUFORMTEMPLATELISTRepository
	{
		public EDUFORMTEMPLATELISTRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUFORMSTASTICPERMISSIONRepository : IRepository<EDUFORMSTASTICPERMISSION>
	{
	}


	public partial class EDUFORMSTASTICPERMISSIONRepository : Repository<EDUFORMSTASTICPERMISSION>, IEDUFORMSTASTICPERMISSIONRepository
	{
		public EDUFORMSTASTICPERMISSIONRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUACTVIEWTARGETRepository : IRepository<EDUACTVIEWTARGET>
	{
	}


	public partial class EDUACTVIEWTARGETRepository : Repository<EDUACTVIEWTARGET>, IEDUACTVIEWTARGETRepository
	{
		public EDUACTVIEWTARGETRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUACTTYPEROLEREFRepository : IRepository<EDUACTTYPEROLEREF>
	{
	}


	public partial class EDUACTTYPEROLEREFRepository : Repository<EDUACTTYPEROLEREF>, IEDUACTTYPEROLEREFRepository
	{
		public EDUACTTYPEROLEREFRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUACTTYPEREFRepository : IRepository<EDUACTTYPEREF>
	{
	}


	public partial class EDUACTTYPEREFRepository : Repository<EDUACTTYPEREF>, IEDUACTTYPEREFRepository
	{
		public EDUACTTYPEREFRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUACTTYPEGROUPINGRepository : IRepository<EDUACTTYPEGROUPING>
	{
	}


	public partial class EDUACTTYPEGROUPINGRepository : Repository<EDUACTTYPEGROUPING>, IEDUACTTYPEGROUPINGRepository
	{
		public EDUACTTYPEGROUPINGRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUACTTYPE_BKRepository : IRepository<EDUACTTYPE_BK>
	{
	}


	public partial class EDUACTTYPE_BKRepository : Repository<EDUACTTYPE_BK>, IEDUACTTYPE_BKRepository
	{
		public EDUACTTYPE_BKRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUACTTYPERepository : IRepository<EDUACTTYPE>
	{
	}


	public partial class EDUACTTYPERepository : Repository<EDUACTTYPE>, IEDUACTTYPERepository
	{
		public EDUACTTYPERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUACTTOPICRepository : IRepository<EDUACTTOPIC>
	{
	}


	public partial class EDUACTTOPICRepository : Repository<EDUACTTOPIC>, IEDUACTTOPICRepository
	{
		public EDUACTTOPICRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUACTTARGETRepository : IRepository<EDUACTTARGET>
	{
	}


	public partial class EDUACTTARGETRepository : Repository<EDUACTTARGET>, IEDUACTTARGETRepository
	{
		public EDUACTTARGETRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IEDUACTBOOKINGRepository : IRepository<EDUACTBOOKING>
	{
	}


	public partial class EDUACTBOOKINGRepository : Repository<EDUACTBOOKING>, IEDUACTBOOKINGRepository
	{
		public EDUACTBOOKINGRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IDOCTORPOINTTYPERepository : IRepository<DOCTORPOINTTYPE>
	{
	}


	public partial class DOCTORPOINTTYPERepository : Repository<DOCTORPOINTTYPE>, IDOCTORPOINTTYPERepository
	{
		public DOCTORPOINTTYPERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IDOCTORPOINTCALTYPERepository : IRepository<DOCTORPOINTCALTYPE>
	{
	}


	public partial class DOCTORPOINTCALTYPERepository : Repository<DOCTORPOINTCALTYPE>, IDOCTORPOINTCALTYPERepository
	{
		public DOCTORPOINTCALTYPERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IDOCTORPOINTRepository : IRepository<DOCTORPOINT>
	{
	}


	public partial class DOCTORPOINTRepository : Repository<DOCTORPOINT>, IDOCTORPOINTRepository
	{
		public DOCTORPOINTRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IDEPSECTEMPRepository : IRepository<DEPSECTEMP>
	{
	}


	public partial class DEPSECTEMPRepository : Repository<DEPSECTEMP>, IDEPSECTEMPRepository
	{
		public DEPSECTEMPRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IDEPSECDATUMRepository : IRepository<DEPSECDATUM>
	{
	}


	public partial class DEPSECDATUMRepository : Repository<DEPSECDATUM>, IDEPSECDATUMRepository
	{
		public DEPSECDATUMRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface ICLERKIPDNOTEDATUMRepository : IRepository<CLERKIPDNOTEDATUM>
	{
	}


	public partial class CLERKIPDNOTEDATUMRepository : Repository<CLERKIPDNOTEDATUM>, ICLERKIPDNOTEDATUMRepository
	{
		public CLERKIPDNOTEDATUMRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface ICICBOOKRepository : IRepository<CICBOOK>
	{
	}


	public partial class CICBOOKRepository : Repository<CICBOOK>, ICICBOOKRepository
	{
		public CICBOOKRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IAUTOEDUFORMTEMPLATETARGETRepository : IRepository<AUTOEDUFORMTEMPLATETARGET>
	{
	}


	public partial class AUTOEDUFORMTEMPLATETARGETRepository : Repository<AUTOEDUFORMTEMPLATETARGET>, IAUTOEDUFORMTEMPLATETARGETRepository
	{
		public AUTOEDUFORMTEMPLATETARGETRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IAUTOEDUFORMTEMPLATESIGNERRepository : IRepository<AUTOEDUFORMTEMPLATESIGNER>
	{
	}


	public partial class AUTOEDUFORMTEMPLATESIGNERRepository : Repository<AUTOEDUFORMTEMPLATESIGNER>, IAUTOEDUFORMTEMPLATESIGNERRepository
	{
		public AUTOEDUFORMTEMPLATESIGNERRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IAUTOEDUFORMTEMPLATELISTRepository : IRepository<AUTOEDUFORMTEMPLATELIST>
	{
	}


	public partial class AUTOEDUFORMTEMPLATELISTRepository : Repository<AUTOEDUFORMTEMPLATELIST>, IAUTOEDUFORMTEMPLATELISTRepository
	{
		public AUTOEDUFORMTEMPLATELISTRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IAUTOEDUFORMTEMPLATEEXCEPTRepository : IRepository<AUTOEDUFORMTEMPLATEEXCEPT>
	{
	}


	public partial class AUTOEDUFORMTEMPLATEEXCEPTRepository : Repository<AUTOEDUFORMTEMPLATEEXCEPT>, IAUTOEDUFORMTEMPLATEEXCEPTRepository
	{
		public AUTOEDUFORMTEMPLATEEXCEPTRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IAUTHROLERepository : IRepository<AUTHROLE>
	{
	}


	public partial class AUTHROLERepository : Repository<AUTHROLE>, IAUTHROLERepository
	{
		public AUTHROLERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IAUTHMENURepository : IRepository<AUTHMENU>
	{
	}


	public partial class AUTHMENURepository : Repository<AUTHMENU>, IAUTHMENURepository
	{
		public AUTHMENURepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IACTTYPETREE_TEMPRepository : IRepository<ACTTYPETREE_TEMP>
	{
	}


	public partial class ACTTYPETREE_TEMPRepository : Repository<ACTTYPETREE_TEMP>, IACTTYPETREE_TEMPRepository
	{
		public ACTTYPETREE_TEMPRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IACCOUNTRepository : IRepository<ACCOUNT>
	{
	}


	public partial class ACCOUNTRepository : Repository<ACCOUNT>, IACCOUNTRepository
	{
		public ACCOUNTRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IACCOUNTROLEIMPORTRepository : IRepository<ACCOUNTROLEIMPORT>
	{
	}


	public partial class ACCOUNTROLEIMPORTRepository : Repository<ACCOUNTROLEIMPORT>, IACCOUNTROLEIMPORTRepository
	{
		public ACCOUNTROLEIMPORTRepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


	public partial interface IACCOUNTROLERepository : IRepository<ACCOUNTROLE>
	{
	}


	public partial class ACCOUNTROLERepository : Repository<ACCOUNTROLE>, IACCOUNTROLERepository
	{
		public ACCOUNTROLERepository(IiKASAWebApiContextUnitOfWork unitOfWork) : base(unitOfWork)
		{
		}
	}


}
#pragma warning restore 1591

